### ISSUE TITLE
Discussion on releases

### ISSUE THREAD

**Issue by zachborboa** [php-curl-class/php-curl-class#119]
I'd like to open a discussion on releases. Possible topics:

- [ ] release timelines
- [x] composer/packagist (https://packagist.org/packages/php-curl-class/php-curl-class)
- [x] semantic versioning (http://semver.org/)

Thank you

**Comment by sergeyklay** [comment]
I vote up for SemVer

**Comment by zborboa-google** [comment]
Regarding composer, we have had a few bugs filed in the past related to the packagist being out of date. @failpunk is the current maintainer. Hopefully he can chime in and get that updated (or add me as a maintainer). Thanks

**Comment by zachborboa** [comment]
**release timelines:** will move towards news releases for changes that require incrementing major, minor, and patch changes.

**composer/packagist:** updated maintainer

**semantic versioning:** have been using semantic versioning for some time now
