### ISSUE TITLE
Undefined method `download`

### ISSUE THREAD

**Issue by erayaydin** [php-curl-class/php-curl-class#124]
Hello,
I was downloaded last version of php-curl-class repo. When I want use $curl->download("...","..."); its make PHP Fatal Error.

```
PHP Fatal error:  Call to undefined method Curl\Curl::download() ...
```

My File:

```
use \Curl\Curl;
$image = "...";
$imagedownload = new Curl();
$image->download($image, '/tmp/'.$name.'.png');
```

Thank you, :smile:

**Comment by erayaydin** [comment]
I am searched repo and I see download() method, but when I use `composer update --dev` I can't see download() method in vendor.

composer.json
```
{
    "require": {
        "php-curl-class/php-curl-class": "dev-master"
    }
}
```

composer update
```
nothing to install or update
```

> I think problem is my req. stability in composer.json

**Comment by zborboa-google** [comment]
Hi Eray. I'm not the maintainer of php-curl-class on packagist.org (https://packagist.org/packages/php-curl-class/php-curl-class).

Perhaps we can get @failpunk to update to the latest version or add me as an admin so that I may do so.

**Comment by erayaydin** [comment]
Oh ok, packagist package is old. Please update :+1:
