### ISSUE TITLE
PHP Warning curl_setopt(): cannot represent a stream of type MEMORY as a STDIO FILE*

### ISSUE THREAD

**Issue by flyon** [php-curl-class/php-curl-class#131]
I get this warning when I do a GET request. The result still comes in, but with this warning.
I'm on a windows WAMP installation. 

This SO question (http://stackoverflow.com/questions/6841854/how-to-do-curl-put-requests-with-a-php-memory-file-handle) suggests: try to set rw+ for the file handle or use php://temp instead of memory.

But I'm not sure how to "set rw+ for the file handle", and switching to php://temp would mean changing the code of this library.

**Comment by zachborboa** [comment]
@flyon - make sure you are using the latest HEAD version of php-curl-class

**Comment by zborboa-google** [comment]
Was fixed in 4cb1436 for #110.

**Comment by zachborboa** [comment]
This should no longer be an issue as `CURLOPT_WRITEHEADER` is no longer used.

79d099b9abf39f0df9d9a42d704bb1c11ee6c8e0

**Comment by WebnetMobile** [comment]
You may want to update packagst's repo, as it still serves outdated version: https://packagist.org/packages/php-curl-class/php-curl-class

**Comment by zachborboa** [comment]
@WebnetMobile - I wish I could. I don't have access to update the version on packagist.org

**Comment by WebnetMobile** [comment]
Then at least you should add a warning to your README. If this packagist entry is not your own, yo may want to try to take it over contacting packagist maintainers. Current situation hurts your directly

**Comment by zachborboa** [comment]
@WebnetMobile - updated! thank you
