### ISSUE TITLE
no php documentation / annotation

### ISSUE THREAD

**Issue by someother1** [php-curl-class/php-curl-class#151]
Great Wrapper, i like it, and i use it often - thank you!

It would be even nicer if someone could add correct php annotation.
it would improve the workflow a lot. (eg autocomplete)

kindly regards

**Comment by zborboa-google** [comment]
We may be able to add annotations. What IDE/plugins are you using?
Thanks

**Comment by someother1** [comment]
Netbeans 8.0.2 is currently my preferred IDE.
Just the Netebans "HTML5 & PHP" Package without any other Plugins.

The Workflow with correctly setted Annotations is amazing!

Kindly Regards

**Comment by zachborboa** [comment]
Here's a post on Netbeans annotation support
https://blogs.oracle.com/netbeansphp/entry/brand_new_annotations_support
