### ISSUE TITLE
Add Type Hinting in method declarations

### ISSUE THREAD

**Issue by zborboa-g** [php-curl-class/php-curl-class#152]
https://php.net/manual/en/language.oop5.typehinting.php

**Comment by gotardo** [comment]
Hi,
Both type hintings for params and return types could be cool. But, is backwards compatibility a 'must' in the project? May be it is interesting to start a new version for PHP7.x.

**Comment by zachborboa** [comment]
Hi. Backwards compatibility is ideal, but not a strict rule. We're tracking changes permitted by PHP version in #380.

Closing this in favor of #380.
