### ISSUE TITLE
Add documentation on readthedocs.org

### ISSUE THREAD

**Issue by zachborboa** [php-curl-class/php-curl-class#153]
Examples:

https://phpmyadmin.readthedocs.org/en/latest/
https://github.com/phpmyadmin/phpmyadmin/blob/master/doc/index.rst

http://docs.guzzlephp.org/en/latest/
https://github.com/guzzle/guzzle/blob/master/docs/index.rst

**Comment by zachborboa** [comment]
Use Read the Docs [webhook](https://help.github.com/articles/about-webhooks/).
Use [markdown](https://docs.readthedocs.org/en/latest/getting_started.html#in-markdown).

**Comment by zborboa-google** [comment]
Also replace "Quick Start and Examples" section with a "Documentation" section.

"Documentation is available at https://www.example.com/"

**Comment by zachborboa** [comment]
This library is fairly intuitive. For more info, see examples https://github.com/php-curl-class/php-curl-class/tree/master/examples
