### ISSUE TITLE
[NFR] Non-blocking cURL calls

### ISSUE THREAD

**Issue by temuri416** [php-curl-class/php-curl-class#165]
Hi,

Thanks for the nice library!

Would you consider implementing non-blocking cURL calls?

Cheers!

**Comment by zachborboa** [comment]
Hi,`MultiCurl` is available for this.

```php
$multi_curl = new MultiCurl('https://www.example.com/search');

$multi_curl->complete(function($instance) {
    // Call completed. Do something.
});

$multi_curl->addGet(array('q' => 'foo'));
$multi_curl->addGet(array('q' => 'bar'));
$multi_curl->addGet(array('q' => 'baz'));
$multi_curl->start();
```

**Comment by temuri416** [comment]
Hi,

I've tried this against my local API server's `wait` action:

```php
$multi_curl = new \Curl\MultiCurl('http://api.example.com/v1/wait');

// NOT INTERESTED IN A CALLBACK
//$multi_curl->complete(function($instance) {
//});

$multi_curl->addGet(array('some' => 'var'));
$multi_curl->start();

echo 'OK';
```

`wait` action does nothing except `sleep(10)`.

I executing above example makes a blocking call to API server - PHP script gets blocked for 10 seconds.

I was expecting that 'OK' would be executed immediately acted `->start()` call (i.e. non-blocking).

Am I missing something?

Thanks!

**Comment by zborboa-google** [comment]
I don't believe we can have non-blocking in the way you described. `start()` keeps curl alive with `curl_multi_select()` and `curl_multi_exec()`. By returning immediately, requests would be left unfinished.

The example on the `curl_multi_exec` documentation is similar to how it is achieved in php-curl-class.
https://php.net/curl_multi_exec#refsect1-function.curl-multi-exec-examples

**Comment by temuri416** [comment]
yes, I have realised that too. after reading more about it, it seems the only way to achieve what I need is to fork a process or use gearman/beanstalk..
