### ISSUE TITLE
MultiCurl not work

### ISSUE THREAD

**Issue by Filix** [php-curl-class/php-curl-class#168]
I tried version dev-master, 3.4.3, 3.4.4. No one works.
It never callback my succss, error or complete function. 
So I can not get the response.

My code:

        $multi_curl = new MultiCurl();
        $multi_curl->addGet('http://www.baidu.com');
        $multi_curl->addGet('http://www.qq.com');
        $multi_curl->success(function($instance) {
            echo 'call to "' . $instance->url . '" was successful.' . "\n";
        });
        $multi_curl->error(function($instance) {
            echo 'call to "' . $instance->url . '" was unsuccessful.' . "\n";
        });
        $multi_curl->complete(function($instance) {
            echo 'call completed' . "\n";
        });
        $multi_curl->start();

**Comment by zachborboa** [comment]
Hi. Order matters in this case. Set your callbacks before adding requests (`addGet()`).

```php
$multi_curl = new MultiCurl();
$multi_curl->success(function($instance) {
    echo 'call to "' . $instance->url . '" was successful.' . "\n";
});
$multi_curl->error(function($instance) {
    echo 'call to "' . $instance->url . '" was unsuccessful.' . "\n";
});
$multi_curl->complete(function($instance) {
    echo 'call completed' . "\n";
});
$multi_curl->addGet('http://www.baidu.com');
$multi_curl->addGet('http://www.qq.com');
$multi_curl->start();
```

**Comment by Filix** [comment]
@zachborboa thank you! It works well!
