### ISSUE TITLE
delete() doesnt allow sending data in body

### ISSUE THREAD

**Issue by Kehet** [php-curl-class/php-curl-class#171]
I was using Spotify API with this class but noticed that \Curl\Curl::delete() doesn't allow sending data in body of request. I'm not sure what W3 specification says about this, but it sure should be possible to use this way.

Also, whole that idea second argument sometimes being body and sometimes part of url is confusing. Would it be better to separate those two data types into own arguments?

Also, I would like to set custom body to request (eg. Spotify API requires json formatted data on DELETE -method). Is this possible on this version / should this also be possible?

**Comment by zachborboa** [comment]
Hi @Kehet. The spec doesn't explicitly forbid a body in a delete. I'll add a third parameter in `delete()` to allow body data.

Before:
```php
$curl->delete($url, $query_parameters);
```
After
```php
$curl->delete($url, $query_parameters, $request_body);
```

http://stackoverflow.com/questions/299628/is-an-entity-body-allowed-for-an-http-delete-request
http://stackoverflow.com/questions/14323716/restful-alternatives-to-delete-request-body
