### ISSUE TITLE
Post to some api and get the return data

### ISSUE THREAD

**Issue by flyyang** [php-curl-class/php-curl-class#172]
Hi there,

I use multi_curl to post some data to an REST API.
```
$multi_curl->addPost(APP_SERVER.'/v1/solutions', $data);
```
The REST API received the request and return the result. The result can be seen use `curl` command line tool.
```
curl -H -x blabla..
```
How can I get the API return result use $multi_curl? I tried the success method but not worked.

```
$multi_curl->success(function(data) {
// data  == null
 });
```
or
```
$multi_curl->success(function($multi_cul) {
 $Log->logger($multi_curl->response);//no data
 });
```
Help!

**Comment by zachborboa** [comment]
Hi. Here is a multicurl example with callbacks.
https://github.com/php-curl-class/php-curl-class/blob/master/examples/multi_curl_get_callbacks.php

**Comment by flyyang** [comment]
Thanks for the reply.

I have seen the example before and used nearly the same code as the example.

Now the success method was fired, but don't know where to get the POST return data.

**Comment by flyyang** [comment]
Get the data from $instance->response.
```
$multi_curl->success(function($instance) {
    echo 'call to "' . $instance->url . '" was successful.' . "\n";
    echo 'response: ' . $instance->response . "\n";
});
$multi_curl->error(function($instance) {
    echo 'call to "' . $instance->url . '" was unsuccessful.' . "\n";
    echo 'error code: ' . $instance->error_code . "\n";
    echo 'error message: ' . $instance->error_message . "\n";
});
$multi_curl->complete(function($instance) {
    echo 'call completed' . "\n";
});
```

What the $instance object contain anyway?Is there a doc for this object?

**Comment by ricwein** [comment]
Hey, did you take notice of the correct order of calling the multi_curl methods? see [here](https://github.com/php-curl-class/php-curl-class/issues/168#issuecomment-93427351). This could prevent you from getting correct responses. So first call the callback methods like `complete()` followed by addinge the request `addPost()`.

To get all available variables of the `$instance` object just try printing it with `print_r($instance);` or look in the sourcecode of the [curl-class](https://github.com/php-curl-class/php-curl-class/blob/master/src/Curl/Curl.php) line 10-34.

**Comment by flyyang** [comment]
Problem solved.Thanks @ricwein.
