### ISSUE TITLE
Issue with setCookie function.

### ISSUE THREAD

**Issue by winkexp** [php-curl-class/php-curl-class#174]
Hi,

I got an issue with setCookie function, the http_build_query will do urlencode to the cookie array/string, which will change the actual cookie value hence get rejected by the server.
So I added a urldecode after http_build_query.

    public function setCookie($key, $value)
    {
        $this->cookies[$key] = $value;
        //$this->setOpt(CURLOPT_COOKIE, str_replace('+', '%20', http_build_query($this->cookies, '', '; ')));
        $this->setOpt(CURLOPT_COOKIE, str_replace('+', '%20', urldecode(http_build_query($this->cookies, '', '; '))));
    }

Thanks,
Wayne

**Comment by zachborboa** [comment]
Hi Wayne. What is the value of the $value parameters passed to the `setCookie` function? Also, what is the expected value of the cookie after calling the function? Thanks

**Comment by winkexp** [comment]
JSESSIONID=0000wd-PcsB3bZ-KzYGAqm_rKlm:17925chrl

This is a example of the cookie, so it will be changed by urlencode in http_build_query sometimes when it contains the special chars.

**Comment by winkexp** [comment]
Cheers,
