### ISSUE TITLE
Content-Length is not automatically added in Post function

### ISSUE THREAD

**Issue by winkexp** [php-curl-class/php-curl-class#175]
Hi,

I see the Content-Length is not added automatically added in Post function, but it's in Put funciton, so i have modified it slightly as below:

    public function post($url, $data = array())
    {
        if (is_array($url)) {
            $data = $url;
            $url = $this->base_url;
        }
        
		$post_data = $this->buildPostData($data);
        if (is_array($data) && empty($data)) {
            $this->setHeader('Content-Length', '0');
        }else{
        	$this->setHeader('Content-Length', strlen($post_data));
        }

        $this->setURL($url);
        $this->setOpt(CURLOPT_CUSTOMREQUEST, 'POST');
        $this->setOpt(CURLOPT_POST, true);
        $this->setOpt(CURLOPT_POSTFIELDS, $post_data);
        return $this->exec();
    }

Thanks,
Wayne

**Comment by zachborboa** [comment]
Hi Wayne. Content-Length is added automatically by cURL.

```php
$curl = new Curl();
$curl->post('http://www.example.com/', 'test');
var_dump($curl->request_headers);
```

Response
```
class Curl\CaseInsensitiveArray#4 (1) {
  private $container =>
  array(6) {
    'Request-Line' =>
    string(15) "POST / HTTP/1.1"
    'User-Agent' =>
    string(94) "PHP-Curl-Class/3.4.5 (+https://github.com/php-curl-class/php-curl-class) PHP/5.6.5 curl/7.38.0"
    'Host' =>
    string(15) "www.example.com"
    'Accept' =>
    string(3) "*/*"
    'Content-Length' =>
    string(1) "4"
    'Content-Type' =>
    string(33) "application/x-www-form-urlencoded"
  }
}
```
