### ISSUE TITLE
a IDE warnning, can ignore

### ISSUE THREAD

**Issue by fr0zenrain** [php-curl-class/php-curl-class#183]
at line 840, it report a warning ,Function name must be callable. may be because $json_decoder has initialize null in line 43,thx

**Comment by zachborboa** [comment]
Hi. Which IDE are you using?

**Comment by zachborboa** [comment]
![image](https://cloud.githubusercontent.com/assets/1083146/7336830/bac7221a-ebc4-11e4-8354-5b2d6de11628.png)
