### ISSUE TITLE
Where is possibility to use proxy? Using setOpt triggers warning

### ISSUE THREAD

**Issue by xZero707** [php-curl-class/php-curl-class#196]
eg. $curl->setOpt('PROXY', '123.123.123.123:80');
Returns: 
PHP Warning:  curl_setopt() expects parameter 2 to be long, string given in /var/dev/web/libs/Curl/Curl.php on line 658

OS: Debian Jessie 8 AMD64
Server environment: XAMPP 5.6.8 / PHP 5.6.8

**Comment by zachborboa** [comment]
Hi. You'll pass the same parameters that you would pass to `curl_setopt`.

```php
$this->setOpt(CURLOPT_PROXY, '123.123.123.123:80');
```

**Comment by xZero707** [comment]
Oh, I was though if call is setOpt, CURLOPT can be excluded. Thank you, and sorry for interruption. 
Best regards!
