### ISSUE TITLE
problem with mix up of curl and http errors

### ISSUE THREAD

**Issue by lhwparis** [php-curl-class/php-curl-class#199]
I switched to your curl class and really like it Thanks :)
One problem i found was that You mix up curl and http errors. Normal behavior of curl is to respond with curl error code 0 even on http Status 404 or 500 but your class answers with the http Status Code (400, 500) in The curl error code. Do You dont think This is missleading cause these codes are http status codes and not curl error codes?

**Comment by zachborboa** [comment]
Hi. Both `curl_error_code` and `http_status_code` are available to differentiate.

**Comment by zachborboa** [comment]
`curl_error_code` has been renamed to `curlErrorCode`.
`http_status_code ` has been renamed to `httpStatusCode`.

```php
if ($curlError) {
    echo 'Curl error: ' . $curlErrorCode . "\n";
} else if ($httpError) {
    echo 'Http error: ' . $httpError . "\n";
}
```
