### ISSUE TITLE
Add ability to retry requests

### ISSUE THREAD

**Issue by zachborboa** [php-curl-class/php-curl-class#202]
Example usage:

``` php
$curl = new Curl();
$curl->setRetry(function($instance) {
    // Retry when request times out.
    return $instance->retries < 3 && $instance->error === CURLE_OPERATION_TIMEOUTED;
});
```
#200

**Comment by zachborboa** [comment]
```php
/**
 * Set Retry
 *
 * @access public
 * @param  $decider
 */
public function setRetry(callable $decider)
{
}
```

**Comment by leopucci** [comment]
I prefer the retry as a standard feature, it can be a parameter that the user can set also, but a default retry value should be included, no one needs to handle connections error if the curl class itself could deal with it.

**Comment by KTP95** [comment]
Also To me interess this too much,
Maybe is possible write it on "completeCallback" that is already existed.. ?

**Comment by zachborboa** [comment]
Retry is currently possible.

```php
$url = 'https://www.example.com/';
$data = array('foo' => 'bar');
$retries = 0;

$curl = new Curl();
$curl->error(function($instance) use (&$curl, &$retries, $url, $data) {
    if ($retries < 2) {
        $retries += 1;
        $curl->post($url, $data);
    }
});
$curl->post($url, $data);
```

**Comment by KTP95** [comment]
Very Thanks Sir, 

there a method of execute again the last curl-request ?
i want don't pass $url/$data in use(), because i have a long, very long script /12-15 curl request) and every is different - no only post or only get , there are a mix.

another question, &$curl, &$retries, $url, $data , must be global vars ?
so make if i use it in a method of a my class ? so is $this->retries, $this->curl etc.

Thanks,

**Comment by zachborboa** [comment]
@KTP95 - yes Curl::exec().

```php
$retries = 0;
$curl = new Curl();
$curl->error(function($instance) use (&$curl, &$retries) {
    if ($retries < 2) {
        $retries += 1;
        $curl->exec();
    }
});
$curl->post('http://www.example.com/', array('foo' => 'bar'));
```

**Comment by zachborboa** [comment]
@leopucci - so the logic you'd like is if `$instance->error`, automatically retry?

**Comment by leopucci** [comment]
@zachborboa 
Your approach is nice. 
The user can treat retry by himself now. 
But what if the user just send a :
$curl = new Curl();
$curl->post('https://www.example.com/', array('foo' => 'bar')); 

Then he does not have any retry feature.
retry 1 time more by default, if he does not want to retry, he need to set this explicity to 0. 
$curl = new Curl();
$curl->retry=0;
$curl->post('https://www.example.com/', array('foo' => 'bar'));

**Comment by thebeline** [comment]
I would push against making this a "standard" feature.  It "is" standard, in a way.  Figure, you need to determine what IS an "error," also, many APIs require a pause between retries, or possibly data changes (signed time-stamps, etc).  So making a "standard" retry system would be disadvantageous compared to using the framework in the way it was designed.  Two ways this can be handled:

```
// Standard Error Retry (similar to above).
$curl = new Curl();
$curl->retries = 3;
$curl->error(function($curl) {
    if ($curl->retries-- > 0) $curl->exec();
});
$curl->post('https://www.example.com/', array('foo' => 'bar'));
```

Or with own error detection:
```
$curl = new Curl();
$curl->retries = 3;
$curl->complete(function($curl) {
    if (/* some error detection using $curl */) {
        // Set Curl vars for Error state (I actually hate this, access violations, but alas).
        if ($curl->retries-- > 0) {
            $curl->exec();
        } else {
            // Throw or raise error?  Set OTHER error variables?
        }
    }
});
$curl->post('https://www.example.com/', array('foo' => 'bar'));
```

Note how neither require using `(use)`, and can be any callable (so if this is getting called in an object, it can be an object method, etc).

**Comment by zuoRambo** [comment]
The `retry` mechanism is necessary for one great HTTP Client.
As you know, Guzzle HTTP support RetryMiddleware to help developer to define their application when to retry or resend request.

```php
    Middleware::retry(
            function (
                $retries,
                RequestInterface $request,
                ResponseInterface $response = null
            ) {
                // Limit the number of retries to 2
                if ($retries <= 2 && (null === $response || $response->getStatusCode() >= 500)) {
                    return true;
                }

                return false;
            },
            function ($retries) {
                $retries++;

                return $retries * $retries * 200;
            }
        );
```

**Comment by zachborboa** [comment]
Implemented as
```php
$curl->setRetry($max_retries);
```
or
```php
$curl->setRetry(function ($instance) {
    return $instance->retries < 3;
});
```

**Comment by zachborboa** [comment]
Implemented as
```php
$multi_curl->setRetry($max_retries);
```
or
```php
$multi_curl->setRetry(function ($instance) {
    return $instance->retries < 3;
});
```
in #468

**Comment by zuoRambo** [comment]
Nice～
