### ISSUE TITLE
Add ability to set a request delay

### ISSUE THREAD

**Issue by zachborboa** [php-curl-class/php-curl-class#203]
```php
// Set the amount of time to delay before making requests.
$delay_ms = 5000;
$curl->setDelay($delay_ms);
```

**Comment by kirugan** [comment]
Can you explain why you need such feature ?

**Comment by thebeline** [comment]
I imagine @zachborboa is referring to a behavior similar to: http://stackoverflow.com/questions/9212953/curl-sleep-delay-between-requests

So if you are making multiple requests, you incur a delay between them.

If that is so, I would refer him to the answers cited there, in that, the Curl requests are synchronous, so all you would have to do is run a `foreach` loop with a `sleep` at the end to incur the desired delay.

**Comment by zachborboa** [comment]
We need a way to specify the amount of time to wait before making successive requests.

**Comment by thebeline** [comment]
We don't, however.

If you are sending requests to the same server, and need to delay between requests to prevent your script from hitting a requests rate limit, implement the loop yourself.

I know that sounds a little harsh/blunt, but there is a limit to specific one-offs for a library.

Take this for instance:  I have an API that requires that, once something fails, I make 3 requests to revoke the previous transaction.  The delay between those requests should be logarithmic.  That is to say, wait 10 seconds before sending the first request, then 100 seconds, then 1000 seconds.  Once we implement a basic delay, should we implement that as well?

It is possible to implement this basic idea by having the `complete` callback sleep for a period of time, which may be of interest to you.

**Comment by zachborboa** [comment]
Okay, we can table this. As @thebeline mentioned, rate limiting is trivial to implement.
