### ISSUE TITLE
buildURL() and custom signs in parameres

### ISSUE THREAD

**Issue by adrianwmm** [php-curl-class/php-curl-class#204]
I suggest change line in src/Curl.php
from
````php
private function buildURL($url, $data = array())
{
    return $url . (empty($data) ? '' : '?' . http_build_query($data));
}
````
to something like 
````php
private function buildURL($url, $data = array())
{
    return rtrim($url, '?') . (empty($data) ? '' : '?' . urldecode(http_build_query($data)));
}
````

Why?
When are you using custom sings like spaces or percent signs or brackets, http_build_query() function encodes them to ascii, and some web services dont recognize properly a set of parameters (e.g. mapquest - custom signs in api key, and json stringify format as one of parameters) and returns errors. 

Greetings

**Comment by zachborboa** [comment]
Hi. Do you have an example where `buildURL` fails without using `urldecode` and succeeds with using `urldecode`? I want to create a test case for this. Thank you
