### ISSUE TITLE
How to send json

### ISSUE THREAD

**Issue by neverfan** [php-curl-class/php-curl-class#209]
I try to send json, but data doesn't send on server:

$params = json_encode(array('key' => 'val'));

$headers = array(
    'Content-Type' => 'application/json',
    'Content-Length' => strlen($params)
);

$Client = new Curl();

foreach($headers as $header => $value)
{
    $Client->setHeader($header, $value);
 }

$Client->post("http://api.url.json", $params);

How correctly send json?

**Comment by zachborboa** [comment]
Hi. Here's an example:

```php
$data = json_encode(array(
    'id' => '1',
    'content' => 'Hello world!',
    'date' => date('Y-m-d H:i:s'),
));

$curl = new Curl();
$curl->setHeader('Content-Type', 'application/json');
$curl->post('https://httpbin.org/post', $data);
var_dump($curl->response->json);
```
