### ISSUE TITLE
Inconsitent version for 3.6.6 tag

### ISSUE THREAD

**Issue by chaos-drone** [php-curl-class/php-curl-class#210]
Hi,

For your 3.6.6 the version in composer.json is 3.6.5 so when requiring 3.6.6 or 3.6.5 composer says it cannot find that version.

**Comment by zachborboa** [comment]
Hi. I've contacted Packagist for a fix.

Version 3.6.6 has already been released (https://github.com/php-curl-class/php-curl-class/releases/tag/3.6.6) and the Packagist Webhooks/Services has been active yet the latest version is not available on https://packagist.org/packages/php-curl-class/php-curl-class. I've also tried forcing an update through packagist.org to no avail.

**Comment by chaos-drone** [comment]
For tag 3.6.6 the version in composer.json is 3.6.5 that's why there is problem with packagist. You should fix the version in composer so it is the same with the tag. I don't know how can you do that without releasing new version 3.6.7 e.g. :)

**Comment by zachborboa** [comment]
3.6.7 released. Thanks!
