### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by rbrzezinski** [php-curl-class/php-curl-class#211]
I've written sample script:

```php
<?php

require 'curl.php';

while (true) {
    $curl = new Curl\Curl();
    $curl = null;
    echo number_format(memory_get_usage()) . "\n";
}
```

Because of a PHP bug, there is memory leak. Solution: remove CaseInsensitiveArray reference.

Simply add `$this->headers = null;` to method `Curl::close()` and invoke before `$curl = null;`

```php
<?php

require 'curl.php';

while (true) {
    $curl = new Curl\Curl();
    $curl->close();
    $curl = null;
    echo number_format(memory_get_usage()) . "\n";
}
```

I've wasted couple of hours to figure it out :<

**Comment by thebeline** [comment]
I am guessing this is due to a circular reference?  As much as I do not like the `CaseInsensativeArray` object, I believe it is needed.  Have you tried handling the explicit destruction of the object with a `__destruct` method on the Curl object?  Would this work?

**Comment by rbrzezinski** [comment]
`Curl::close()` is called in `Curl::__destruct()` method, but it won't work. Only if it's called manualy before removing object (`$curl = null;`)

**Comment by zachborboa** [comment]
I see a memory leak when not using `$curl->close();`. By using `$curl->close()`, I don't see a memory leak.

```php
// Memory leak
for ($i = 0; $i < 5; $i++) {
    $curl = new Curl();
    $curl->close();
    echo $i . ' ' . number_format(memory_get_usage()) . "\n";
    sleep(1);
}
```

```
$ php memory_leak.php 
0 450,280
1 454,008
2 457,688
3 461,368
4 465,048
```

```php
// No memory leak
for ($i = 0; $i < 5; $i++) {
    $curl = new Curl();
    $curl->close();
    echo $i . ' ' . number_format(memory_get_usage()) . "\n";
    sleep(1);
}
```

```
$ php no_memory_leak.php 
0 447,904
1 447,984
2 447,984
3 447,984
4 447,984
```
