### ISSUE TITLE
Requests for oData 4

### ISSUE THREAD

**Issue by mitaky** [php-curl-class/php-curl-class#214]
An url like : Aros?$filter=Model eq webapi.Models.Model'User' fails as bad request, while if called through the browser, it succeeds. I have tried to both urlencode it and rawurlencode.

**Comment by zachborboa** [comment]
Hi. What's the full url for the request you're calling? Is this it?
`https://www.example.com/Aros?$filter=Model eq webapi.Models.Model`

**Comment by zachborboa** [comment]
Might be similar to #217. A possible solution:
```php
$curl = new Curl();
$url = str_replace(' ', '%20', 'https://www.example.com/Aros?$filter=Model eq webapi.Models.Model');
$curl->download($url, '/tmp/myfile.bin');
```
