### ISSUE TITLE
Download File From Url with Space ' ' not work, must be replaced by %20 - add filter

### ISSUE THREAD

**Issue by KTP95** [php-curl-class/php-curl-class#217]
Hi,
Some BAD-websites give a download url with spaces:
as
http://str9.xxxxx.me/files/5/xxxxxxxx/SonicSoul - Never Too Late.rar

The Script fail on it, receve an 404, also if i use urlencode() , the spaces are replaced with "+" and don't work, is need %20" , maybe yo can add a BuildIn fix for this.

thanks

**Comment by zachborboa** [comment]
Hi. Do you have an example url I can test with? Thanks

**Comment by KTP95** [comment]
$curl = new Curl\Curl();

$curl->download('http://ktpbestuploader.altervista.org/Please Try Download This File.rar', __DIR__.'/file.rar');

url: http://ktpbestuploader.altervista.org/Please Try Download This File.rar

return the html page downloaded of 404 page.

**Comment by zachborboa** [comment]
The url with `%20` is the correct url.

```
$ curl -I "http://ktpbestuploader.altervista.org/Please Try Download This File.rar"
HTTP/1.1 404 Not Found
Date: Thu, 13 Aug 2015 17:26:00 GMT
Server: Apache
Content-Length: 2978
Connection: close
Content-Type: text/html
```

```
$ curl -I "http://ktpbestuploader.altervista.org/Please%20Try%20Download%20This%20File.rar"
HTTP/1.1 200 OK
Date: Thu, 13 Aug 2015 17:26:18 GMT
Server: Apache
Last-Modified: Thu, 13 Aug 2015 16:40:30 GMT
ETag: "2886ccb-be-51d33fe449b80"
Accept-Ranges: bytes
Content-Length: 190
Content-Type: application/x-rar-compressed
```

Try this:
```php
$curl = new Curl();
$url = str_replace(' ', '%20', 'http://ktpbestuploader.altervista.org/Please Try Download This File.rar');
$curl->download($url, '/tmp/file.rar');
```

**Comment by KTP95** [comment]
yes, i know, this thread is only for inform you, maybe you want insert this replace (space in %20) in next release..

**Comment by jhuliano** [comment]
%20 is just the representation of a white space in percent encoding (URL Encoding). Instead of doing the str_replace right now, what you should be doing is URL encoding your string like this:

```php
curl = new Curl();
$url = 'http://ktpbestuploader.altervista.org/Please Try Download This File.rar';
$curl->download(urlencode($url), '/tmp/file.rar');
```

Right now every time you send an URL to the class you should make sure your string is properly encoded.

I think that it's a good feature that the class handles the URL encoding, also, it would be pretty damn simple to implement it. All it takes is to use the PHP urlencode function in the "buildURL" function of Curl Class.

What do you think @zachborboa?

**Comment by KTP95** [comment]
Yes, also I Think that is better integrate the fix of space in the class (and others fix if need).

horever, @jhuliano your code is bad, because urlencode encode also sign as / or : that are a part of a string so the example url will be
http%3A%2F%2Fktpbestuploader.altervista.org%2FPlease%20Try%20Download%20This%20File.rar

break url, is need use str_replace, no urlencode.

**Comment by jhuliano** [comment]
@KTP95 Oh, sorry! You are right, I did URL Encode the whole thing without even thinking about it. Please disregard it.

**Comment by zachborboa** [comment]
I've test more sites and we can't assume urls with spaces and with %20 are the same.

```
$ curl -I "http://www.example.com/privacy%20policy%202009.htm"
HTTP/1.1 200 OK
Content-Length: 66504
Content-Type: text/html
Last-Modified: Thu, 19 Jan 2012 19:17:44 GMT
Accept-Ranges: bytes
ETag: "7e5da85dfd6cc1:0"
Server: Microsoft-IIS/7.5
X-Powered-By: ASP.NET
Date: Tue, 25 Aug 2015 23:59:03 GMT
```

```
$ curl -I "http://www.example.com/privacy policy 2009.htm"
HTTP/1.1 400 Bad Request
Content-Length: 311
Content-Type: text/html; charset=us-ascii
Server: Microsoft-HTTPAPI/2.0
Date: Tue, 25 Aug 2015 23:59:33 GMT
Connection: close
```
