### ISSUE TITLE
Add Method for manually set the Response_Header->Content-Type

### ISSUE THREAD

**Issue by KTP95** [php-curl-class/php-curl-class#219]
Hi, so as title,

Some server send a page jSon or XML, but with bad response header, so' because you don't allow for force-set the right response header for content type so allow job the integrated xml / json parsen also when content type is bad?

i write the method for you

	/**
     * Set Content Type
     *
     * @access public
     * @param  $newContentType
     *
     * @return string
     */
	public function setContentType($newContentType) {
		
		$this->response_headers['Content-Type'] = $newContentType;
		return list($this->response, $this->raw_response) = $this->parseResponse($this->response_headers, $this->raw_response);
	}

Thanks

**Comment by zachborboa** [comment]
Hi. I don't think we should be modifying the response headers. If the server isn't sending the correct resonse headers, you can parse response manually.

```php
$json_response = json_decode($curl->rawResponse, false);
$xml_response = simplexml_load_string($curl->rawResponse);
```
