### ISSUE TITLE
Allow adding Multicurl handles again after start()

### ISSUE THREAD

**Issue by Savageman** [php-curl-class/php-curl-class#227]
How cool would it be?

This feature needs 3 changes (I can do a PR if you want):

* Right now it doesn't work because the `$curl_handles = $this->curls;` is outside the `do { ... } while()` loop.
* We would also need to clean-up the curl handles and have a new `$nextCurlId` property to assign each new handle (instead of the `count`).
* Finally we would need to set-up new handles (callbacks, options and before_send) when adding them while curl_multi is executing.

**Comment by zachborboa** [comment]
This does sound useful. A possibly use case would be something like this:

```php
$multi_curl = new MultiCurl();

$multi_curl->complete(function($instance) {
    $next_url = get_next_url();
    if ($next_url) {
        $multi_curl->addPost($next_url);
    }
});

$multi_curl->addPost('https://www.foo.com/');
$multi_curl->addPost('https://www.bar.com/');
$multi_curl->addPost('https://www.baz.com/');
$multi_curl->start();
```

**Comment by Savageman** [comment]
Great, I will make the PR tomorrow then.

**Comment by Savageman** [comment]
Closing here in favor of the new PR.
