### ISSUE TITLE
Curl::verbose() does not output anything

### ISSUE THREAD

**Issue by blaaat** [php-curl-class/php-curl-class#240]
Think this is because CURLINFO_HEADER_OUT is set. 
Is it an idea to duplicate the normal CURLOPT_VERBOSE functionality when verbose is enabled?

https://bugs.php.net/bug.php?id=65348

Edit: This will probably be impossible, how about making the CURLINFO_HEADER_OUT optional?

**Comment by zachborboa** [comment]
We can make `CURLINFO_HEADER_OUT` optional. However, I think the default should remain true so that request headers are included by default.

```php
// Request headers included
$curl = new Curl();
$curl->get('https://www.example.com/');
var_dump($curl->requestHeaders);
```

```php
// Verbose enabled without request headers
$curl = new Curl();
$curl->setOpt(CURLINFO_HEADER_OUT, false);
$curl->verbose();
$curl->get('https://www.example.com/');
```

**Comment by zachborboa** [comment]
Thanks for the report!
