### ISSUE TITLE
MultiCurl close() called multiple times causes PHP Warning

### ISSUE THREAD

**Issue by jaydiablo** [php-curl-class/php-curl-class#248]
In testing this library, using MultiCurl, I was calling `MultiCurl::close()` after the curl requests were done, not realizing that the library also calls `close()` on destruct.  When `close()` is called multiple times like that, PHP throws a warning that `$this->multiCurl` is not a valid resource.

Is it worth checking that `$this->multiCurl` is a resource before calling `curl_multi_close` with it?

**Comment by zachborboa** [comment]
Fixed. Thank you!
