### ISSUE TITLE
$curl->buildPostData($data) before addHandle in MultiCurl addPost function

### ISSUE THREAD

**Issue by adamnguyenit** [php-curl-class/php-curl-class#249]
In the addPost function of MultiCurl class, your code is just call buildPostData before addHandle. It makes a issue: headers do not set before build data. But in buildPostData you have "check headers for encode the request data", ex: if headers contain "Content-Type: application/json", you will encode the data to json string in buildPostData.
Please, take a look and fix it as soon as possible.
Sorry for my English. Thank you.

**Comment by zachborboa** [comment]
Hi. If you want your data json encoded when it POSTs, set the content-type to application/json.

```php
$multi_curl = new MultiCurl();
$multi_curl->setHeader('Content-Type', 'application/json');
$multi_curl->addPost($data);
```
