### ISSUE TITLE
Add examples

### ISSUE THREAD

**Issue by zborboa-g** [php-curl-class/php-curl-class#25]

**Comment by zachborboa** [comment]
Google Spreadsheet - Update a range
https://developers.google.com/sheets/reference/rest/v4/spreadsheets.values/update

**Comment by zachborboa** [comment]
[Many examples](https://github.com/php-curl-class/php-curl-class/tree/master/examples) are available. Please [file a ticket](https://github.com/php-curl-class/php-curl-class/issues/new) if you didn't find an example that fits your use case.
