### ISSUE TITLE
How to send "--data"?...

### ISSUE THREAD

**Issue by circleride** [php-curl-class/php-curl-class#252]
How to send this **--data '{"value":"off"}'**  ?

curl -X PATCH "https://api.cloudflare.com/client/v4/zones/023e105f4ecef8ad9ca31a8372d0c353/settings/development_mode" \
-H "X-Auth-Email: user@example.com" \
-H "X-Auth-Key: c2547eb745079dac9320b638f5e225cf483cc5cfdda41" \
-H "Content-Type: application/json" \
--data '{"value":"off"}'

Sorry for my bad english :-1:  :(

**Comment by circleride** [comment]
Example: 
https://api.cloudflare.com/#zone-settings-change-development-mode-setting

**Comment by zachborboa** [comment]
```php
$curl = new Curl();
$curl->setHeader('X-Auth-Email', 'user@example.com');
$curl->setHeader('X-Auth-Key', 'c2547eb745079dac9320b638f5e225cf483cc5cfdda41');
$curl->setHeader('Content-Type', 'application/json');
$curl->patch('https://api.cloudflare.com/client/v4/zones/023e105f4ecef8ad9ca31a8372d0c353/settings/development_mode', array(
    'value' => 'off',
));
```

**Comment by circleride** [comment]
Thanks!

i am trying whit DELETE:

curl -X DELETE "https://api.cloudflare.com/client/v4/zones/023e105f4ecef8ad9ca31a8372d0c353/purge_cache" \
-H "X-Auth-Email: user@example.com" \
-H "X-Auth-Key: c2547eb745079dac9320b638f5e225cf483cc5cfdda41" \
-H "Content-Type: application/json" \
--data '{"purge_everything":true}'

But....

Error: 400: HTTP/1.1 400 Bad Request

**Comment by zachborboa** [comment]
```php
$curl = new Curl();
$curl->setHeader('X-Auth-Email', 'user@example.com');
$curl->setHeader('X-Auth-Key', 'c2547eb745079dac9320b638f5e225cf483cc5cfdda41');
$curl->setHeader('Content-Type', 'application/json');
$curl->delete('https://api.cloudflare.com/client/v4/zones/023e105f4ecef8ad9ca31a8372d0c353/purge_cache', array(
    'purge_everything' => true,
));
```
