### ISSUE TITLE
Remove the "vendor" symlink from the "examples" folder

### ISSUE THREAD

**Issue by cedx** [php-curl-class/php-curl-class#279]
I know that this symbolic link is very useful to test the examples, but it can be very annoying...

We have a build phase that fetch/update the Composer dependencies and deploy them on a remote server. The problem is that during this phase an output folder is created, and the dependencies are copied into it.

The symbolic link breaks our build phase as it points to an invalid location. Each time the phase is run, we have this error:

```
cp: /[...]/files/vendor/php-curl-class/php-curl-class/examples/vendor: No such file or directory
```

Note: our "vendor" directory is not located at the project root, we use a custom location in our `composer.json`.

**Comment by zachborboa** [comment]
Hi Cédric. Can you simply unlink the vendor symlink?
```bash
$ unlink php-curl-class/examples/vendor
```

**Comment by cedx** [comment]
Yes of course :) Thanks, so easy after all.

**Comment by roydekleijn** [comment]
We also face this problem, I feel this is not a good practice..

**Comment by Linuxhombre** [comment]
I have created a version that hops every parameter posted and can also
Traverse a file, using the headers as post parameters for the end PHP cURL
URL. Let me know if interested.

**Comment by zachborboa** [comment]
Proposing to remove [the symlink](https://github.com/php-curl-class/php-curl-class/blob/master/examples/vendor), that should solve things, right?

**Comment by zachborboa** [comment]
@Linuxhombre Yes interested. Thank you
