### ISSUE TITLE
Seamlessly decode json

### ISSUE THREAD

**Issue by zborboa-g** [php-curl-class/php-curl-class#28]
Decode json when content-type is `application/json`.

**Comment by hi2u** [comment]
Maybe I'm a bit confused about something here, but I'm wondering why this class sometimes (when the response is XML or JSON) parses and overwrites $Curl->response with a different data type automatically by default.

It seems like a pretty dangerous default to me, and has tripped me up a few times when my code expects the class to be consistent ($Curl->response is a regular string of data - as it is for all other Content-Type responses).

I know I can instead access $Curl->rawResponse to get a consistent data type (a string), but this seems backwards to me.  Surely the $Curl->response should stay consistent (the actual response with no tampering), and if people want a parsed array/object, they get these data types from a method like $Curl->getParsedResponse() 

Is there a way to turn it off?  It's also unnecessary resource usage for people that have no need for it.

Also I think it would be helpful to put a note on the main README.md to warn new users about this unexpected inconsistent behaviour.

Anyway, thanks for the work on this, I appreciate it.

**Comment by zachborboa** [comment]
@hi2u - The response has historically been automatically decoded for known content types including json and xml. You can see how this is handled in `parseResponse`. There isn't any way to turn this off.

https://github.com/php-curl-class/php-curl-class/blob/master/src/Curl/Curl.php#L949
