### ISSUE TITLE
Can't add request Cookies

### ISSUE THREAD

**Issue by Fohlen** [php-curl-class/php-curl-class#280]
There is no way to add request cookies.
When I use 
```
		$curl->setHeader('Cookie: 79zarV', (string)$curl->getCookie('79varV'));		
```
it will be plainly ignored. Injecting manually by using 
```
curl_setopt($curl->curl, CURLOPT_HTTPHEADER, array('Cookie: 79zarV='.$cookie);
```
Is beeing ignored as well!
How can I fix this?

**Comment by zborboa-google** [comment]
Use `setCookie()`?

**Comment by Fohlen** [comment]
Funnily, I can retrieve the cookie with ```getCookie()``` but setting it again with ```setCookie()``` or leaving it as-is does not send it in the header

**Comment by zachborboa** [comment]
Here's an example:
```php
$curl = new Curl();
$curl->setCookie('foo', 'bar');
$curl->get('https://httpbin.org/cookies');
var_dump($curl->response->cookies->foo === 'bar');
```

**Comment by Fohlen** [comment]
Really, that doesn't work, well, try it yourself
```
		$curl = new Curl();
		$curl->setCookie('79varZ', ('9e846d3d6b41ab71e8d6ba6cfff521ad:6:0'));
		$file = $curl->get('https://www31.adrive.com/public/79zarV.html');
		var_dump($curl->response->cookie); // this will be empty
		$curl->close();
```
@zachborboa you can obtain a valid ```79varZ``` cookie from https://nightly.inexor.org
I have this use case since their API is actually a pain in the ass and explicitly wants to prohibits external usage, but that doesn't mean I stop there :+1:

**Comment by zachborboa** [comment]
You'll want to use `getResponseCookie()` to get the cookie from the response headers.
