### ISSUE TITLE
Maybe add a variable "lastRedirect" in curl class for a request have multi redirects?

### ISSUE THREAD

**Issue by feeho** [php-curl-class/php-curl-class#287]
https://secure.php.net/search.php?show=quickref&pattern=curl_init
Follow is a test request and response headers here and I wanna get the last Location value.

Same result I use: curl_getinfo($curl->curl, CURLINFO_EFFECTIVE_URL);

    [rawResponseHeaders] => HTTP/1.1 302 Found
Server: nginx/1.6.2
Date: Mon, 18 Jan 2016 14:07:54 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 20
Connection: keep-alive
X-Powered-By: PHP/5.6.13-0+deb8u1
Content-language: en
X-Frame-Options: SAMEORIGIN
Set-Cookie: COUNTRY=NA%2C60.255.1.211; expires=Mon, 25-Jan-2016 14:07:54 GMT; Max-Age=604800; path=/; domain=.php.net
Location: https://php.net/manual-lookup.php?pattern=curl_init&scope=quickref
Content-Encoding: gzip
Vary: Accept-Encoding
Strict-Transport-Security: max-age=31536000

HTTP/1.1 301 Moved Permanently
Server: nginx/1.6.2
Date: Mon, 18 Jan 2016 14:07:57 GMT
Content-Type: text/html
Content-Length: 184
Connection: keep-alive
Location: https://secure.php.net/manual-lookup.php?pattern=curl_init&scope=quickref

HTTP/1.1 302 Found
Server: nginx/1.6.2
Date: Mon, 18 Jan 2016 14:07:58 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 20
Connection: keep-alive
X-Powered-By: PHP/5.6.13-0+deb8u1
Content-language: en
X-Frame-Options: SAMEORIGIN
Set-Cookie: COUNTRY=NA%2C60.255.1.211; expires=Mon, 25-Jan-2016 14:07:58 GMT; Max-Age=604800; path=/; domain=.php.net
Location: https://php.net/manual/en/function.curl-init.php
Content-Encoding: gzip
Vary: Accept-Encoding
Strict-Transport-Security: max-age=31536000

HTTP/1.1 301 Moved Permanently
Server: nginx/1.6.2
Date: Mon, 18 Jan 2016 14:07:58 GMT
Content-Type: text/html
Content-Length: 184
Connection: keep-alive
Location: https://secure.php.net/manual/en/function.curl-init.php

HTTP/1.1 200 OK
Server: nginx/1.6.2
Date: Mon, 18 Jan 2016 14:07:58 GMT
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
X-Powered-By: PHP/5.6.13-0+deb8u1
Content-language: en
X-Frame-Options: SAMEORIGIN
Set-Cookie: LAST_LANG=en; expires=Tue, 17-Jan-2017 14:07:58 GMT; Max-Age=31536000; path=/; domain=.php.net
Set-Cookie: COUNTRY=NA%2C60.255.1.211; expires=Mon, 25-Jan-2016 14:07:58 GMT; Max-Age=604800; path=/; domain=.php.net
Link: <http://php.net/curl-init>; rel=shorturl
Last-Modified: Mon, 18 Jan 2016 05:07:54 GMT
Content-Encoding: gzip
Vary: Accept-Encoding
Strict-Transport-Security: max-age=31536000

**Comment by zachborboa** [comment]
Hi. Why can't `curl_getinfo($curl->curl, CURLINFO_EFFECTIVE_URL);` be used?

**Comment by feeho** [comment]
@zachborboa 
Same result fI use: curl_getinfo($curl->curl, CURLINFO_EFFECTIVE_URL);
Yes,I used it.But add a varaiable is better?

**Comment by zachborboa** [comment]
Added `$curl->effectiveUrl`. Thanks

**Comment by Linuxhombre** [comment]
Perfect.
