### ISSUE TITLE
Get Request grab headers and ignore response

### ISSUE THREAD

**Issue by txt3rob** [php-curl-class/php-curl-class#289]
Hi,

Could you assist me a bit i want to do a get request to a url which will return a video stream but i dont want curl to grab the response i only want to return the headers is this possible?

**Comment by txt3rob** [comment]
set a timeout and can return what is required.

**Comment by txt3rob** [comment]
how would i echo out the content-type from the headers? rawResponse is a string.

is it possible to echo out from the response object?

**Comment by zachborboa** [comment]
Hi. You may want to look into using a HEAD request.

```bash
curl --head "https://www.example.com/path/to/video.avi"
```

```php
$curl->head('https://www.example.com/path/to/video.avi');
```
