### ISSUE TITLE
XML issue and solution

### ISSUE THREAD

**Issue by dvLden** [php-curl-class/php-curl-class#295]
I started a project yesterday that depends on your CURL class and I noticed that there's a problem with response. Before your class, I used another one that always returned "string" as response, no matter what Content-Type it actually is.

So after converting to your class, I noticed that my project is failing everywhere I used `json_decode()` or `new SimpleXMLElement`, as it returns the properly formatted object already, except that it fails for XML in some situations.

I tracked down your method `parseResponse` and noticed that `simplexml_load_string` is not good for every XML situation where it may contain _nested XML objects_ (if I may call it that way). 

So I just made slight modification from this:
`$xml_obj = @simplexml_load_string($response);`

Response before:
<img width="506" alt="screen shot 2016-01-29 at 20 20 49" src="https://cloud.githubusercontent.com/assets/3460368/12685658/f03cc76a-c6c5-11e5-8e98-58128a69024a.png">

To this:
`$xml_obj = @simplexml_load_string($response, 'SimpleXMLElement', LIBXML_NOCDATA);`

Response after:
<img width="742" alt="screen shot 2016-01-29 at 20 21 19" src="https://cloud.githubusercontent.com/assets/3460368/12685662/f87647c6-c6c5-11e5-8e95-375e375b6f8b.png">

And now it works perfectly... Just a tip, hopefully it will get updated officially after you read this.
I am not familiar with contributions - where I make changes and you add to the master branch, so I'll try to avoid that for now and just open the issue as it's simpler this way.

**Comment by Linuxhombre** [comment]
This should absolutely be included

**Comment by zachborboa** [comment]
Hi. Casting the variable to a string should work.

```php
$response = <<<EOF
<rss>
<items>
    <item>
        <link><![CDATA[https://www.example.com/]]></link>
    </item>
    <item>
        <link><![CDATA[https://www.another-example.net/]]></link>
    </item>
</items>
</rss>
EOF;

$xml_obj = @simplexml_load_string($response);
echo $xml_obj->items->item['0']->link . "\n"; // https://www.example.com/
echo $xml_obj->items->item['1']->link . "\n"; // https://www.another-example.net/
```

**Comment by zachborboa** [comment]
You can now use a custom xml decoder.

```php
$curl = new Curl();
$curl->setXmlDecoder(function($response) {
    return simplexml_load_string($response, 'SimpleXMLElement', LIBXML_NOCDATA);
});
```

**Comment by wangyouworld** [comment]
`
[i.txt](https://github.com/php-curl-class/php-curl-class/files/3337473/i.txt)
`

Change the i.txt file to i.xml
