### ISSUE TITLE
Testability | Missing getter setter methods

### ISSUE THREAD

**Issue by B4rb4ross4** [php-curl-class/php-curl-class#303]
Hi,

I wanted to use your class in a project, because it provides a convenient object oriented wrapper around the php curl functions, which would make unit testing my code easier. At least i thought so. Now that I started to get my test coverage up, I found the problem, that accessing the response etc. is just done by accessing the attributes on the curl object directly. I wanted to mock out your class from my code to test my class. My function looks like this:

``` php
public function request()
  {
    /** @var \Curl\Curl $curl */
    $curl = $this->handler;

    $curl->setOpt(CURLOPT_CUSTOMREQUEST, 'POST');
    $curl->setOpt(CURLOPT_POST, true);
    $curl->setOpt(CURLOPT_HTTPHEADER,     array("Content-Type: application/json","Content-Length: " . strlen($this->request)));
    $curl->setOpt(CURLOPT_POSTFIELDS, $this->request);
    $curl->setURL($this->url);
    $curl->exec();

    $this->response = $curl->rawResponse;
  }
```

Because there is no getter function for the response I'm not able to mock out your curl class. Could you provide a fix for that issue or should I create a pull request for you (since its just generate getter/setters in the IDE)?

**Comment by zachborboa** [comment]
Hi. A pull request would be great. Are you looking for something like this?

```php
public function getResponse() {
    return $this->response;
}
```

**Comment by B4rb4ross4** [comment]
Exactly

**Comment by zachborboa** [comment]
Hi, I'm revisiting this issue. If you'd like to test things you can pull in #529. Thank you
