### ISSUE TITLE
curl getResponseCookies says undifined method

### ISSUE THREAD

**Issue by hayesrobin** [php-curl-class/php-curl-class#305]
When I was tried to get all response cookies listed it says this error --> 
```
PHP Fatal error:  Call to undefined method Curl\Curl::getResponseCookies() in 
```
my code is --> 
```
require 'vendor/autoload.php';

use \Curl\Curl;

$curl = new Curl();
$curl->setOpt(CURLOPT_SSL_VERIFYPEER, false);
$curl->setOpt(CURLOPT_FOLLOWLOCATION, true);
$curl->get('https://example.com');

if ($curl->error) {
    echo 'Error: ' . $curl->errorCode . ': ' . $curl->errorMessage;
} else {
    echo $curl->response;
}

var_dump($curl->getResponseCookies());
```
But $curl->getCookie() is working good

**Comment by zachborboa** [comment]
Hi. Please pull in the latest version (4.11.0) which includes `getResponseCookies`. Thank you

**Comment by ruslanbakanov** [comment]
"Fatal error: Call to undefined method Curl\Curl::getResponseCookies()"

Hello!
The same situation
And i just clone repository and have the latest version :)

**Comment by luisfavila** [comment]
I don't thing there's a `getResponseCookies` but a `getResponseCookie` only. I was searching for this too @ruslanbakanov

**Comment by zachborboa** [comment]
@hayesrobin @ruslanbakanov @luisfavila my mistake. There's no `getResponseCookies()` method. You can simply use `$curl->responseCookies`.
