### ISSUE TITLE
Pass ID to MultiCurl

### ISSUE THREAD

**Issue by sojic** [php-curl-class/php-curl-class#309]
It would be nice if you add feature to pass ID of "url", ex:

```
foreach ($collection as $item) {
	$curl->addGet($item->id, $item->url);
}
```

and return it in success callback:

```
$curl->success(function($instance) {
	$this->info('call to "' . $instance->id . '" was successful.' . "\n");
});
```

**Comment by Linuxhombre** [comment]
Super easy to pop in return codes etc after the curl execution.  Also, I actually add an ID property to the multiCurl() element myself, based on the encryption at-hand, values passed in, etc.

**Comment by zachborboa** [comment]
@sojic When queuing a new request with `MultiCurl`, a unique internal id is set. In the callback, `$instance->id` is available for use.

```php
$curl->id = $this->nextCurlId++;
```
https://github.com/php-curl-class/php-curl-class/blob/master/src/Curl/MultiCurl.php#L586

**Comment by zachborboa** [comment]
MultiCurl contains an id.
```php
$multi_curl = new MultiCurl();
$multi_curl->complete(function($instance) {
    var_dump($instance->id);
});
$multi_curl->addGet('https://httpbin.org/get');
$multi_curl->start();
```
