### ISSUE TITLE
Php running out of allocated memory

### ISSUE THREAD

**Issue by dlstadther** [php-curl-class/php-curl-class#324]
After 12 executions of Curl->get(...), I run out of allocated memory. The line that throws the error is Curl.php line 731 (`$json_obj = json_decode($response, false);`)

```php
    /**
     * Set Default JSON Decoder
     *
     * @access public
     */
    public function setDefaultJsonDecoder()
    {
        $this->jsonDecoder = function($response) {
            $json_obj = json_decode($response, false);
            if (!($json_obj === null)) {
                $response = $json_obj;
            }
            return $response;
        };
    }
```

I can increase the `memory_limit` in `php.ini` to greater than 128M, but regardless of how large I make it this error occurs prior to reaching 100,000 records.

I have to curl for a few 100,000 records (~400,000), but have to do so in chunks of 1,000. Basically have the following:

```php
$fp = fopen($path_to_file, "w");
while(True) {
   $curl = new Curl();
   $curl->setBasicAuthentication($username, $password);
   $curl->get($url);

   //check httpStatusCode for rate limiting purposes
   //possibly sleep for some amount of time then continue with the next iteration of this loop

   $response = $curl->response;
   foreach($response->a as $a) {
       // keep only the attributes I want
       fputcsv($fp, array('id' => $a->id, 'name' => $a->name));
   }

   //get url for next page of results
   if (property_exists($response, 'next-page') {
       $url = $response->{'next-page'};
   } else {
       break;
   }
}
fclose($fp);
```

I have tried to `unset($curl);` after I finish with it after each iteration of the `while(True)...`, but this has no effect.

I'm suspicious that there are some variables within this Curl class that are not getting cleaned up after each reoccurring call.

_Worth noting, Php is **not** my primary language. I'm used to python handling garbage collection for me. Basically, I'm kind of lost when it comes to debugging this project._

**Comment by thebeline** [comment]
Are you using PHP7?  

It may be worth calling `$curl->close()`, as even though the object is overwritten, it is not destructed (see #310).

If you are using PHP 7, then you may be running into a known memory leak.  Try `close()` first.

**Comment by dlstadther** [comment]
I'm using Php Version 5.5.31.

I'll try using `$curl->close()`

**Comment by dlstadther** [comment]
`$curl->close();` solved the issue! Thanks @thebeline !

Correct code below:

```python
$fp = fopen($path_to_file, "w");
while(True) {
   $curl = new Curl();
   $curl->setBasicAuthentication($username, $password);
   $curl->get($url);

   //check httpStatusCode for rate limiting purposes
   //possibly sleep for some amount of time then continue with the next iteration of this loop

   $response = $curl->response;
   foreach($response->a as $a) {
       // keep only the attributes I want
       fputcsv($fp, array('id' => $a->id, 'name' => $a->name));
   }

   //get url for next page of results
   if (property_exists($response, 'next-page') {
       $url = $response->{'next-page'};
   } else {
       break;
   }
   $curl->close();
}
fclose($fp);
```
