### ISSUE TITLE
required php 5.5.11

### ISSUE THREAD

**Issue by Valtas** [php-curl-class/php-curl-class#326]
Fatal error: Due to technical limitations of PHP <= 5.5.11 and HHVM, it is not possible to perform a post-redirect-get request using a php-curl-class Curl object that has already been used to perform other types of requests. Either use a new php-curl-class Curl object or upgrade your PHP engine. in /var/www/avito/mrtin/data/www/core/dop_parser/parsrent/vendor/php-curl-class/php-curl-class/src/Curl/Curl.php on line 546

**Comment by zachborboa** [comment]
Hi. This is a known and unfixable issue that affects PHP <= 5.5.11. Please use a new curl object for each request if you're unable to update the version of php you are using.
