### ISSUE TITLE
Send POST STRING begins with @

### ISSUE THREAD

**Issue by KTP95** [php-curl-class/php-curl-class#330]
Dear, as a title

$curl = new Curl();
$curl->post('http://www.example.com/login/', array(
    'username' => 'myusername',
    'password' => '@MyPasswordStartWith@',
));

This is do error because is try interpreter as @File 

Please fix, maybe give possibility to disable @path/file syntax, and use only new Standard Curl File

**Comment by zachborboa** [comment]
Hi. I'm unable to reproduce. The library checks that the file referenced exists[1]. Make sure you've updated your composer dependencies.

```php
// test.php
<?php
require __DIR__ . '/vendor/autoload.php';

use \Curl\Curl;

$curl = new Curl();
$curl->post('http://127.0.0.1:8001/', array(
    'username' => 'myusername',
    'password' => '@MyPasswordStartWith@',
));
```

```php
// server.php
<?php
error_log($_POST['password'], 4);
```

````
$ php -S 127.0.0.1:8001 server.php 
PHP 7.0.2 Development Server started at Thu Jun  2 01:38:24 2016
Listening on http://127.0.0.1:8001
Document root is /Users/user
Press Ctrl-C to quit.
[Thu Jun  2 01:38:28 2016] @MyPasswordStartWith@
[Thu Jun  2 01:38:28 2016] 1
```

[1] https://github.com/php-curl-class/php-curl-class/blob/master/src/Curl/Curl.php#L154
