### ISSUE TITLE
Suggest build In function for setup proxy

### ISSUE THREAD

**Issue by KTP95** [php-curl-class/php-curl-class#331]
I suggest a build-in function for setup (and unset) proxy,
so like this, example
//All parameters

//CURLOPT_HTTPPROXYTUNNEL = active/deactive + setup proxy

$curl->setProxy($CURLOPT_HTTPPROXYTUNNEL , $CURLOPT_PROXY, $CURLOPT_PROXYUSERPWD, $CURLOPT_PROXYAUTH, $CURLOPT_PROXYPORT, $CURLOPT_PROXYTYPE);

//after setup proxy, turn it off, but store in the memory
$curl->setProxy($CURLOPT_HTTPPROXYTUNNEL = false);

// And completly deactive + unset proxy
$curl->unsetProxy();

maybe with support advanced syntax so like

$curl->setProxy($PROXY = 'user:password@host:port', $CURLOPT_PROXYTYPE);

Or so like...a build in one-line function for activate/handle proxy setup

what do you think about this proposal?

**Comment by KTP95** [comment]
ps. a question, what is difference from CURLOPT_PROXYAUTH and  CURLOPT_PROXYUSERPWD ..i not understand this...

**Comment by thebeline** [comment]
I don;t use a proxy, so I am not sure, but this looks interesting.  Write it up and submit a pull request, would be very interested in seeing what that looks like...

**Comment by KTP95** [comment]
Sincerally also I not user never proxy , but try build this functions

**Comment by Linuxhombre** [comment]
Yes, you can add a supplemental function easily (there's a lot of 
options out there too to, for example, randomly rotate through proxies 
along with user agents, so forth).

**Comment by zachborboa** [comment]
Proxy can now be set like this

```php
$curl = new Curl();
$curl->setProxy('proxy.example.com', '1080', 'username', 'password');
$curl->setProxyTunnel();
$curl->get('https://httpbin.org/get');
var_dump($curl->response);
```
