### ISSUE TITLE
Feature: set a maximum size limit to curl downloads

### ISSUE THREAD

**Issue by Bogdaan** [php-curl-class/php-curl-class#332]
Hi, i have some issues with `download` function (large files download + memory limit).
May be a download limit (inside class) would be useful?

Raw curl:
```
// We need progress updates to break the connection mid-way
curl_setopt($cURL_Handle, CURLOPT_BUFFERSIZE, 128); // more progress info
curl_setopt($cURL_Handle, CURLOPT_NOPROGRESS, false);
curl_setopt($cURL_Handle, CURLOPT_PROGRESSFUNCTION, function(
    $DownloadSize, $Downloaded, $UploadSize, $Uploaded
){
    // If $Downloaded exceeds 1KB, returning non-0 breaks the connection!
    return ($Downloaded > (1 * 1024)) ? 1 : 0;
});
```

Class function prototype:
```
$curl->limitDownload(1024); // 1KB
```

Source: http://stackoverflow.com/questions/17641073/how-to-set-a-maximum-size-limit-to-php-curl-downloads

**Comment by zachborboa** [comment]
Thank you for the suggestion. Not sure if a specific function like this needs to be added to the library since it can be added fairly easily using `Curl::setOpt`. I would also rename it to something like `Curl::setMaxDownloadSize` or `Curl::setMaxDownloadSizeBytes`.

**Comment by Bogdaan** [comment]
@zachborboa 
Agree with you. But `download` method "without limit" is **security hole** in the system.
You can generate terabyte file on remote (by user-agent or ip).

Actually this issue was created due to the fact that someone in my project use this hole.

**Comment by zachborboa** [comment]
Accepting this as `curl` includes a `--max-filesize <bytes>` option:

    Specify  the maximum size (in bytes) of a file to download. If the file requested is larger than this value, the
    transfer will not start and curl will return with exit code 63.

    NOTE: The file size is not always known prior to download, and for such files this option has no effect even  if
    the file transfer ends up being larger than this given limit. This concerns both FTP and HTTP transfers.

**Comment by zachborboa** [comment]
Thanks!

**Comment by dotancohen-healthpro** [comment]
I'm two years too late to help, but the suggested solution `--max-filesize` will not help against an attacker. If the attacker does not set a `Content-Length` header then curl will happily download the bytes until your hard drive is full.

**Comment by dotancohen** [comment]
I'm two years too late to help, but the suggested solution --max-filesize will not help against an attacker. If the attacker does not set a Content-Length header then curl will happily download the bytes until your hard drive is full.

**Comment by zachborboa** [comment]
@dotancohen While `curl`'s `--max-filesize` does not prevent downloading a file larger than the specified size, `Curl::setMaxFilesize()` does abort the transfer when the number of downloaded bytes exceeds the specified number of maximum bytes.

**Comment by dotancohen** [comment]
@zachborboa 
I see. The method is was a bit misleading to those familiar with `curl`, but I've looked at the source and I see that it is overwriting the default `CURLOPT_PROGRESSFUNCTION` and using the return value to abort if necessary. Very clever, I did not realize this was possible.

I apologize for the noise!
