### ISSUE TITLE
Chainig call support

### ISSUE THREAD

**Issue by undercloud** [php-curl-class/php-curl-class#335]
Add chaining like this? It's cool!
```PHP
curl = new Curl();
$curl->setBasicAuthentication('username', 'password')
  ->setUserAgent('')
  ->setReferrer('')
  ->setHeader('X-Requested-With', 'XMLHttpRequest')
  ->setCookie('key', 'value')
  ->get('http://www.example.com/')
```

**Comment by Naresh206** [comment]
Hi,
 I think that is wrong way.
is it working

**Comment by zachborboa** [comment]
Thanks for the suggestion. Use of method chaining is a bit controversial. I'm `-1` on adding this.

> Optimize for the reading case. **NEVER** optimize to make code faster to write. After all, you'll write it once, but read it over and over and over.

https://www.reddit.com/r/PHP/comments/251699/method_chaining_yes_or_no_only_for_setters/chcn3zc
