### ISSUE TITLE
Main Website SSL Certificate Expired.

### ISSUE THREAD

**Issue by djeraseit** [php-curl-class/php-curl-class#336]
Main website SSL certficate expired. They are cheap at SSLs.com

**Comment by WyriHaximus** [comment]
They're free at letsencrypt

**Comment by zachborboa** [comment]
Fixed. Thanks

![image](https://cloud.githubusercontent.com/assets/1083146/18409859/1a76de98-7707-11e6-89c7-7e8efedf8112.png)
