### ISSUE TITLE
What's the point to new Curl($base_url) if it's not used?

### ISSUE THREAD

**Issue by patricknelson** [php-curl-class/php-curl-class#338]
What's the point to accepting a base URL in the constructor if it's never used? Why can't I just do this?

```php
$curl = new \Curl\Curl($endpoint);
$response = $curl->get('/request-uri', [
	'someParam' => $myParamValue
]);
```

I noticed that the URL is always overwritten if/when I ever do a `->get()` since that method accepts a URL and always calls `->setURL()` which then overrides `->base_url` property. Why ever even provide a base URL? I know Guzzle handles this sort of syntax.

**Comment by zachborboa** [comment]
Hi. Base url is meant to be set for all the subsequent calls with only the data being passed to the follow. This is how it would be rewritten:
```php
$curl = new \Curl\Curl($endpoint . '/request-uri');
$response = $curl->get([
    'someParam' => $myParamValue
]);
```

**Comment by zachborboa** [comment]
Thanks for the suggest. Ticket #347 created.
