### ISSUE TITLE
Possibility to multicurl retry?

### ISSUE THREAD

**Issue by sergiodebcn** [php-curl-class/php-curl-class#339]
It is possible to retry multicurl calls? I one of the instances fails? Only retry the specific url that fails?
Thanks

**Comment by zachborboa** [comment]
It's not currently possible to retry multicurl calls. Maybe either of these could be implemented:

```php
$multi_curl->setRetry(function($instance) {
    return $instance->runCount < 3;
});
```

or

```php
$multi_curl->error(function($instance) {
    if ($instance->runCount < 3) {
        $instance->run();
    }
});
```
This issue is similar to <https://github.com/php-curl-class/php-curl-class/issues/202>.

**Comment by cgurubest** [comment]
PHP Fatal error:  Call to undefined method Curl\Curl::run()

**Comment by zachborboa** [comment]
Implemented as
```php
$curl->setRetry($max_retries);
```
or
```php
$curl->setRetry(function ($instance) {
    return $instance->retries < 3;
});
```
in #468

**Comment by zachborboa** [comment]
Implemented as
```php
$multi_curl->setRetry($max_retries);
```
or
```php
$multi_curl->setRetry(function ($instance) {
    return $instance->retries < 3;
});
```
in #468
