### ISSUE TITLE
Documented return types don't match code

### ISSUE THREAD

**Issue by 56quarters** [php-curl-class/php-curl-class#340]
The comments for `Curl::exec` and `Curl::get` indicate that they will always return `string`. However, when the response has a `Content-Type` header of `application/json`, it will be decoded by default into a `stdClass`.

It seems that the docs for these methods should indicate that the return type changes based on the `Content-Type` of the response.

**Comment by zachborboa** [comment]
Thanks for the suggestion.

**Comment by 56quarters** [comment]
Thanks!
