### ISSUE TITLE
Allow requests using relative url when a base url has been set

### ISSUE THREAD

**Issue by zachborboa** [php-curl-class/php-curl-class#347]
Make the following possible:

``` php
$curl = new \Curl('https://www.example.com/api/');

// https://www.example.com/api/test
$response = $curl->get('test', [
    'key' => 'value',
]);

// https://www.example.com/root
$response = $curl->get('/root', [
    'key' => 'value',
]);
```

**Comment by patricknelson** [comment]
What was the point of closing my original ticket #338? You'd simply setup a PR to implement the change/bug pointed out in the original ticket :smile:

**Comment by zachborboa** [comment]
Implements using an absolute or relative URL
https://developer.mozilla.org/en-US/docs/Web/API/URL/URL

**Comment by zachborboa** [comment]
Possibly useful for test cases.
http://w3c-test.org/url/url-constructor.html
