### ISSUE TITLE
Update packagist

### ISSUE THREAD

**Issue by Oxicode** [php-curl-class/php-curl-class#350]
What is the expected behavior?
Donwload last versión

What is the actual behavior?
Donwload versión at 2016-03-09 00:50 UTC

What steps will reproduce the problem?
https://packagist.org/packages/php-curl-class/php-curl-class

**Comment by Oxicode** [comment]
Cc @zachborboa

**Comment by zachborboa** [comment]
4.12.0 has been released. Thanks
