### ISSUE TITLE
buildPostData() does not work with the following json

### ISSUE THREAD

**Issue by funkytaco** [php-curl-class/php-curl-class#351]
What is the expected behavior?

buildPostData() does not work with the following json:

```
$not_encoded = '{
            "action": "EventsRouter",
            "method": "query",
            "data": [{
            "limit": 2000,
            "params": {
            "eventState": [0],
            "severity": [5]
            }
            }],
            "tid": 1
            }';
```

What is the actual behavior?

I made sure to set a content header for json.
The regular curl way works:
              `CURLOPT_POSTFIELDS => json_encode($not_encoded),`
This doesn't:
```
$this->setHeader('Content-Type', 'application/json');
            $this->buildPostData(json_encode($not_encoded));
            $this->setBasicAuthentication($this->username, $this->password);
```

**Comment by zachborboa** [comment]
Hi. Can you give an example of what you are trying to accomplish? Also, buildPostData should not typically be used directly. Here's an example of how to POST json data. https://github.com/php-curl-class/php-curl-class/blob/master/examples/post_json.php

**Comment by funkytaco** [comment]
Oh, I see. Thanks, it works now.
The `$curl->post()` example confused me. I should have read the docs a little more closely.
