### ISSUE TITLE
default json decoder has 2nd parameter hardcoded to false

### ISSUE THREAD

**Issue by domnulnopcea** [php-curl-class/php-curl-class#357]
it would be nice to be able to set this parameter dynamically.

if I want an array back instead of stdClass there is no direct way

thanks

**Comment by zachborboa** [comment]
Thanks for the suggestion!

**Comment by domnulnopcea** [comment]
great! thanks! when are you going to release a new composer package with this feature included? we are depending on it

**Comment by zachborboa** [comment]
released!

**Comment by nesttle** [comment]
How can I set 'TRUE'? I'm using @dev release.

Thanks!

**Comment by zachborboa** [comment]
@nesttle 

$curl = new Curl();
$curl->setDefaultJsonDecoder($assoc, $depth, $options);
