### ISSUE TITLE
CURLFile is ignored

### ISSUE THREAD

**Issue by julianrutten** [php-curl-class/php-curl-class#361]
What is the expected behavior?
CURLFile is attached to the request

What is the actual behavior?
CURLFile is ignored

What steps will reproduce the problem?
Send a CURLFile in a multidimensional array. See ```src\Curl\Curl.php``` line ```145```

**Comment by zachborboa** [comment]
Hi thanks for filing a bug. Similar to https://github.com/php-curl-class/php-curl-class/issues/345
I've been working on a fix, hang tight. Thanks

**Comment by julianrutten** [comment]
Thanks :) Sorry for not checking. Closing this issue as its a duplicate.
