### ISSUE TITLE
MultiCurl running past curl timeout

### ISSUE THREAD

**Issue by iautomation** [php-curl-class/php-curl-class#363]
What is the expected behavior?
Each Curl instance is set with CURLOPT_TIMEOUT=>5 & CURLOPT_CONNECTTIMEOUT=>3 via the setOpt method. This should limit each handle to run a maximum of 5 seconds. If cURL multi is runs these instances in parallel, I would think the maximum time for each instance would be the maximum time for all instances.

What is the actual behavior?
It's taking much longer to run all of them. In fact, it's running faster with Curl than with MultiCurl

What steps will reproduce the problem?
This is run on a dedicated Centos server. Example code(modified):
```
$curl_opts = [
	CURLOPT_CONNECTTIMEOUT=>3,
	CURLOPT_TIMEOUT=>5
];
$multi_curl = new MultiCurl();
foreach($curl_opts as $key=>$value)
	$multi_curl->setOpt($key, $value);

$multi_curl->complete(function($instance){
	echo 1;
});

foreach($domains as $domain){
	$multi_curl->addGet('http://'.$domain);
	if(count($multi_curl->curls)>=5){
		$multi_curl->start(); // takes anywhere from 3s to 20s to run
		echo '<br>';
	}
}

```

**Comment by zachborboa** [comment]
Hi. You should probably only be calling `start()` once. In your example, it would be after queueing the requests.

```
$curl_opts = [
    CURLOPT_CONNECTTIMEOUT=>3,
    CURLOPT_TIMEOUT=>5
];
$multi_curl = new MultiCurl();
foreach($curl_opts as $key=>$value)
    $multi_curl->setOpt($key, $value);

$multi_curl->complete(function($instance){
    echo 1;
});

foreach($domains as $domain){
    $multi_curl->addGet('http://'.$domain);
}

$multi_curl->start();
```

Here's an another example
https://github.com/php-curl-class/php-curl-class/blob/master/examples/multi_curl_get_callbacks.php
