### ISSUE TITLE
Hoy to replicate curl -X POST https://example.com -F "variable[price]=12.50" -F "variable[attachment]=@/filepath.png"

### ISSUE THREAD

**Issue by nesttle** [php-curl-class/php-curl-class#374]
## What is the expected behavior?
Simulate **_CURL -F_** with php-curl-class

> curl -X POST https://example.com -F "variable[price]=12.50" -F "variable[attachment]=@/filepath.png"

## What is the actual behavior?
Error **422** HTTP/1.1

## What steps will reproduce the problem?

> 	$postarray = array(
> 		'variable[attachment]' => '@/filepath.png'
> 		'variable[price]' => '12.50'
> 	);
> 
> 	$curl = new Curl();
> 	$curl->setBasicAuthentication($auth['apikey'], $auth['secret']);
> 	$curl->setHeader('Accept', 'application/json');
> 	$curl->post('https://www.example.com/api/v1/p', $postarray);
> 	if ($curl->error) {
> 		return 'Error: ' . $curl->errorCode . ': ' . $curl->errorMessage;
> 	}
> 	else {
> 		return $curl->response;
> 	}

**Comment by zachborboa** [comment]
Try `$curl->setHeader('Content-Type', 'multipart/form-data');`.

https://github.com/php-curl-class/php-curl-class/blob/master/examples/upload_file.php
