### ISSUE TITLE
Require PHP 7.0+

### ISSUE THREAD

**Issue by zachborboa** [php-curl-class/php-curl-class#380]
This ticket is to document changes that can be made if and when support for <s>PHP 5.3 is</s> various PHP versions are dropped.

Changes/Improvements for PHP 5.4+
- [x] Use short array syntax. e.g. `$a = [1, 2, 3, 4];` or `$a = ['one' => 1, 'two' => 2, 'three' => 3, 'four' => 4];`
- [x] Add `callable` type declarations (type hinting) (https://secure.php.net/manual/en/functions.arguments.php#functions.arguments.type-declaration)
- [x] Remove 5.3 use of web server in favor of built-in development web server ([before_script.sh](https://github.com/php-curl-class/php-curl-class/blob/master/tests/before_script.sh))
- [x] Remove 5.3 test environment ([.travis.yml](https://github.com/php-curl-class/php-curl-class/blob/master/.travis.yml))

For PHP 5.5+
- [ ] Use native PHP solution to limit the number of simultaneously open connections that libcurl may cache: `curl_multi_setopt($ch, CURLMOPT_MAXCONNECTS, $limit);`
- [x] Use `json_last_error_msg()` without checking if `function_exists('json_last_error_msg')`.
- [x] Remove 5.4 test environment ([.travis.yml](https://github.com/php-curl-class/php-curl-class/blob/master/.travis.yml))

For PHP 5.6+
- [x] Remove 5.5 test environment ([.travis.yml](https://github.com/php-curl-class/php-curl-class/blob/master/.travis.yml))

For PHP 7.0+
- [ ] Add `bool`, `float`, `int`, `string` type declarations (type hinting) (https://secure.php.net/manual/en/functions.arguments.php#functions.arguments.type-declaration)
- [ ] Possibly use `declare(strict_types=1);` (https://www.php.net/manual/en/functions.arguments.php#functions.arguments.type-declaration.strict)
- [x] Remove 5.6 test environment ([.travis.yml](https://github.com/php-curl-class/php-curl-class/blob/master/.travis.yml))

For PHP 7.1+
- [ ] Remove 7.0 test environment ([.travis.yml](https://github.com/php-curl-class/php-curl-class/blob/master/.travis.yml))

For PHP 7.2+
- [ ] Remove 7.1 test environment ([.travis.yml](https://github.com/php-curl-class/php-curl-class/blob/master/.travis.yml))

For PHP 7.3+
- [ ] Remove 7.2 test environment ([.travis.yml](https://github.com/php-curl-class/php-curl-class/blob/master/.travis.yml))

For PHP 7.4+
- [ ] Remove 7.3 test environment ([.travis.yml](https://github.com/php-curl-class/php-curl-class/blob/master/.travis.yml))

For PHP 8.0+
- [ ] Use named arguments (https://wiki.php.net/rfc/named_params)
- [ ] Remove 7.4 test environment ([.travis.yml](https://github.com/php-curl-class/php-curl-class/blob/master/.travis.yml))

**Comment by Oxicode** [comment]
+1

**Comment by zachborboa** [comment]
Active support for PHP 5.6 ended on Jan 19, 2017. We may just jump to requiring 5.6+

![image](https://cloud.githubusercontent.com/assets/1083146/24071721/3d6ae768-0b96-11e7-80ee-38486ab13a4a.png)
https://secure.php.net/supported-versions.php

**Comment by gotardo** [comment]
Hi,
Would it be interesting to work on a branch for PHP7.x?

**Comment by zachborboa** [comment]
@gotardo Since there's still a high percentage of users on old versions of PHP and the library works on 7.x as is, I personally am not going to dive into making PHP 7+ only changes just yet.

![image](https://user-images.githubusercontent.com/1083146/31702664-65fd895c-b38d-11e7-8050-a27482b74d58.png)
from https://wordpress.org/about/stats/

**Comment by Oxicode** [comment]
Min 5.6

**Comment by peter279k** [comment]
It should be min is `5.5` I think because the [json_last_error_msg](http://php.net/manual/en/function.json-last-error-msg.php) function only supports `php-.5.5+`.

**Comment by Dibbyo456** [comment]
Since PHP 5.x has reached EOL years ago and the only supported versions are 7.2+
Is there any particular reason you're still supporting older versions? As for WordPress, vast majority has now shifted to 7.x

**Comment by zachborboa** [comment]
PHP 5.x now makes up about around 15% of the reported numbers:
![image](https://user-images.githubusercontent.com/1083146/111174420-ca843400-857d-11eb-9866-77f4d94a7da1.png)

(colors have been updated to match the first pie chart screenshot: https://github.com/php-curl-class/php-curl-class/issues/380#issuecomment-337467095)
