### ISSUE TITLE
How do you get a POST response?

### ISSUE THREAD

**Issue by notflip** [php-curl-class/php-curl-class#382]
I would like to POST to a url and get the response, it should be in json
I get a 302 status code but can't seem to see more

**Comment by zachborboa** [comment]
Hi. 302 is redirection. Take a look at `var_dump($curl->responseHeaders);`, specifically `var_dump($curl->responseHeaders['Location']);`.

**Comment by zuoRambo** [comment]
how to support CURLOPT_FOLLOWLOCATION

**Comment by zuoRambo** [comment]
when i use download function to download a file from one url,if the response header is 302,my file save to local is 0 bytes.

**Comment by zachborboa** [comment]
@zuoRambo 
```php
$curl = new Curl();
$curl->setOpt(CURLOPT_FOLLOWLOCATION, true);
$curl->download('https://www.example.com/image.png', '/tmp/image.png');
```

**Comment by zuoRambo** [comment]
that's pretty cool!
