### ISSUE TITLE
download when statusCode == '302'

### ISSUE THREAD

**Issue by zuoRambo** [php-curl-class/php-curl-class#390]
when i use download function, i want it could auto redirect when response's status is '302'

but,it not, because it use 'get' in the download function:
```php
        if (is_callable($mixed_filename)) {
            $this->downloadCompleteFunction = $mixed_filename;
            $fh = tmpfile();
        } else {
            $filename = $mixed_filename;
            $fh = fopen($filename, 'wb');
        }

        $this->setOpt(CURLOPT_FILE, $fh);
        $this->get($url);
        $this->downloadComplete($fh);

        return ! $this->error;
```

how can i fix this question?

**Comment by zachborboa** [comment]
Hi. Here's an example https://github.com/php-curl-class/php-curl-class/blob/master/examples/download_file_with_redirect.php

**Comment by zuoRambo** [comment]
that's good then i add 'setPost(CURLOPT_FOLLOWLOCATION, true)' in Curl-get() [src/Curl/Curl.php#L413]
