### ISSUE TITLE
setHeaders() method

### ISSUE THREAD

**Issue by Philipp91** [php-curl-class/php-curl-class#391]
Currently, there are two ways to set headers:
a) Call "setHeader" for every single one, which will rebuild the array for curl every single time and call setOpt every time.
b) Write to the "requestHeaders" field directly. One might accidentally use a normal array() instead of a CaseInsensitiveArray one, don't know if that matters. Anyway, it feels weird writing to those fields from a OO perspective and setOpt doesn't get called like this, so one last header must be set using the setHeader method.

I suggest a setHeaders method which takes an array and writes all of them to the local array, then calls setOpt. I can provide a pull request.

**Comment by zachborboa** [comment]
Fixed in 36ad0e4ecf24ffd1d576113fa826be949df6cc1c. Thanks!

**Comment by Philipp91** [comment]
Thank you!
