### ISSUE TITLE
error response should be parsed to a xml obj

### ISSUE THREAD

**Issue by liyadongcn** [php-curl-class/php-curl-class#394]
What is the expected behavior?
when get the response with error , the response string should be treated as a xml obj as the response   without errors.

What is the actual behavior?
return a string

What steps will reproduce the problem?

**Comment by zuoRambo** [comment]
you could setDefaultDecoder('xml')

**Comment by zachborboa** [comment]
Perhaps the content-type in the response headers isn't xml. Look at `var_dump($curl->responseHeaders['content-type']);`or `var_dump($curl->responseHeaders);`.
