### ISSUE TITLE
Set UTF-8 as default?

### ISSUE THREAD

**Issue by Philipp91** [php-curl-class/php-curl-class#397]
I'm following best practice advice and set the encoding to UTF-8 wherever I can.
If I don't do
`$curl->setOpt(CURLOPT_ENCODING, "UTF-8");`
the response is garbled. Interestingly, the PHP documentation (http://php.net/manual/de/function.curl-setopt.php) doesn't list charsets as valid values, but things like "gzip". Nevertheless, it works because it sets the Accept-Encoding header and at least the servers that I am communicating with apparently choose another encoding by default.

So it's worth thinking about an option in the Curl class for CURLOPT_ENCODING or even the Accept-Encoding header directly, which defaults to UTF-8. On the other hand, this might break existing uses of the library, where the default encoding is not UTF-8, but just happened to be the right one.  Also, I'm not sure how many encoding problems that would solve, depends on how many servers respect "Accept-Encoding: UTF-8".

**Comment by zachborboa** [comment]
Hi. `UTF-8` is not a valid argument for `CURLOPT_ENCODING`. Try an empty string instead.

```php
$curl->setOpt(CURLOPT_ENCODING, '');
```
