### ISSUE TITLE
Reuse the same handle

### ISSUE THREAD

**Issue by webbolo** [php-curl-class/php-curl-class#402]
I was wondering.. Why not reusing the curl handle? As far as i know making many (synchronous) calls to the same server would use the same connection making the entire task faster.

More available here:
[http://stackoverflow.com/questions/3787002/reusing-the-same-curl-handle-big-performance-increase](http://stackoverflow.com/questions/3787002/reusing-the-same-curl-handle-big-performance-increase)

**Comment by zachborboa** [comment]
Here's an example for how to reuse using `Curl` instead of `MultiCurl`.
```php
$curl = new Curl();
$curl->get('https://www.example.com/');
var_dump($curl->response);
$curl->get('https://www.example.com/');
var_dump($curl->response);
```
