### ISSUE TITLE
getInfo fct should be able to return all infos

### ISSUE THREAD

**Issue by Bertutchio** [php-curl-class/php-curl-class#404]
What is the expected behavior?
I should be able to retrieve **all** the curl info when i use the **getInfo** method with no parameter.

What is the actual behavior?
Currently the opt parameter is required. It's painful if you want all infos.

Thanks.

**Comment by zachborboa** [comment]
Thanks for the suggestion!

**Comment by Bertutchio** [comment]
Thanks !
