### ISSUE TITLE
support resume

### ISSUE THREAD

**Issue by foxer2010** [php-curl-class/php-curl-class#405]
can you add CURLOPT_RANGE to Download Function
to make curl support resume download

```
      if (file_exists($filename)) {
            $from = filesize($filename);
            $this->setOpt(CURLOPT_RANGE, $from . "-");
        }
```

and change 
`$fh = fopen($filename, 'wb');`
to
`$fh = fopen($filename, 'ab');`
to avoid truncate the file

**Comment by zachborboa** [comment]
Thanks for the suggestion!
