### ISSUE TITLE
Multidimensional Arrays as POST Fields

### ISSUE THREAD

**Issue by bob-zs** [php-curl-class/php-curl-class#406]
What is the expected behavior?
```php
$curl->post($endpoint, [
        'OuterArrayKey' => [
            'title' => 'Testing API'
            ,'opened_at' =>  '10 Feb 2011, 15:37'
            ,'occured_at' => '10 Feb 2011, 15:37'
        ]
    ]));
```
* This code should go through. *

What is the actual behavior?
* What happens is a "Error: 400: HTTP/1.1 400 Bad Request"*

Could I suggest having an option in `Curl::post` to have:
```php
$data = json_encode($data);
```

instead of

```php
$data = http_build_query($data);
```

**Comment by zachborboa** [comment]
Hi. Here's an example showing how to POST json.
https://github.com/php-curl-class/php-curl-class/blob/master/examples/post_json.php

You need
```php
$curl->setHeader('Content-Type', 'application/json');
```
