### ISSUE TITLE
setOpt error when using CURLOPT_SSLVERSION

### ISSUE THREAD

**Issue by mcred** [php-curl-class/php-curl-class#409]
When using the code below:
```
$this->curl = new Curl();
$this->curl->setOpt('CURLOPT_SSLVERSION', 6);
```
I will receive the following error:
`curl_setopt() expects parameter 2 to be integer, string given`

I have tried a few variations of this, but no matter what I pass for the second parameter in setOpt it will always be sent to Curl as a string and not the actual parameter given.

**Comment by zachborboa** [comment]
```php
$curl->setOpt(CURLOPT_SSLVERSION, 6);
```

**Comment by mcred** [comment]
That got it! Thank you.
