### ISSUE TITLE
The process cannot access the file because it is being used by another process. (code: 32)

### ISSUE THREAD

**Issue by minhphuc429** [php-curl-class/php-curl-class#430]
i had error when run this code
`$curl->download($url, __DIR__ . '/download/image.png');`

**Comment by tansautn** [comment]
Check your file "__DIR__ . '/download/image.png'" , it might be wirting/reading by another process. Also can be another curl session

**Comment by asktobeasked** [comment]
No. It's a bug. This error occur because of  you call rename function before you close resource. To fix it, open file Curl.php, find

    private function downloadComplete($fh)
    {
	    if (!$this->error && $this->downloadCompleteFunction) {
             rewind($fh);
             $this->call($this->downloadCompleteFunction, $fh);
            $this->downloadCompleteFunction = null;
           }

        if (is_resource($fh)) {
            fclose($fh);
        }

change to:

    private function downloadComplete($fh)
    {

        if (is_resource($fh)) {
            fclose($fh);
        }

		if (!$this->error && $this->downloadCompleteFunction) {
            //rewind($fh); //Unnecessary
            $this->call($this->downloadCompleteFunction, $fh);
            $this->downloadCompleteFunction = null;
        }

with function download, you should add mode as a parameter to user can easy custom it

**Comment by asktobeasked** [comment]
And because of function download will call function get so that you should add $data as a parameter too. It should be as 

public function download($url, $data = array(), $mixed_filename, $mode)

**Comment by zachborboa** [comment]
@asktobeasked can you provide a code snippet to reproduce the problem? Thanks

**Comment by asktobeasked** [comment]
@zachborboa As I said above, the problem occur because of the function rename run while file resource still open. So that to fix it, simple close resource before call downloadCompleteFunction. It's my code:

Find:

            // Move the downloaded temporary file to the destination save path.
            $this->downloadCompleteFunction = function ($fh) use ($download_filename, $filename) {
                rename($download_filename, $filename);
            };

Replace by

            // Move the downloaded temporary file to the destination save path.
            $this->downloadCompleteFunction = function ($fh) use ($download_filename, $filename) {
                if($this->error)
					unlink($download_filename);
				else
					rename($download_filename, $filename);
				
            };

Find:
        if (!$this->error && $this->downloadCompleteFunction) {
            rewind($fh);
            $this->call($this->downloadCompleteFunction, $fh);
            $this->downloadCompleteFunction = null;
        }

        if (is_resource($fh)) {
            fclose($fh);
        }

Replace by:

        if (is_resource($fh)) 
		{
            fclose($fh);
        }

		if ($this->downloadCompleteFunction) {
            //rewind($fh);
            $this->call($this->downloadCompleteFunction, $fh);
            $this->downloadCompleteFunction = null;
        }

**Comment by zachborboa** [comment]
@asktobeasked I'm unable to reproduce the issue. Can you reply with a code sample to reproduce? That would really help. I also created a pull request (https://github.com/php-curl-class/php-curl-class/pull/434) with the changes mentioned, but it breaks the build.

**Comment by asktobeasked** [comment]
The issue from download method, friend. You can easy test it by the code:

$curl = new Curl();
$curl->download('https://secure.php.net/images/logos/php-med-trans.png', '/tmp/php-med-trans.png');

You will receive the error above because you call rename function before you close the file resource

**Comment by zachborboa** [comment]
Unable to reproduce the "process cannot access the file" error. As suggested, tried:

```php
$curl = new Curl();
$curl->download('https://secure.php.net/images/logos/php-med-trans.png', '/tmp/php-med-trans.png');
```

**Comment by zachborboa** [comment]
Reopening since there are more reports of this bug. Still need to determine how exactly to reproduce this issue.

**Comment by Chak10** [comment]
I have the same error.
```php
$curl = new Curl();
$curl->download('https://lh4.googleusercontent.com/-v0soe-ievYE/AAAAAAAAAAI/AAAAAAADwkE/KyrKDjjeV1o/photo.jpg', 'image.jpg');
```
Result 
```text
Warning: rename(image/image.jpg.pccdownload,image/image.jpg): Failed to access file. File used by another process. (Code: 32) in C:\wamp64\www\class\cURL\Curl.php on line 287.
```

**Comment by zachborboa** [comment]
According to @Chak10's comment, it appears this bug occurs when using Wampserver.

**Comment by zachborboa** [comment]
Thank you for the comments and help debugging this issue. I was able to reproduce on Windows. A fix will be out shortly.
