### ISSUE TITLE
Set CURLOPT_HTTPHEADER influence the next curl post request.

### ISSUE THREAD

**Issue by yinfuyuan** [php-curl-class/php-curl-class#436]
Hello, i have the following questions.
        I send the first request with CURLOPT_HTTPHEADER and this value set Content-Type is multipart/form-data.
        
        `$ch = curl_init();`
        `curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type:multipart/form-data'));`
        `curl_setopt($ch, CURLOPT_URL, 'http://www.baidu.com');`
        `curl_setopt($ch, CURLOPT_POST, true);`
        `curl_exec($ch);`
        `curl_close($ch);`

        The next curl post request i use php-curl-class and not set CURLOPT_HTTPHEADER, but the server cannot receive the data.

        `$curl = new \Curl\Curl();`
        `$curl->post([server_host], array('name'=>'name'));`
        `var_dump($curl1->response);// output array(0) { }`
        `exit;`

        If i don't use php-curl-class or use other classlib the server can right receive the data.

        `$ch2 = curl_init();`
        `curl_setopt($ch2, CURLOPT_URL, [server_host]);`
        `curl_setopt($ch2, CURLOPT_POST, true);`
        `curl_setopt($ch2, CURLOPT_POSTFIELDS, array('name'=>'name'));`
        `curl_exec($ch2);// output {"name":"name"}`
        `curl_close($ch2);`
        `exit;`

        No matter use which kinds of method, the second request header Content-Type value both is multipart/form-data, but use the php-curl-class can't receive the data.

**Comment by zachborboa** [comment]
Hi. What content-type is the server expecting? If the server is expecting `multipart/form-data`, you can do this:

```php
$curl = new Curl();
$curl->setHeader('Content-Type', 'multipart/form-data');
```

**Comment by yinfuyuan** [comment]
The server is not expecting multipart/form-data and server is expecting bodyParams.
 but if i do this in first curl request:

$curl->setHeader('Content-Type', 'multipart/form-data');

The server received bodyParams is empty at the second curl requests.
The two curl requests are in the same http request.

**Comment by zachborboa** [comment]
I'm not following. I don't see bodyParams in your examples.

I need a better example of what your full script looks like. Does it look like this?
```php
$curl = new \Curl\Curl();
$curl->post($server_host, array('name' => 'name'));
var_dump($curl->response);

$curl->post($server_host, array('name' => 'name'));
var_dump($curl->response);
```

**Comment by yinfuyuan** [comment]
@zachborboa Yes. Now I'll give a complete example:

```
$file_data = array('file' => 'file');
$request_url = 'http://yinfy.weizhan.51cto.com/api/banners'; // Need to fill in a url
$curl = new \Curl\Curl();
$curl->setHeader('Content-Type', 'multipart/form-data'); // #anchor-1
$curl->post($request_url, $file_data);
if(!$curl->error) {
    var_dump($curl->response);//The value is "array(0) { }", If i annotation "#anchor-1", the value is 'object(stdClass)#94 (1) { ["file"]=> string(4) "file" }'
    echo '<br>';
}
$curl->close();

$data_new = array('name' => 'name');
$request_url_new = 'http://yinfy.weizhan.51cto.com/api/feedbacks'; // Need to fill in a url
$curl_new = new \Curl\Curl();
$curl_new->post($request_url_new, $data_new);
if(!$curl_new->error) {
    var_dump($curl_new->response);//The value is "array(0) { }", If i annotation "#anchor-1", the value is 'object(stdClass)#99 (1) { ["name"]=> string(4) "name" }'
    exit;
}
$curl_new->close();
```

The object  $curl setHeader('Content-Type', 'multipart/form-data') has influenced on the new object $curl_new result.

**Comment by zachborboa** [comment]
Here's what I tested. I created a file `file.txt` and ran the following. Do you see the same?
```php
use \Curl\Curl;

$curl = new \Curl\Curl();
$curl->setHeader('Content-Type', 'multipart/form-data');
$curl->post('http://127.0.0.1:8000/', array('file' => '@file.txt'));
echo 'response 1:' . "\n";
var_dump($curl->response);
$curl->close();

$curl_new = new \Curl\Curl();
$curl_new->post('http://127.0.0.1:8000/', array('name' => 'name'));
echo 'response 2:' . "\n";
var_dump($curl_new->response);
$curl_new->close();
```

```
$ php example.php 
response 1:
string(84) "string(70) "multipart/form-data; boundary=------------------------56dc8a146f910c92"
"
response 2:
string(47) "string(33) "application/x-www-form-urlencoded"
"
```

**Comment by zachborboa** [comment]
For the server

```php
<?php
var_dump($_SERVER['CONTENT_TYPE']);
```

```
$ php -S 127.0.0.1:8000 index.php
```

**Comment by yinfuyuan** [comment]
@zachborboa 
I use browser run your example，and get the result is this:

`response 1: string(33) "string(19) "multipart/form-data" " response 2: string(33) "string(19) "multipart/form-data" "`

I try to use console run your example and run the same command, but I get result is null like this:
`response 1:
string(5) "NULL
"
response 2:
string(5) "NULL
"`
and i get the notice from server:
`PHP Notice:  Undefined index: CONTENT_TYPE in ...`

I change 
`var_dump($_SERVER['CONTENT_TYPE']);`
to
`var_dump($_SERVER);`
I get the result is this:
`response 1:
string(1171) "array(22) {
  ......
  ["HTTP_CONTENT_TYPE"]=>
  string(70) "multipart/form-data; boundary=----------------------------06995504e60f"
  ......
}
"
response 2:
string(1082) "array(21) {
   ......
  ["HTTP_CONTENT_TYPE"]=>
  string(33) "application/x-www-form-urlencoded"
  ......
}
"`

I use browser get `var_dump($_SERVER);` result is this:
`response 1: string(1763) "
array(36) {
  ......
  ["CONTENT_TYPE"]=>
  string(19) "multipart/form-data"
  ......
  ["HTTP_CONTENT_TYPE"]=>
  string(19) "multipart/form-data"
  ......
}

"
response 2:
string(1760) "
array(36) {
  ......
  ["CONTENT_TYPE"]=>
  string(19) "multipart/form-data"
  ......
  ["HTTP_CONTENT_TYPE"]=>
  string(19) "multipart/form-data"
  ......
}

"`

My php version info is:
`PHP 5.5.25 (cli) (built: Feb 28 2017 09:48:53) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with XCache v3.2.0, Copyright (c) 2005-2014, by mOo
    with XCache Cacher v3.2.0, Copyright (c) 2005-2014, by mOo`

**Comment by zachborboa** [comment]
I'm unable to reproduce. What operating system are you using?

```php
<?php
var_dump(PHP_VERSION);
var_dump($_SERVER['HTTP_CONTENT_TYPE']);
```

From the command line
```
$ php --version
PHP 5.5.25 (cli) (built: Jul  3 2017 03:30:51) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
```

```
$ php page.php 
response 1:
string(103) "string(6) "5.5.25"
string(70) "multipart/form-data; boundary=------------------------ae3a2490b7056095"
"
response 2:
string(66) "string(6) "5.5.25"
string(33) "application/x-www-form-urlencoded"
"
```

From the browser
```
response 1:
string(103) "string(6) "5.5.25"
string(70) "multipart/form-data; boundary=------------------------ca76eaf006042e19"
"
response 2:
string(66) "string(6) "5.5.25"
string(33) "application/x-www-form-urlencoded"
"
```

**Comment by yinfuyuan** [comment]
@zachborboa  My operating system is `CentOS release 6.5 (Final)`

Since you unable to reproduce，you can close this issue now. This issue maybe affected with my other environment.When i find specific info,I'll report to you again.
