### ISSUE TITLE
How to use it in laravel

### ISSUE THREAD

**Issue by sml2h3** [php-curl-class/php-curl-class#437]
How to use it in laravel?
I composer it but show me this:
Using version ^7.2 for php-curl-class/php-curl-class
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v5.4.12
    - Conclusion: don't install laravel/framework v5.4.12
    - Can only install one of: laravel/framework[v5.4.9, v5.4.12].
    - don't install laravel/framework v5.4.12|remove illuminate/console v5.4.9
    - don't install illuminate/console v5.4.9|don't install laravel/framework v5.4.12
    - don't install illuminate/console v5.4.9|don't install laravel/framework v5.4.12
    - Installation request for laravel/framework (locked at v5.4.12, required as 5.4.*) -> satisfiable by laravel/framework[v5.4.12].
    - Installation request for illuminate/console (locked at v5.4.9) -> satisfiable by illuminate/console[v5.4.9], laravel/framework[v5.4.9].

Installation failed, reverting ./composer.json to its original content.

**Comment by ddouglas493** [comment]
I use it in Laravel with no issue. Below is the portion of my composer.json that would help with your situation. Once you make the modification necessary, do the following:

- composer dumpautoload
- composer update nothing (This will install no dependency without attempting to update existing ones)

 

```
"require": {
        "php": ">=5.6.4",
        "3rdpartyeve/phealng": "~2.0",
        "anlutro/l4-settings": "^0.4.9",
        "doctrine/dbal": "^2.5",
        "laravel/framework": "5.3.*",
        "php-curl-class/php-curl-class": "^7.1",
        "zizaco/entrust": "5.2.x-dev"
    },
```

**Comment by zachborboa** [comment]
Confirmed version latest stable (v7.2) working with Laravel.

```
    "require": {
        "php": ">=5.6.4",
        "laravel/framework": "5.4.*",
        "laravel/tinker": "~1.0",
        "php-curl-class/php-curl-class": "^7.2"
    },
```
