### ISSUE TITLE
HTTP Error 400. The request verb is invalid when POST after GET using same curl session

### ISSUE THREAD

**Issue by asktobeasked** [php-curl-class/php-curl-class#438]
I received the error:

Bad Request - Invalid Verb

HTTP Error 400. The request verb is invalid.

if I POST after GET  using same curl session

eg:

$data = array(
'demo' = 'demo'
);
$curl = new Curl();
$curl->get('http://www.demo.com'); => It's OK
$curl->post('http://www.demo.com', $data); => It will occur error above

I think seem that have some problem with var $options or $headers, they need some reset before switch from GET to POST but I cannot find why. Please check and find solution for it

**Comment by asktobeasked** [comment]
After carefully check it, I found the problem. The error occur because you used CURLOPT_CUSTOMREQUEST option for get, post...Because of it's meaningless. Please see https://curl.haxx.se/libcurl/c/CURLOPT_CUSTOMREQUEST.html

1. CURLOPT_CUSTOMREQUEST option only accept value HTTP, FTP, IMAP, POP3, and SMTP. So that GET and POST value are meaningless
2. Please read http://stackoverflow.com/questions/4163865/how-to-reset-curlopt-customrequest
It's a php bug, you cannot reset CURLOPT_CUSTOMREQUEST by NULL 
3. I'm testing by set value of $follow_303_with_post to true (default in your script is false) that mean it will set CURLOPT_CUSTOMREQUEST = POST but some server when require more Content-Lenght. So that need write more code for header

=> My solution is 
1. Remove $this->setOpt(CURLOPT_CUSTOMREQUEST, 'GET') in get(...) function method
2. Remove 

        if ($this->follow_303_with_post) {
            $this->setOpt(CURLOPT_CUSTOMREQUEST, 'POST');
        } else {
            if (isset($this->options[CURLOPT_CUSTOMREQUEST])) {
                if ((version_compare(PHP_VERSION, '5.5.11') < 0) || defined('HHVM_VERSION')) {
                    trigger_error(
                        'Due to technical limitations of PHP <= 5.5.11 and HHVM, it is not possible to '
                        . 'perform a post-redirect-get request using a php-curl-class Curl object that '
                        . 'has already been used to perform other types of requests. Either use a new '
                        . 'php-curl-class Curl object or upgrade your PHP engine.',
                        E_USER_ERROR
                    );
                } else {
                    $this->setOpt(CURLOPT_CUSTOMREQUEST, null);
                }
            }
        }

in post(...) function method:

Done ;)

**Comment by zachborboa** [comment]
1. The protocols supported are HTTP, FTP, IMAP, POP3, and SMTP. The values GET and POST are supported and not meaningless.
2. You can restore CURLOPT_CUSTOMREQUEST to the the default by using null. We use it where supported or trigger an error.

Closing since you found a solution.
