### ISSUE TITLE
about buildUrl ,queryString problem

### ISSUE THREAD

**Issue by rainlay** [php-curl-class/php-curl-class#441]
Hi, I had meet a build query string problem,

the problem is after http_build_query, the query string was encoded,

but the third party api didn't accept the symbol encoded, ex : comma

for example my queryString is : 

> ?user_ids=my_id1%2my_id2

but the api cant get the param

the api only accpeted the queryString is

> ?user_ids=my_id1,my_id2

so my problem is , it is possible to change   

```
private function buildURL($url, $data = array())
{
    return $url . (empty($data) ? '' : '?' . http_build_query($data, '', '&'));
}
```

to:
```
private function buildURL($url, $data = array())
{
    //data is encode string to solve the custom encode problem
    if ( is_string($data))
    {
        return $url . (empty($data) ? '' : '?' . $data);
    }
    return $url . (empty($data) ? '' : '?' . http_build_query($data, '', '&'));
}
```
to solve the problem, or is any better solution?

**Comment by zachborboa** [comment]
Hi. Are you making a POST request, a GET, request or something else? Can you provide a sample request you're making? Thanks

**Comment by rainlay** [comment]
Hi, I was made a GET request 

the sample is like (the queryString after http_build_query) :

> fail request

`https://api.sendbird.com/v3/users?user_ids=user_1%2user_2`

> response

```
{
  "users": [],
  "next": ""
}
```

> success request

`https://api.sendbird.com/v3/users?user_ids=user_1,user2`

> response

```
{
  "users": [
    {
      "user_id": "user_1",
      "is_active": true,
      "is_online": false,
      "last_seen_at": 1490683927390,
      "nickname": "user_1",
      "profile_url": ""
    },
    {
      "user_id": "user_2",
      "is_active": true,
      "is_online": false,
      "last_seen_at": 1490685668791,
      "nickname": "user_2",
      "profile_url": ""
    }
  ],
  "next": ""
}
```

**Comment by zachborboa** [comment]
How are you constructing the request in php? Can you just make the request like this?
```php
$curl = new Curl();
$curl->get('https://api.sendbird.com/v3/users?user_ids=user_1,user2');
```

**Comment by rainlay** [comment]
Yes, just build it manually like this (even is not good)

`       
        $queryString = $this->build_http_query($data);
        $queryString .= '&'. 'user_ids=' . $user_ids;`

`
  $this->curl->get($url, $queryString);
`

**Comment by zachborboa** [comment]
Thanks for explaining further. I've created a [pull request](https://github.com/php-curl-class/php-curl-class/pull/442) to allow using a string.

```php
$curl = new Curl();
$curl->get('https://www.example.com/', 'user_ids=user_1,user_2');
```
