### ISSUE TITLE
Suggested: please Add AZURE curl GET feature for Cloud API's

### ISSUE THREAD

**Issue by inglesuniversal** [php-curl-class/php-curl-class#451]
SAMPLE REQUEST FROM AZURE's WEBSITE:

GET https://api.cognitive.microsoft.com/bing/v5.0/news/trendingtopics HTTP/1.1
Host: api.cognitive.microsoft.com
Ocp-Apim-Subscription-Key: ••••••••••••••••••••••••••••••••

USING your Script... from the EXAMPLE section...

```
<?php
// PHP CURL CLASS
// SOURCE: https://github.com/php-curl-class/php-curl-class
```

```
require '/vendor/autoload.php';

use \Curl\Curl;
// curl --request GET "https://httpbin.org/get?key=value"
$curl = new Curl();
$curl->get('https://api.cognitive.microsoft.com/bing/v5.0/news/trendingtopics/', array(
    'Ocp-Apim-Subscription-Key' => '***************************',
));
if ($curl->error) {
    echo 'Error: ' . $curl->errorCode . ': ' . $curl->errorMessage . "\n";
} else {
    echo 'Response:' . "\n";
    var_dump($curl->response);
}
```

I am getting this ERROR:

Error: 401: HTTP/1.1 401 Access Denied

How could that be... IF I am able to see the response and data at AZURE's site...

Any Clue on how to solve and add this feature to your SCRIPT ?

Thanks

**Comment by zachborboa** [comment]
Hi. `Ocp-Apim-Subscription-Key` should be set as a header.

```php
$curl = new Curl();
$curl->setHeader('Ocp-Apim-Subscription-Key', 'my-key');
$curl->get('...');
```
