### ISSUE TITLE
Please remove symlink examples/vendor

### ISSUE THREAD

**Issue by tomcyr** [php-curl-class/php-curl-class#454]
What is the expected behavior?
No errors during creating zip archive

What is the actual behavior?
During creating zip archive for deployment an error occurs "error calling stat: No such file or directory /xxx/vendor/php-curl-class/php-curl-class/examples/vendor"

What steps will reproduce the problem?
Creating zip archive with project

**Comment by zachborboa** [comment]
Thanks for report.

Note: similar to #279

**Comment by tomcyr** [comment]
@zachborboa Thanks.
