### ISSUE TITLE
Groups

### ISSUE THREAD

**Issue by drcrash84** [php-curl-class/php-curl-class#460]
Group 1:
some urls array to get response
Group 2:
some urls array to get response
Group 3:
some urls array to get response

All groups should work in parallel mode.
How to put response from each Group when it will be complete in a separate variables ($group1, $group2, $group3?

**Comment by zachborboa** [comment]
Possibly something like this
```php
$groups = array();

$multi_curl = new MultiCurl();
$multi_curl->success(function ($instance) use (&$groups) {
    $groups[$instance->group] = $instance->response;
});

$get_1 = $multi_curl->addGet('https://www.example.com/');
$get_1->group = 'a';

$get_2 = $multi_curl->addGet('https://www.example.net/');
$get_2->group = 'b';

$get_3 = $multi_curl->addGet('https://www.example.org/');
$get_3->group = 'c';

$multi_curl->start();

var_dump($groups);
```

**Comment by drcrash84** [comment]
That's what i search, thanks.
But how to use array of urls in this example instead one url like this:
$get_1 = $multi_curl->addGet('https://www.example.com/');
