### ISSUE TITLE
How to use array?

### ISSUE THREAD

**Issue by drcrash84** [php-curl-class/php-curl-class#462]
`$groups = array();

$multi_curl = new MultiCurl();
$multi_curl->success(function ($instance) use (&$groups) {
    $groups[$instance->group] = $instance->response;
});

$get_1 = $multi_curl->addGet('https://www.example.com/');
$get_1->group = 'a';

$get_2 = $multi_curl->addGet('https://www.example.net/');
$get_2->group = 'b';

$get_3 = $multi_curl->addGet('https://www.example.org/');
$get_3->group = 'c';

$multi_curl->start();

var_dump($groups);`

how to use array of urls in groups instead one url?
Like this:
`$get_1 = $multi_curl->addGet(array('https://www.example.com/', 'https://www.example.net/'));`

but this construction not working

**Comment by zachborboa** [comment]
Hi. Calling `addGet()` with an array is not possible as implemented. Something like this could work:

```php
$multi_curl = new MultiCurl();
foreach ($list_of_urls as $url) {
    $multi_curl->addGet($url);
}
$multi_curl->start();
```
