### ISSUE TITLE
No common encryption algorithm

### ISSUE THREAD

**Issue by Pirenko** [php-curl-class/php-curl-class#463]
Hi,
I'm having trouble with a cURL request... The error that I get is "_cURL error 35: Cannot communicate securely with peer: no common encryption algorithm(s)._"

Also, this issue only happens on some servers... I mean depending on the server that calls the script that executes the PHP script that error is generated or not.
Any ideas?

Thanks!

**Comment by zachborboa** [comment]
Hi. I believe this error means that curl couldn't find an encryption that both client and server support. For the sites where this happens, you may try entering the domain on https://www.ssllabs.com/ssltest/analyze.html to see what encryption algorithms are supported.

**Comment by Pirenko** [comment]
Thanks for your response!
