### ISSUE TITLE
Proposal to allow url parameters in base url for all http protocols

### ISSUE THREAD

**Issue by dwestvik** [php-curl-class/php-curl-class#464]
There are web services that include url parameters within the published endpoint. An example is Netsuite restlets have the format:
https://rest.sandbox.netsuite.com/app/site/hosting/restlet.nl?script=192&deploy=1

When using a GET, you may need to append additional query parameters to this base url such as
https://rest.sandbox.netsuite.com/app/site/hosting/restlet.nl?script=192&deploy=1&rec=7426

The issue is when you need to use a POST,PUT, etc.  In the the 2nd parameter to these requests allow for the data to be sent in the body (as it should). However, in those cases, the url parameters would need to be included in the URL parameter of $curl->post(). 

This leads to a non-consistent method to specify an endpoint url. That is for a GET, if you do provide the url parameters 'script=192&deploy=1' within the provided URL, the query 'rec=7426' cannot be appended (via the GET 2nd parameter) since it adds an additional '?' (query mark) to the url.
https://rest.sandbox.netsuite.com/app/site/hosting/restlet.nl?script=192&deploy=1?rec=7426

My proposal is to modify the buildUrl method to handle a base url that has included query strings and still allow additional parameters to be added when calling GET (or other similar methods). This is done by checking the passed URL for a pre-existing query '?' and changing this 'mark' to an '&' to allow appending of additional query parameters. 

The result allows any class using Curl can now have a consistent endpoint URL for all HTTP methods. 

My proposed change:  (I can provide a PR with this and additional buildUrl test options.

[in Curl.php - buildUrl]

         if (!empty($mixed_data)) {
            $query_mark = (strpos($url,'?')>0)? '&':'?';
             if (is_string($mixed_data)) {
                $query_string .= $query_mark . $mixed_data;
             } elseif (is_array($mixed_data)) {
                $query_string .= $query_mark . http_build_query($mixed_data, '', '&');
             }
          }

**Comment by zachborboa** [comment]
Merged in https://github.com/php-curl-class/php-curl-class/commit/cd08b5dee7d2a9ae04acc19e2237d8cd193dccc7 Thanks!
