### ISSUE TITLE
Reset without memory leak

### ISSUE THREAD

**Issue by CashCode** [php-curl-class/php-curl-class#466]
Does the complete request automatically delete from queue and I can put another one in working queue without memory leak?
For example: I need to process 200 queries, I run multi with 20 threads, when one is ready I need to put one inside instead, without stop. Any working example?
Regards.

**Comment by zachborboa** [comment]
Hi. Yes completed requests are automatically removed from the queue and additional requests may be added. Here's an example that uses multi curl:
https://github.com/php-curl-class/php-curl-class/blob/master/examples/multi_curl_get.php

All examples can be found here:
https://github.com/php-curl-class/php-curl-class/tree/master/examples
