### ISSUE TITLE
Starting queue many times

### ISSUE THREAD

**Issue by CashCode** [php-curl-class/php-curl-class#467]
Hey. I couldnt find any build function for setting up proxy. Is there any?
Sometimes there is a situation, when proxy has very big time connect (more then 5-10 seconds) and in result the queue stucks.
```
require __DIR__ . '/vendor/autoload.php';

use \Curl\MultiCurl;

// Requests in parallel with callback functions.
$multi_curl = new MultiCurl();



$multi_curl->complete(function($instance) {
 var_dump($instance->response);
});

$multi_curl->addGet('http://cih.ms', array(
    'q' => 'hello world',
)); // for example, this stucks
$multi_curl->addGet('http://cih.ms');


$multi_curl->start(); // Blocks until all items in the queue have been processed.
```
How not to wait for stuck request being executed, and put some new urls and start again?
Should I just put it and make $multi_curl->start() again?

**Comment by CashCode** [comment]
$multi_curl->curls is private property

**Comment by zachborboa** [comment]
You can add all the urls first, then call `$multi_curl->start();`. You may also increase the number of simultaneous by using `$multi_curl->setConcurrency($concurrency);`.

**Comment by CashCode** [comment]
But sometimes it's not enough, sometimes it has about 200 tasks to do in a short limit of time.  Server can keep only 50 properly. And when one is completed I want to put another one. That's the idea.
