### ISSUE TITLE
Put requests after blocking multi_curl

### ISSUE THREAD

**Issue by CashCode** [php-curl-class/php-curl-class#469]
```$multi_curl->start(); // Blocks until all items in the queue have been processed.```
Sometimes I have about 200 tasks to do in a short limit of time. Server can keep only 50 properly. And when one is completed I want to put another one. Is it safe to put somehow more request in a blocked queue? Or should I start a new one, will it run async?
For example:
```
$multi_curl1->start();
// checking how many is completed from $multi_curl1, when half is completed
//setting up
$multi_curl2->start();
```
And another case, when I have chain of queries (more than 2), for example authorization, is there any way to make it async? I mean when I have 20 threads, and I need to make many different queries in any of the threads without waiting another ones.
In pure multicurl there is an option to put another request in queue.
Regards.

**Comment by zachborboa** [comment]
Hi. Yes you can add additional requests (e.g. via `addGet`, `addPost`, etc.) after starting.

```php
$urls = array();
for ($i = 0; $i < 10; $i++) {
    $urls[] = 'https://www.example.com/?' . md5(mt_rand());
}

$multi_curl = new MultiCurl();
$multi_curl->complete(function ($instance) use (&$multi_curl, &$urls) {
    $next_url = array_pop($urls);
    if (!($next_url === null)) {
        $multi_curl->addGet($next_url);
    }
});

$multi_curl->addGet(array_pop($urls));
$multi_curl->start();
```
