### ISSUE TITLE
Error: 60: Peer certificate cannot be authenticated with given CA certificates: SSL certificate problem: self signed certificate

### ISSUE THREAD

**Issue by Issa2008** [php-curl-class/php-curl-class#470]
`'Error: 60: Peer certificate cannot be authenticated with given CA certificates: SSL certificate problem: self signed certificate'`

to fiw this i think u have to add this : 

```
$curl = new Curl();
$curl->setOpt( CURLOPT_SSL_VERIFYPEER, FALSE);
```

**Comment by zachborboa** [comment]
Hi. Disabling `CURLOPT_SSL_VERIFYPEER` is not recommended. If you can't establish a connection without disable ssl protections, the connection cannot be (reasonably) guaranteed. Try using a different computer or a different connection when making the request.
