### ISSUE TITLE
POST fails if Preceded by PUT

### ISSUE THREAD

**Issue by sganz** [php-curl-class/php-curl-class#475]
What is the expected behavior?
Expect the POST to always set the correct Content-Length header

What is the actual behavior?
The Post call uses the existing (LAST) set Content-Length from the previous call, in my case the code has a loop around a set of calls like (WHERE some_data is a string)-
```
while(something_or_other)
{
  curl->post(some_url, some_data);
  curl->put(some_other_url, some_params);
}
```
First time through the loop, works like a charm. The second time the Content-Length header is reporting the length from the previous PUT call.

What steps will reproduce the problem?
Create a sequence of calls like the above example, make sure content lengths are DIFFERENT and it should fail.
You can see the issue if you turn on curl verbose() which will show what it things the content length is and what is is sending Like this debug snip-

```
Content-Length: 45

* upload completely sent off: 45 out of 45 bytes
```
Above output that is OK, it fails with output looking like below

```
Content-Length: 45

* upload completely sent off: 25 out of 25 bytes
```
At this point the server on the other end times out waiting for data.

To verify the fix I set the content length explicitly before the post call and all is well. I did it like this -

```
$this->curl->setHeader('Content-Length', strlen($this->curl->buildPostData($card)));

```

**Comment by sganz** [comment]
I tried a hack and a PR but didn't realize that the post data could also be an array. I think the problem only shows up when the post data is a string type not an array.

Sorry for the hack PR :)

**Comment by zachborboa** [comment]
Hi. Similarly to #472, I believe this issue also should be fixed. Regards

**Comment by sganz** [comment]
Zach -
Just ran all the code on the new version and worked well. 

Again thanks for an easy to use well thought out package!

Sandy

**Comment by zachborboa** [comment]
@sganz You're very welcome
