### ISSUE TITLE
the compressed transfer example could be improved

### ISSUE THREAD

**Issue by divinity76** [php-curl-class/php-curl-class#481]
first off, it sets the compression algorithm to "gzip" specifically, but it should just be set to emptystring, because that makes curl list all supported encodings (which is usually "gzip" and "deflate", but will automatically include any other compression algorithms libcurl was compiled with, as well as stopping it from offering gzip encoding when libcurl was not actually compiled with gzip support)

second, the example tries to download a png file with compression... png files are already pre-compressed, and won't benefit from being gzip compressed during transfer, in fact, it's just a waste of cpu, both for the server and the client. (well, unless the server use something like [ngx_http_gzip_static_module](http://nginx.org/en/docs/http/ngx_http_gzip_static_module.html), in which case its just a cpu waste for the client, but no sane sysadmin would pre-gz compress individual .png files anyway )

**Comment by zachborboa** [comment]
Hi. Would this be a better example?
```
$curl = new Curl();
$curl->setOpt(CURLOPT_ENCODING , '');
$curl->download('https://www.example.com/file.bin', '/tmp/myfile.bin');
```

**Comment by divinity76** [comment]
yes!

(but personally i would use a filetype that is guaranteed to benefit from compression, like `.xml` , but that's not important)
