### ISSUE TITLE
Documentation improvement

### ISSUE THREAD

**Issue by peter279k** [php-curl-class/php-curl-class#483]
As title, can I add the documentation for ```examples``` PHP file?
I plan to create and classify the categories for each example scripts and add the descriptions for the example scripts.
Can you suggest some tips for this work? How to start this work?

Thanks.

**Comment by zachborboa** [comment]
Hi. It may beneficial to organize the `examples` directory. Possibly into 2 categories:

```
examples/
├── curl
│   ├── get.php
│   ├── post.php
│   ├── ...
└── multicurl
    ├── multi_curl_get.php
    ├── multi_curl_post.php
    └── ...
```

**Comment by peter279k** [comment]
Ok, good categories. I also think we need to have the online doc for usage and sample code in```examples``` like [this](https://irazasyed.github.io/telegram-bot-sdk/).

What do you think?

**Comment by zachborboa** [comment]
That seems like a fairly good example. I would like to keep the maintenance of the examples to a minimum if possible.

**Comment by KarelWintersky** [comment]
```
$curl->get($url); 
```
returns object, not string!

**Comment by zachborboa** [comment]
No response so closing for now.
