### ISSUE TITLE
CURLOPT_UNIX_SOCKET_PATH

### ISSUE THREAD

**Issue by eckelarsson** [php-curl-class/php-curl-class#484]
What is the expected behavior?
To do curl request with a unix socket path as endpoint

What is the actual behavior?
Malformed url, tried too add localhost as url but dosen't seams that it takes as well, then i get "Couldn't connect to server"

        $socket = "unix:///var/run/docker.sock";

        $curl = new Curl();

        $curl->setUrl('http://localhost');
        $curl->setHeader('Host', 'localhost');
        $curl->setHeader('Content-type', 'application/json');
        $curl->setOpt(CURLOPT_UNIX_SOCKET_PATH, $socket);
        $curl->get('/containers/json');

**Comment by zachborboa** [comment]
Hi. You need to change the socket. This works:
```php
$curl = new Curl();
$curl->setUrl('http://localhost');
$curl->setOpt(CURLOPT_UNIX_SOCKET_PATH, '/var/run/docker.sock');
$curl->get('/containers/json');
var_dump($curl->response);
```
