### ISSUE TITLE
How to Handle Concurrent Request Responses

### ISSUE THREAD

**Issue by alivelimeli** [php-curl-class/php-curl-class#487]
Hello,

I have 2 different urls in different hosts that I need to make a request. 

Those requests can be run as parallel using muti_curl. 

I've checked the multi_curl example but one point is not clear for me.

First request has much more priority to be completed (with or without error). 

So I need to add to get requests and handle those requests. 

But the callback is called when they are completed.

I'm ok with parallel requests but not ok with parallel response handling together. 

Could you please give me an example of how I can process results if both requests are completed (with or without success)?

Thanks

**Comment by zachborboa** [comment]
Hi. I believe you're trying to make requests in parallel, but handle responses differently depending on the type of request. Something like this should work:
```php
$multi_curl = new MultiCurl();
$multi_curl->success(function ($instance) {
    echo 'call to "' . $instance->url . '" was successful.' . "\n";
    echo 'response: ' . $instance->response . "\n";
    if ($instance->handler === 'response_type_1') {
        // Handle response type 1.
    } else if ($instance->handler === 'response_type_2') {
        // Handle response type 2.
    } else if ($instance->handler === 'response_type_3') {
        // Handle response type 3.
    }
});

$get1 = $multi_curl->addGet('https://www.example.com/');
$get->handler = 'response_type_1';

$get2 = $multi_curl->addGet('https://www.example.org/');
$get2->handler = 'response_type_2';

$get3 = $multi_curl->addGet('https://www.example.net/');
$get3->handler = 'response_type_3';

$multi_curl->start();
```
