### ISSUE TITLE
Return data and keys of CaseInsensitiveArray as public attributes

### ISSUE THREAD

**Issue by ddavaham** [php-curl-class/php-curl-class#489]
What is the expected behavior?

The ability to systematically loop through the Request and Response Headers to evaluate them and make decisions off of them

What is the actual behavior?

These are private attributes, so I am unable to access them as an array. Rather I have to call offsetGet from CaseInsensitiveArray but that requires a key to be included. I need the ability to store the array in the database.

What steps will reproduce the problem?

No need to reproduce. Just attempt to retrieve all the headers as an array.

**Comment by zachborboa** [comment]
Hi. You are able to loop through all the headers.

```php
foreach ($curl->responseHeaders as $key => $value) {
    echo $key . ' => ' . $value . "\n";
}
```

```
Status-Line => HTTP/1.1 200 OK
Connection => keep-alive
Content-Type => application/json
Access-Control-Allow-Origin => *
Access-Control-Allow-Credentials => true
...
```
