### ISSUE TITLE
Undefined offset: 1 in function parseHeaders

### ISSUE THREAD

**Issue by beeyev** [php-curl-class/php-curl-class#490]
Periodically get such error

> ErrorException (E_NOTICE)
Undefined offset: 1

Error appears in [this line](https://github.com/php-curl-class/php-curl-class/blob/dc8282d086362d946520781c8908e0b084f01438/src/Curl/Curl.php#L1366)

This is how raw_headers looks like

> "raw_headers" => array:2 [▼
    0 => """
      HTTP/1.0 403 Forbidden\n
      Cache-Control: no-cache\n
      Content-Type: text/html\n
      Strict-Transport-Security: max-age=0
      """
    1 => "\n"

**Comment by zachborboa** [comment]
Thanks!
