### ISSUE TITLE
Why not use getOpt ? 

### ISSUE THREAD

**Issue by KyranRana** [php-curl-class/php-curl-class#492]
https://github.com/php-curl-class/php-curl-class/blob/e2b3f7abfea95a1fadb3f6eb849b76e88cca0f6f/src/Curl/Curl.php#L591

You are checking if an option is set in the options array, but doesn't getOpts already do that?

**Comment by zachborboa** [comment]
Hi. You're right that `getOpt()` could be used here. However, I think the `isset` version reads more clearly.

**Comment by KyranRana** [comment]
Fair enough :+1:
