### ISSUE TITLE
Filling the request body in the mode MultiCurl ignores the content type specified in the object MultiCurl.

### ISSUE THREAD

**Issue by Nexvelius** [php-curl-class/php-curl-class#493]
Hello! My English is not my native language and if my words will not be clear for you, let me know.

In the process of working with your library, I discovered different behavior of queries using class Curl and MultiCurl class.

Please pay your attention to the method [buildPostData](https://github.com/php-curl-class/php-curl-class/blob/master/src/Curl/Curl.php#L150)

```php
    public function buildPostData($data)
    {
        $binary_data = false;
        if (is_array($data)) {
            // Return JSON-encoded string when the request's content-type is JSON.
            if (isset($this->headers['Content-Type']) &&
                preg_match($this->jsonPattern, $this->headers['Content-Type'])) {
                $json_str = json_encode($data);
```

You can see that it takes into account the Content-Type header if it matches the pattern for forming the JSON, convert the data into jSON.

This works fine, but let's now look at the [addPost method in class MultiCurl.](https://github.com/php-curl-class/php-curl-class/blob/master/src/Curl/MultiCurl.php#L207)

```php
    public function addPost($url, $data = array(), $follow_303_with_post = false)
    {
        if (is_array($url)) {
            $follow_303_with_post = (bool)$data;
            $data = $url;
            $url = $this->baseUrl;
        }
        $curl = new Curl();
        if (is_array($data) && empty($data)) {
            $curl->removeHeader('Content-Length');
        }
        $curl->setUrl($url);
        /*
         * For post-redirect-get requests, the CURLOPT_CUSTOMREQUEST option must not
         * be set, otherwise cURL will perform POST requests for redirections.
         */
        if (!$follow_303_with_post) {
            $curl->setOpt(CURLOPT_CUSTOMREQUEST, 'POST');
        }
        $curl->setOpt(CURLOPT_POST, true);
        $curl->setOpt(CURLOPT_POSTFIELDS, $curl->buildPostData($data));
        $this->queueHandle($curl);
        return $curl;
    }
```

You can see that inside this method creates a new Curl object and calls its method buildPostData.

If I call $multiCurl->setHeader('Content-Type', 'application/json) before calling addPost, it will not be considered here and the encoding in JSON is not going to happen.

This is because the Curl object knows nothing about the headers of MultiCurl.

It seems non-obvious. Of course, you can pre-encode your data in JSON, but it seemed to me that I had to tell you about it.

Thank you for your attention.

**Comment by zachborboa** [comment]
Great find! Thank you
