### ISSUE TITLE
How to upload multipart file with attributes?

### ISSUE THREAD

**Issue by daninthemix** [php-curl-class/php-curl-class#496]
I'm trying to upload files to Box.

This works absolutely fine when there's no attributes:

$this->Curl->setHeader('Content-Type', 'multipart/form-data');
$this->Curl->post("https://upload.box.com/api/2.0/files/{$ID}/content", array('file' => "@$log"));

However this doesn't work:

$this->Curl->post("https://upload.box.com/api/2.0/files/content", array('name' => $name, 'parent' => ['id' => $parentID], 'file' => "@$log"));

The API returns ''parent is required", and from [their API reference](https://developer.box.com/reference#upload-a-file) I notice this:

_The "attributes" (JSON) part must come before the file part of the multipart form data._

So how would I structure my Curl request based on the above?

Thanks

**Comment by daninthemix** [comment]
OK, this is resolved by doing json_encode on all the file metadata and including it as the 'attributes' post field.

**Comment by zachborboa** [comment]
Sounds like you were able to find a solution. Adding an example based on the docs (https://developer.box.com/reference#upload-a-file):

```sh
curl https://upload.box.com/api/2.0/files/content \
  -H "Authorization: Bearer ACCESS_TOKEN" -X POST \
  -F attributes='{"name":"tigers.jpeg", "parent":{"id":"11446498"}}' \
  -F file=@myfile.jpg
```

```php
$curl = new Curl();
$curl->setHeader('Authorization',  'Bearer ACCESS_TOKEN');
$curl->setHeader('Content-Type', 'multipart/form-data');
$curl->post('https://upload.box.com/api/2.0/files/content', array(
    'attributes' => json_encode(
        array(
            'name' => 'tigers.jpeg',
            'parent' => array(
                'id' => '11446498',
            ),
        ),
    ),
    'file' => '@myfile.jpg',
));
```
