### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by SpazzMarticus** [php-curl-class/php-curl-class#497]
I like this repository, but I am quite afraid of updating to newer versions, because there is no changelog listing the changes made.

Please add a changelog containing API-changes, deprecations, fixes, ...
[Guide I found useful.](http://keepachangelog.com/en/1.0.0/)

**Comment by zachborboa** [comment]
Hi. I adhere to semantic versioning (https://semver.org/) as much as possible so that minor and patch version updates can be done safely.

Another option to see the changes between versions, is the compare page.
https://github.com/php-curl-class/php-curl-class/compare/8.0.0...8.0.1

**Comment by SpazzMarticus** [comment]
Going through a list of commits to see what changed is quite time consuming. Maybe you could pinpoint to the major changes in the [releases](https://github.com/php-curl-class/php-curl-class/releases).

You can close this issue, if you want.

**Comment by timomayer** [comment]
i agree with @SpazzMarticus . a CHANGELOG.md file with the breaking changes would be helpful. going through commits for each new major version is not an option
