### ISSUE TITLE
How I use resetful.

### ISSUE THREAD

**Issue by oneword** [php-curl-class/php-curl-class#502]
The api is resetful url ,How to use it on multi? 
example:
https://www.google.com/a/b/c/d
https://www.google.com/a/b/e/f
https://www.google.com/a/b/g/h
https://www.google.com/a/b/i/j

The api is "https://www.google.com/a/b", and I params is "['c','d']","['e','f']","['g','h']","['i','j']".
sorry for my terrible english.

**Comment by zachborboa** [comment]
This could work.

```php
use \Curl\MultiCurl;


$params = [
    ['c', 'd'],
    ['e', 'f'],
    ['g', 'h'],
    ['i', 'j'],
];

$multi_curl = new MultiCurl();

foreach ($params as $param) {
    $url = 'https://www.google.com/a/b/' . implode('/', $param);
    $multi_curl->addGet($url);
    echo $url . "\n";
}

$multi_curl->start();
```
