### ISSUE TITLE
Is it possible to "fake" a request with this library

### ISSUE THREAD

**Issue by ddavaham** [php-curl-class/php-curl-class#503]
I am seeing scenarios popup in my application where i need to be able to build an instance of Curl\Curl to deliver a message that will filter down through my application.

One in particular scenario is with the automate calls to an API. Until I get the timing down, I keep getting blocked. I would like to be able to store a key in Redis indicating if I am blocked and for how long and have a script check redis. If redis says i should still be blocked, I would like to Create an instance of CURL Curl with a custom HTTP Status Code and return that to the script making the request. 

Now if this is possible, great. If not, then I am going to have to redo some code blocks so handle a simple false or a custom payload of some sort.

**Comment by zachborboa** [comment]
If you really wanted, you could create an instance like this
```php
$curl = new Curl();
$curl->error = true;
$curl->httpStatusCode = 404;
$culr->errorMessage = '404 Not Found';
$curl->response = 'Page not found';
```
