### ISSUE TITLE
Problems with Cyrillic in url

### ISSUE THREAD

**Issue by RussianBulls** [php-curl-class/php-curl-class#505]
if there is a Cyrillic script in the url, it fails: "Maximum execution time of 180 seconds exceeded"

example: $curl->get('http://balemala.com/index.php/vmchk/Банан-комнатный-саженцы-банана/View-all-products.html');

**Comment by zachborboa** [comment]
Hi, thank you for the bug report. PHP Curl Class uses the `parse_url` function which only works on UTF-8 characters. Until a fix is implemented, you will need to percent-encode urls. Here is that url percent-encoded.

http://balemala.com/index.php/vmchk/%D0%91%D0%B0%D0%BD%D0%B0%D0%BD-%D0%BA%D0%BE%D0%BC%D0%BD%D0%B0%D1%82%D0%BD%D1%8B%D0%B9-%D1%81%D0%B0%D0%B6%D0%B5%D0%BD%D1%86%D1%8B-%D0%B1%D0%B0%D0%BD%D0%B0%D0%BD%D0%B0/View-all-products.html

**Comment by zachborboa** [comment]
Fixed. Thanks for the suggestion
