### ISSUE TITLE
HTTPS - Add "custom headers" after CONNECT method

### ISSUE THREAD

**Issue by rodlac** [php-curl-class/php-curl-class#509]
Can it possible to add "custom headers" after CONNECT method when using HTTPS? I need it because I have to add some headers that can be read by proxy and if I add on HTTP Headers the proxy can't read because of the headers are encrypted.

Example:

CONNECT example.com:443 HTTP/1.1
My-Custom-Header: Some value goes here

*actual request headers*

PS: My proxy can read custom headers after CONNECT method

**Comment by zachborboa** [comment]
I would try using `CURLOPT_PROXYHEADER`.

```php
$curl = new Curl();
$curl->setOpt(CURLOPT_PROXYHEADER, ...);
```

See also the documentation for `CURLOPT_HEADEROPT`.
![image](https://user-images.githubusercontent.com/1083146/39080813-be69074e-44ea-11e8-9fff-afaa3a1712df.png)
https://secure.php.net/manual/en/function.curl-setopt.php
