### ISSUE TITLE
Is there a way to send POST without body?

### ISSUE THREAD

**Issue by watari** [php-curl-class/php-curl-class#511]
In my case API for which I write integration logic refuses to receive my request for authentication under reason  "400 Bad Request". It caused by POST body '[]' that is created from default data value for post method of the class. In old versions of cUrl class (3.*)  data was checked if it not empty before build, but now this check is gone. 

My question is next: how I can send POST request that will contain only headers?

-------------------------------------------------------------------------------------------------------------------------------

**What is the expected behavior?**
If body not specified (or empty array) it should not be included under option 'CURLOPT_POSTFIELDS'
**What is the actual behavior?**
Class include empty body as '[]'.
**What steps will reproduce the problem?**
Create POST request without body.

**Comment by zachborboa** [comment]
Hi. Here's how to send a POST request without a body:

```php
$curl = new Curl();
$curl->post('https://www.example.com/');
```

Verify POST body is empty.
```php
$curl = new Curl();
$curl->post('https://httpbin.org/post');
var_dump($curl->requestHeaders['Content-Length'] === '0');
var_dump($curl->response->headers->{'Content-Length'} === '0');
```
Output
```
bool(true)
bool(true)
```

**Comment by watari** [comment]
Hi. That is exactly how I do when get 400 error code from API.
This code caused by this line [Curl.php:615](https://github.com/php-curl-class/php-curl-class/blob/bdcf04391795a2732b0ce08c605e3c0a1c259944/src/Curl/Curl.php#L615)

Please reread description of issue. Thanks.

**Comment by watari** [comment]
@zachborboa, in old version before setting this option check was performed.

       if(!(is_array($data) && empty($data))) {
            $this->setOpt(CURLOPT_POSTFIELDS, $this->buildPostData($data));
        }

**Comment by zachborboa** [comment]
Thanks for checking again. I needed to set a json content-type. This reproduces the error:

```php
$curl = new Curl();
$curl->setHeader('Content-Type', 'application/json');
$curl->post('https://httpbin.org/post');
var_dump($curl->requestHeaders['Content-Length'] === '0');
var_dump($curl->response->headers->{'Content-Length'} === '0');
```

**Comment by zachborboa** [comment]
If you'd like to test again, please use the latest version.

    $ composer require php-curl-class/php-curl-class @dev

**Comment by watari** [comment]
Thanks for fix. Now all works fine.
