### ISSUE TITLE
Add support for soap+xml detection

### ISSUE THREAD

**Issue by mazinsw** [php-curl-class/php-curl-class#513]
Please add support for ```application/soap+xml```

This must match header like: ```Content-Type: application/soap+xml; charset=UTF-8```

File: ```Curl\Curl.php```

Before soap support
```php
private $xmlPattern = '~^(?:text/|application/(?:atom\+|rss\+)?)xml~i';
```
After soap support
```php
private $xmlPattern = '~^(?:text/|application/(?:atom\+|rss\+|soap\+)?)xml~i';
```

**Comment by zachborboa** [comment]
Thanks!
