### ISSUE TITLE
Method Curl\Url::__toString() must not throw an exception, caught Error: Call to undefined function Curl\mb_substr()

### ISSUE THREAD

**Issue by burpsuite** [php-curl-class/php-curl-class#517]
## Snapshot
![2018-04-28 23 31 00](https://user-images.githubusercontent.com/14309190/39398387-81a035a2-4b3f-11e8-8b5c-c306be4dc15e.png)

## Example
```json
{
    "require": {
        "ext-mbstring": "*"
    }
}
```

## Description
zh_CN: 请添加"ext-mbstring"至"composer.json"!
en_US: Please add "ext-mbstring" in "composer.json"!

**Comment by zachborboa** [comment]
zh_CN: 谢谢!
en_US: Thank you!
