### ISSUE TITLE
Memory Leaks

### ISSUE THREAD

**Issue by Bertutchio** [php-curl-class/php-curl-class#521]
**What is the expected behavior ?**

Instantiate many objects do not increase the memory usage.

**What is the actual behavior?**

Instantiate multiple times the Curl class increase the memory usage.

As described here : https://bugs.php.net/bug.php?id=69639 and here : https://bugs.php.net/bug.php?id=60139 using closure with class property results in memory leaks.

Any idea on how to resolve this ?

**What steps will reproduce the problem?**

The following code will show the memory increase :

```
for ($i=0; $i < 10000; $i++) {
    $curl = new Curl();
    var_dump(memory_get_usage());
    unset($curl);
}
```

**Comment by zachborboa** [comment]
Thanks!
