### ISSUE TITLE
Is there a reason why there's no accessor for curl_reset function via this class?

### ISSUE THREAD

**Issue by rsanaie** [php-curl-class/php-curl-class#523]
What is the expected behavior?
re-initializes all options set on the given cURL handle

What is the actual behavior?
Not implemented

Reference:
http://php.net/manual/en/function.curl-reset.php

**Comment by zachborboa** [comment]
Hi, thanks for the idea. Maybe it could be implemented so this would work:

```php
$curl = new Curl();
$curl->setUserAgent('My test user-agent');

// Reset all previously set options.
$curl->reset();

$curl->get('https://www.example.com/');
```
