### ISSUE TITLE
$curl->download - appending new downloads to old one if same filename.

### ISSUE THREAD

**Issue by mboveiri** [php-curl-class/php-curl-class#528]
Hi.
how can call method to replace file instead appending file.?
Thank you.

**Comment by zachborboa** [comment]
Hi, The `Curl::download()` method will resume a download if the download was interrupted (and the temporary file exists). Once the file download completes, the completed temporary file is renamed to the filename specified in the 2nd parameter passed to `Curl::download()`.

If you would like to ensure that a file is not appended, you could `unlink()` the file.
https://secure.php.net/manual/en/function.unlink.php
