### ISSUE TITLE
Infinite loop bug in removeDotSegments

### ISSUE THREAD

**Issue by IMN-MichaelL** [php-curl-class/php-curl-class#530]
Trying to curl this url (http://www.supichka.com/рецепта/219/мъфини-всички-рецепти-за-мъфини-на-едно-място) results in an infinite loop in removeDotSegments due to not using a multibyte compliant function here https://github.com/php-curl-class/php-curl-class/blob/8.0.1/src/Curl/Url.php#L75 .

In testing, using this solution [here](http://php.net/manual/en/function.substr-replace.php#90146) solves the problem. 

Also there are also other functions in here that should be multibyte compliant as well that could lead to issues as they are.

**Comment by MattJVarney** [comment]
I can confirm this issue

**Comment by zachborboa** [comment]
Hi, I'm unable to reproduce. What version of PHP and PHP Curl Class are you using?

**Comment by IMN-MichaelL** [comment]
PHP: 7.0.30-1+ubuntu14.04.1+deb.sury.org+1
PHP Curl Class: 8.0.1

**Comment by zachborboa** [comment]
Hi, It appears you are using 8.0.1. Please use the latest version 8.1.0.
