### ISSUE TITLE
Unable to get web page data with http status code 302

### ISSUE THREAD

**Issue by luolongfei** [php-curl-class/php-curl-class#537]
What is the expected behavior?What is the actual behavior?
Hello, I have a problem. When I use $curl->get() function to request this address: https://my.freenom.com/domains.php, the returned http status code is 302. The web page data should be returned as expected, but The value of $curl->response is empty.
But I use my own packaged curl class to get the data of this page is no problem. So I think it might be a bug in php-curl-class

What steps will reproduce the problem?
My part of the code is as follows:
```php
        $curl->setHeader('Accept', 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8');
        $curl->setReferrer('https://my.freenom.com/clientarea.php');
        $curl->setOpts([
            'CURLOPT_FOLLOWLOCATION' => true,
            'CURLOPT_AUTOREFERER' => true
        ]);
        $curl->get('https://my.freenom.com/domains.php', [
            'a' => 'renewals'
        ]);
```
Looking forward to your reply, thank you!

**Comment by zachborboa** [comment]
Hi, turn on error reporting with `error_reporting(E_ALL);` and you should see this error:

```bash
$ php examples/get.php 
PHP Warning:  curl_setopt() expects parameter 2 to be integer, string given in ../php-curl-class/src/Curl/Curl.php on line 989

Warning: curl_setopt() expects parameter 2 to be integer, string given in ../php-curl-class/src/Curl/Curl.php on line 989
```

Use constants, not strings:
```php
$curl->setOpts([
    CURLOPT_FOLLOWLOCATION => true,
    CURLOPT_AUTOREFERER => true,
]);
```

**Comment by luolongfei** [comment]
It's working for me, thank you very much!
