### ISSUE TITLE
release improvement

### ISSUE THREAD

**Issue by adhocore** [php-curl-class/php-curl-class#541]
there is no release info/note https://github.com/php-curl-class/php-curl-class/releases/tag/8.3.0

and there is no changelog too https://github.com/php-curl-class/php-curl-class
and no way to know active version except the badge

i dont know if releases are automated, at least i dont see that in [travis](https://github.com/php-curl-class/php-curl-class/blob/master/.travis.yml)

i would like to propose using [please](https://github.com/adhocore/please) for managing release. which automatically does all the things with just one simple command

**disclaimer** i authored `please`

**Comment by zachborboa** [comment]
Hi, thank you for the suggestion. I've added a placeholder [CHANGELOG.md](https://github.com/php-curl-class/php-curl-class/blob/master/CHANGELOG.md) file.

(Previous discussion: #497)

**Comment by zachborboa** [comment]
Fixed in https://github.com/php-curl-class/php-curl-class/commit/b1c882ec346d5db1a504aaf793d272d81e4331be
