### ISSUE TITLE
Error in empty response in Decoder.php

### ISSUE THREAD

**Issue by arthusu** [php-curl-class/php-curl-class#543]
What is the expected behavior? no error

What is the actual behavior? error because it always returns result without validating before

What steps will reproduce the problem? send several requests through ajax I threw an error

![screenshot_127](https://user-images.githubusercontent.com/12725208/44554408-11735b00-a6ee-11e8-9d72-290d17e9e0b8.png)

solution: 

normal: 

`return $response;`

modified:

```
if(!empty($response)){
            return $response;
        }
```
in line 52

greetz

**Comment by zachborboa** [comment]
Thanks!
