### ISSUE TITLE
Is there an example to get past CSRF example?

### ISSUE THREAD

**Issue by ChoonKwang** [php-curl-class/php-curl-class#549]
Hi, I'm facing some API call to dango application where by they state"
CSRF verification failed. Request aborted.

You are seeing this message because this site requires a CSRF cookie when submitting forms. This cookie is required for security reasons, to ensure that your browser is not being hijacked by third parties.

If you have configured your browser to disable cookies, please re-enable them, at least for this site, or for 'same-origin' "

I tried to use a GET request to get their responseCookies and setcookie in my next POST. However, it is still not working.

**Comment by zachborboa** [comment]
Hi. You'll need to make 2 requests. Pull the csrf token in the first request. Once you have the token, include the token in the second request. For Django sites, the csrf name should be `csrfmiddlewaretoken`.

```php
// Get token.
$curl = new Curl();
$curl->get('https://www.example.com/login');
preg_match('...', $curl->response, $matches); // TODO: Implement token extraction.
$csrf_token = $matches[0];

// Do POST action with csrf token.
$curl = new Curl();
$curl->post('https://www.example.com/login', array(
    'csrfmiddlewaretoken' => $csrf_token,
    'username' => '',
    'password' => '',
));
```

**Comment by ChoonKwang** [comment]
Thanks for your assistance, it works perfectly fine!
