### ISSUE TITLE
Failure when receiving data from the peer: Received HTTP code 407 from proxy after CONNECT

### ISSUE THREAD

**Issue by sbaikov96** [php-curl-class/php-curl-class#552]
Hi! I make a request using a proxy, but I get an error

```
        $parser = new Curl();
	$parser->setProxy($proxy', '3128', '$login', '$pass');
	$parser->setProxyTunnel();
```

> Failure when receiving data from the peer: Received HTTP code 407 from proxy after CONNECT

Tested these proxies in the browser, all is well.

**Comment by zachborboa** [comment]
Hi. 407 is `Proxy Authentication Required`. Remove the quotes:

```php
$parser->setProxy($proxy', '3128', $login, $pass);
```

**Comment by sbaikov96** [comment]
but when I specify a proxy manually, without variables, the result is the same
