### ISSUE TITLE
Send a XML Post

### ISSUE THREAD

**Issue by nronsisvalle** [php-curl-class/php-curl-class#553]
Hi there,
i'm testing this cool library on my php project. What i've to do is to send a XML post content to an external webservice. 

What is the expected behavior?
Post a Content-Type: text/xml to an external webservice.  
Eg: "< ? xml version="1.0" encoding="UTF-8"?>
< Order xmlns="http://mywebservice.local/RestGateway">
....."

What is the actual behavior?
Right now, i can see that my XML was changed to "data=%3C%3Fxml+version%3D%221.0%22+encoding%3D%22UTF-8%22%3F%3E%0A%3COrder+xmlns%3D%22http%......."

What steps will reproduce the problem?
I can see that file src/Curl/Curl.php - line 613 is:
$this->setOpt(CURLOPT_POSTFIELDS, $this->buildPostData($data));

So my datas are prior processed by buildPostData() function.

How can bypass this behaviour? 

Hope what i wrote is easily understandable, if it isn't, please let me know and i'll try to explain the issue as better as i can 

Thank you a lot in advance
Regards

**Comment by zachborboa** [comment]
Hi, I've added an example here
https://github.com/php-curl-class/php-curl-class/blob/master/examples/post_xml.php

**Comment by nronsisvalle** [comment]
Hi, thank you for your response.
I tried your example but it doesn't change this behaviour. XML is still changed in 
data=%3C%3Fxml+version%3D%221.0%22+encoding%3D%22UTF-8%22%3F%3E%0A%3COrder+xmlns%3D%22http%3A%2F%2F.......

**Comment by zachborboa** [comment]
@nronsisvalle can you provide a code sample? Thanks
