### ISSUE TITLE
Temporary file not removed when download fail

### ISSUE THREAD

**Issue by kn-id** [php-curl-class/php-curl-class#555]
Temporary file (.pccdownload) is not removed when download failed (404).

```php
$curl = new \Curl\Curl();
$curl->setOpt(CURLOPT_ENCODING , "");
$curl->download("https://google.com/404", "/tmp/not_found_download.txt");
$curl->close();
```

`/tmp/not_found_download.txt.pccdownload` is not removed

**Comment by zachborboa** [comment]
Thanks!

**Comment by kn-id** [comment]
Could you make a new release for this? @zachborboa

**Comment by zachborboa** [comment]
@kn-id done. https://github.com/php-curl-class/php-curl-class/releases
