### ISSUE TITLE
Can't Install via Composer

### ISSUE THREAD

**Issue by e-baker** [php-curl-class/php-curl-class#563]
What is the expected behavior?

To install properly.

What is the actual behavior?

`composer require php-curl-class/php-curl-class
Using version ^8.3 for php-curl-class/php-curl-class
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)

Installation failed, reverting ./composer.json to its original content.

                                                                                           
  [ErrorException]                                                                         
  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?  
                                                                                           

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...`

What steps will reproduce the problem?

In my environment (iMac and MBP on Mojave) `compser require php-curl-class/php-curl-class
<img width="1212" alt="screen shot 2018-12-12 at 3 05 05 pm" src="https://user-images.githubusercontent.com/1530714/49895774-5ba85580-fe1f-11e8-90be-0c1587a79032.png">

**Comment by zachborboa** [comment]
Hi, Please update composer:

```bash
$ composer self-update
```

(Probably related to this bug https://github.com/composer/composer/issues/7783)
