### ISSUE TITLE
Post Curl without waiting for response

### ISSUE THREAD

**Issue by ChoonKwang** [php-curl-class/php-curl-class#566]
I would like to do a post curl request but doesn't want to wait for the external server to response. How do i actually do it with this library?

**Comment by zachborboa** [comment]
Hi. If you'd like to make asynchronous requests, you can can use `MultiCurl`. Here's an example: https://github.com/php-curl-class/php-curl-class/blob/master/examples/multi_curl_post.php

If you'd like to make non-blocking requests, try these:
```bash
$ curl --request POST "https://www.example.com/" --data "a=1&b=2&c=3" > /dev/null 2>&1 &
```
```bash
$ php do_post_request.php > /dev/null 2>&1 &
```

**Comment by ChoonKwang** [comment]
Hey, it works perfectly fine. Thanks for your help!
