### ISSUE TITLE
Proxy with multi curl

### ISSUE THREAD

**Issue by cs16lover** [php-curl-class/php-curl-class#567]
Is there a way to get proxy support with multi curl?

I'm able to set proxy as:
`	$multi_curl->setOpt(CURLOPT_PROXY, 'ip:port');`
bu it doesn't works.

Also is it possible to set proxy for each connection in multi curl?

**Comment by zachborboa** [comment]
Thank you for the suggestion. Proxy can now be set like this

```php
$multi_curl = new MultiCurl();
$multi_curl->setProxy('someproxy.com', '9999', 'username', 'password');
$multi_curl->setProxyTunnel();
$multi_curl->addGet('https://httpbin.org/ip');
$multi_curl->complete(function ($instance) {
    var_dump($instance->response);
});
$multi_curl->start();
```
