### ISSUE TITLE
Proxy does not work. 

### ISSUE THREAD

**Issue by Kuzanin** [php-curl-class/php-curl-class#571]
Used an example: https://github.com/php-curl-class/php-curl-class/blob/master/examples/proxy.php
Code:
```php
<?php
require __DIR__ . '/../vendor/autoload.php';

use \Curl\Curl;

$curl = new Curl();
$curl->setProxy('109.196.175.182', '3842', 'secret*', 'secret*');
$curl->setProxyTunnel();
$curl->get('http://httpbin.org/get');
$ip = ($curl->response->origin);
$curl->unsetProxy();
$curl->close();
echo $ip;
?>
```

**Comment by zachborboa** [comment]
Hi. Can you add to your script and provide the output of `var_dump($curl);`?

**Comment by Kuzanin** [comment]
Hi. Output: <code>object(Curl\Curl)#3 (41) { ["curl"]=> resource(5) of type (curl) ["id"]=> string(23) "5c3591e0aaeb00.84333263" ["error"]=> bool(true) ["errorCode"]=> int(7) ["errorMessage"]=> string(94) "Couldn't connect to server: Failed to connect to 109.196.175.182 port 3842: Connection refused" ["curlError"]=> bool(true) ["curlErrorCode"]=> int(7) ["curlErrorMessage"]=> string(94) "Couldn't connect to server: Failed to connect to 109.196.175.182 port 3842: Connection refused" ["httpError"]=> bool(false) ["httpStatusCode"]=> int(0) ["httpErrorMessage"]=> string(0) "" ["url"]=> string(22) "http://httpbin.org/get" ["requestHeaders"]=> object(Curl\CaseInsensitiveArray)#6 (2) { ["data":"Curl\CaseInsensitiveArray":private]=> array(1) { ["request-line"]=> string(0) "" } ["keys":"Curl\CaseInsensitiveArray":private]=> array(1) { ["request-line"]=> string(12) "Request-Line" } } ["responseHeaders"]=> object(Curl\CaseInsensitiveArray)#7 (2) { ["data":"Curl\CaseInsensitiveArray":private]=> array(1) { ["status-line"]=> string(0) "" } ["keys":"Curl\CaseInsensitiveArray":private]=> array(1) { ["status-line"]=> string(11) "Status-Line" } } ["rawResponseHeaders"]=> string(0) "" ["responseCookies"]=> array(0) { } ["response"]=> bool(false) ["rawResponse"]=> bool(false) ["beforeSendCallback"]=> NULL ["downloadCompleteCallback"]=> NULL ["successCallback"]=> NULL ["errorCallback"]=> NULL ["completeCallback"]=> NULL ["fileHandle"]=> NULL ["downloadFileName":"Curl\Curl":private]=> NULL ["attempts"]=> int(1) ["retries"]=> int(0) ["childOfMultiCurl"]=> bool(false) ["remainingRetries"]=> int(0) ["retryDecider"]=> NULL ["jsonDecoder"]=> string(25) "\Curl\Decoder::decodeJson" ["xmlDecoder"]=> string(24) "\Curl\Decoder::decodeXml" ["cookies":"Curl\Curl":private]=> array(0) { } ["headers":"Curl\Curl":private]=> object(Curl\CaseInsensitiveArray)#5 (2) { ["data":"Curl\CaseInsensitiveArray":private]=> array(0) { } ["keys":"Curl\CaseInsensitiveArray":private]=> array(0) { } } ["options":"Curl\Curl":private]=> array(14) { [10018]=> string(95) "PHP-Curl-Class/8.5.0 (+https://github.com/php-curl-class/php-curl-class) PHP/7.2.13 curl/7.62.0" [13]=> int(30) [2]=> bool(true) [20079]=> object(Closure)#4 (2) { ["static"]=> array(1) { ["header_callback_data"]=> object(stdClass)#2 (2) { ["rawResponseHeaders"]=> string(0) "" ["responseCookies"]=> array(0) { } } } ["parameter"]=> array(2) { ["$ch"]=> string(10) "" ["$header"]=> string(10) "" } } [19913]=> bool(true) [10002]=> string(22) "http://httpbin.org/get" [10004]=> string(15) "109.196.175.182" [59]=> string(4) "3842" [10006]=> string(23) "sunmarkinson1333:vp5crq" [61]=> bool(true) [10036]=> string(3) "GET" [80]=> bool(true) [10023]=> array(0) { } [44]=> bool(false) } ["jsonDecoderArgs":"Curl\Curl":private]=> array(0) { } ["jsonPattern":"Curl\Curl":private]=> string(84) "/^(?:application|text)\/(?:[a-z]+(?:[\.-][0-9a-z]+){0,}[\+\.]|x-)?json(?:-[a-z]+)?/i" ["xmlDecoderArgs":"Curl\Curl":private]=> array(0) { } ["xmlPattern":"Curl\Curl":private]=> string(53) "~^(?:text/|application/(?:atom\+|rss\+|soap\+)?)xml~i" ["defaultDecoder":"Curl\Curl":private]=> NULL ["headerCallbackData"]=> object(stdClass)#2 (2) { ["rawResponseHeaders"]=> string(0) "" ["responseCookies"]=> array(0) { } } }
</code>

**Comment by Kuzanin** [comment]
I'm Sorry. The error was that the hosting blocked requests from non-standard ports. Thank you very much.
