### ISSUE TITLE
[Error] Send file with path function

### ISSUE THREAD

**Issue by phatnt93** [php-curl-class/php-curl-class#573]
Hi,
I send a file via **path** function but it isn't working.

I send a file via **post** function then it working. You should fix README.md file

Thanks ^^!

**Comment by zachborboa** [comment]
Hi. Can you provide a code sample?

**Comment by phatnt93** [comment]
Hi,
Code example:
--------
$curl = new Curl();
$curl->post('https://api.example.com/profile/', array(
    'image' => '@path/to/file.jpg',
));

**OR**

$curl = new Curl();
$curl->post('https://api.example.com/profile/', array(
    'image' => new CURLFile('path/to/file.jpg'),
));
