### ISSUE TITLE
How to use Multi-Curl Request inside foreach loop ?

### ISSUE THREAD

**Issue by Dibbyo456** [php-curl-class/php-curl-class#578]
Hello,
I'm new to PHP but I do this love this project and I use it on many of script. I have wrote a script using this class and it's works fine but very slow.

```php
use \Curl\Curl;

// The $data is retrieved from database, it contains URL with many other things.
foreach ( $data as $single ) {

    $url = $single["url"]; //get the url
    $curl->get($url); //now fetch it

    if ( $curl->error ) {	
        //do stuff
        continue; //skip rest codes.
    }
		
    $html = $curl->response;
    //do stuff
    //update database.
}
```
I need to fetch 50k+ URLs, so I need to use Multi-CURL to make it fast but I have no idea how to use it. And of course, I read the **/examples**, but still no clue how to properly implement it inside a `foreach` loop.

I need the `curl-responses` and also the current `loop key` of my foreach loop, because I need to update database depending on the result.

Can you please help a little bit?

**Comment by merovinh** [comment]
Try this

```
use \Curl\MultiCurl;

$multi_curl = new MultiCurl();

$multi_curl->success(function ($instance){
    echo 'response: ' . $instance->url . "\n";
    echo 'response: ' . $instance->response . "\n";
    //do stuff
    //update database.
});

foreach ( $data as $single ) {
    $url = $single["url"];
    $multi_curl->addGet($link);
}

$multi_curl->start();
```
