### ISSUE TITLE
How do you handle the Internal Server Error 500 to try a retry ?

### ISSUE THREAD

**Issue by rapgithub** [php-curl-class/php-curl-class#581]
Is there a way to handle http_code numbers to make a retry according the http_code returned or when the script simple returned Internal Server Error I want to retry and not end the script running yet...

thanks

I am trying retry using:

```
    $max_retries = 3;
...
    $curl->setRetry(function ($instance) use ($max_retries) {
        return $instance->retries < $max_retries;
    });
```

but I cannot catch the http_code to retry call for specific http_code errors

also how do you handle this below using your class?

```
$http_code = curl_getinfo($curl, CURLINFO_HTTP_CODE);
```

thanks

**Comment by zachborboa** [comment]
Hi, You can use `$instance->httpStatusCode`:

```php
$curl = new Curl();
$curl->setRetry(function ($instance) {
    // Retry when the result of curl_getinfo($instance->curl, CURLINFO_HTTP_CODE) is 500, 503.
    return in_array($instance->httpStatusCode, array(500, 503));
});
```
