### ISSUE TITLE
Hi, I tried to find an example to fetch a weather api and get the results in plain json output (not php array)

### ISSUE THREAD

**Issue by inglesuniversal** [php-curl-class/php-curl-class#592]
API endpoint:

$city = $_REQUEST['city'];

https://api.apixu.com/v1/current.json?key=xxxxxxxxxxxxx&q=CITY

EXPECTED OUTPUT:

`
{"location":{"name":"Chicago","region":"Illinois","country":"United States of America","lat":41.85,"lon":-87.65,"tz_id":"America/Chicago","localtime_epoch":1562010958,"localtime":"2019-07-01 14:55"},"current":{"last_updated_epoch":1562009406,"last_updated":"2019-07-01 14:30","temp_c":31.7,"temp_f":89.1,"is_day":1,"condition":{"text":"Partly cloudy","icon":"//cdn.apixu.com/weather/64x64/day/116.png","code":1003},"wind_mph":8.1,"wind_kph":13.0,"wind_degree":320,"wind_dir":"NW","pressure_mb":1015.0,"pressure_in":30.5,"precip_mm":0.5,"precip_in":0.02,"humidity":48,"cloud":75,"feelslike_c":33.9,"feelslike_f":93.1,"vis_km":16.0,"vis_miles":9.0,"uv":8.0,"gust_mph":9.2,"gust_kph":14.8}}

`

**Comment by zachborboa** [comment]
Hi, You can use `$curl->rawResponse`.

**Comment by inglesuniversal** [comment]
(SOLVED) PHP CURL CLASS JSON OUTPUT (PRETTY)


`<?php
// Wallhaven Serch API Script



    require __DIR__ . '/vendor/autoload.php';

    use Curl\Curl;

    // curl --request GET "https://httpbin.org/get?key=value"

    $curl = new Curl();
    $curl->get('https://wallhaven.cc/api/v1/search', array(
        'q' => 'Ferrari',
    ));

    if ($curl->error) {
        echo 'Error: ' . $curl->errorCode . ': ' . $curl->errorMessage . "\n";
    } else {
        header('Content-type: Application/JSON');
        print json_encode($curl->response, JSON_PRETTY_PRINT);
    }
`
