### ISSUE TITLE
PSR HTTP standards

### ISSUE THREAD

**Issue by voku** [php-curl-class/php-curl-class#595]
Hi, I wrote a wrapper around this library ... maybe someone is interested in it, because there are some basic HTTP (PSR) interfaces implemented: WORK IN PROCESS (maybe I can also use the Encode / Decoding of this lib?!)

 - PSR-3: Logger Interface
 - PSR-7: HTTP Message Interface
 - PSR-17: HTTP Factory Interface
 - PSR-18: HTTP Client Interface 

https://packagist.org/packages/voku/httpful

**Comment by zachborboa** [comment]
Hi, Thank you for the suggestion. There was another ticket (#461) asking about implementing PSR-7's `RequestInterface` and `ResponseInterface`.
