### ISSUE TITLE
How to unset a opt?

### ISSUE THREAD

**Issue by Dibbyo456** [php-curl-class/php-curl-class#599]
For example:

I have added:

```php
$curl->setOpt( CURLOPT_INTERFACE, 'foo' );
```
Now, how can I `unset` it?

I'm doing a foreach loop, i need to set or unset it time to time.

**Comment by zachborboa** [comment]
Setting to `null` should work:
```php
$curl->setOpt(CURLOPT_INTERFACE, null);
```
per https://curl.haxx.se/libcurl/c/CURLOPT_INTERFACE.html

**Comment by zachborboa** [comment]
I'm not sure of your use case, but you may want to simply use a new curl instance for each request.

```php
for (...) {
  $curl = new Curl();
  $curl->get(...);
  $curl->close();
}
```

**Comment by Dibbyo456** [comment]
Can you have a look? - https://www.reddit.com/r/PHPhelp/comments/cybag6/curlopt_interface_null_fails_to_run_curl/
