### ISSUE TITLE
[Question] MultiCurl vs Zebra_cURL

### ISSUE THREAD

**Issue by Dibbyo456** [php-curl-class/php-curl-class#600]
Does the Multi-cURL class works same way like Zebra_cURL?

> Zebra_cURL is a high performance PHP cURL which not only allows the running of multiple asynchronous requests at once, but also finished threads can be processed right away without having to wait for the other threads in the queue to finish.

https://github.com/stefangabos/Zebra_cURL

**Comment by zachborboa** [comment]
Hi, Zebra_cURL appears to be using cURL multi handles (`curl_multi_init()`). PHP Curl Class also makes use of the cURL multi handle functions. Here's an example of how to process requests without waiting for the queue to finish.

https://github.com/php-curl-class/php-curl-class/blob/master/examples/multi_curl_get_callbacks.php
