### ISSUE TITLE
Improve multicurl download()

### ISSUE THREAD

**Issue by Dibbyo456** [php-curl-class/php-curl-class#602]
`Curl::download` and `MultiCurl::addDownload` uses different logic to download files.
And judging by the codes I would say `Curl::download` is much much better. Why not implement/use the same logic in `MultiCurl::addDownload` ?

Also, `Curl::download` and `MultiCurl::addDownload` both honor `cURL timeout`, I had a hard time debugging why I could not download a 300mb files. I think something could also be done there.

**Comment by zachborboa** [comment]
Thanks for the suggestion. download and addDownload have been more unified.

**Comment by Dibbyo456** [comment]
In the latest commit files getting saved as "`34564.zip.pccdownload`"
the `.pccdownload` not removing. please check.
