### ISSUE TITLE
How to handle the http code 202 ? 

### ISSUE THREAD

**Issue by baijiming** [php-curl-class/php-curl-class#605]
I try to fetch a json data from a url, but it always return the http code 202 at first, and then it will go to  the url automatically to get the real data, the http code is 200 at this time.

**Comment by zachborboa** [comment]
Hi, the HTTP status code 202 means the request has been accepted. The request should not do a redirect to get the real data. To handle the 202 response, use the following:
```php
var_dump($curl->response);
```
