### ISSUE TITLE
Need help to post array as string

### ISSUE THREAD

**Issue by dharmesh-bytes** [php-curl-class/php-curl-class#612]
What is the expected behavior?
need proper responce
What is the actual behavior?
not getting any responce
What steps will reproduce the problem?
need to post like this
[  {    "query": "query ReviewListQuery($locationId: Int!, $offset: Int, $limit: Int, $filters: [FilterConditionInput!], $prefs: ReviewListPrefsInput, $initialPrefs: ReviewListPrefsInput, $filterCacheKey: String, $prefsCacheKey: String) {     locations(locationIds: [$locationId]) {    locationId    name    reviewListPage(page: {offset: $offset, limit: $limit}, filters: $filters, prefs: $prefs, initialPrefs: $initialPrefs, filterCacheKey: $filterCacheKey, prefsCacheKey: $prefsCacheKey) {    totalCount    reviews {    ... on Review {    id    createdDate    publishedDate    title    text    tripInfo {    stayDate    tripType    }    userProfile {    isVerified    displayName    hometown {    location {    additionalNames {    long    }    name    }    }    contributionCounts {    sumAllUgc    helpfulVote    }    }    additionalRatings {    rating    ratingLabel    }    mgmtResponse {    id    text    publishedDate    username    connectionToSubject    }    rating    photos {    id    photoSizes {    url    width    height    }    }    helpfulVotes    status    }    }    }    }    }",    "variables": {      "locationId": 12429815,      "offset": 0,      "limit": -1    }  }]
Code:
```php

```

**Comment by zachborboa** [comment]
Hi, here's an example of how to post an array as a string:
https://github.com/php-curl-class/php-curl-class/blob/master/examples/post_json.php

**Comment by Dibbyo456** [comment]
> need to post like this

What you posted is JSON data (not array).

To send the data on the remote, you need to convert it to array first.

```php
$string = '[ { "query": "query ReviewListQuery($locationId: Int!, $offset: Int, $limit: Int, $filters: [FilterConditionInput!], $prefs: ReviewListPrefsInput, $initialPrefs: ReviewListPrefsInput, $filterCacheKey: String, $prefsCacheKey: String) { locations(locationIds: [$locationId]) { locationId name reviewListPage(page: {offset: $offset, limit: $limit}, filters: $filters, prefs: $prefs, initialPrefs: $initialPrefs, filterCacheKey: $filterCacheKey, prefsCacheKey: $prefsCacheKey) { totalCount reviews { ... on Review { id createdDate publishedDate title text tripInfo { stayDate tripType } userProfile { isVerified displayName hometown { location { additionalNames { long } name } } contributionCounts { sumAllUgc helpfulVote } } additionalRatings { rating ratingLabel } mgmtResponse { id text publishedDate username connectionToSubject } rating photos { id photoSizes { url width height } } helpfulVotes status } } } } }", "variables": { "locationId": 12429815, "offset": 0, "limit": -1 } }]';

// Convert the data to Array
$data = json_decode($string, true);

$curl = new Curl();
$curl->setHeader('Content-Type', 'application/json');
$curl->post('https://httpbin.org/post', $data);
var_dump($curl->response->json);
```
