### ISSUE TITLE
public methods

### ISSUE THREAD

**Issue by bkdotcom** [php-curl-class/php-curl-class#613]
Curl.php

There doesn't appear to be any non-internal use for the following methods and they should probably be declared private

*  `call`  used internally as a helper/shortcut for `call_user_func_array`
* `execDone` : called by exec

**Comment by zachborboa** [comment]
Hi, `call` is used by `class MultiCurl`
https://github.com/php-curl-class/php-curl-class/blob/54be433a7299c15b024ba808e10a96c5d5791d99/src/Curl/MultiCurl.php#L991

`execDone` is used by `class MultiCurl`

**Comment by bkdotcom** [comment]
I should have dug deeper...
