### ISSUE TITLE
Rate limiter on multi_curl()

### ISSUE THREAD

**Issue by Dibbyo456** [php-curl-class/php-curl-class#616]
Often times API or websites rate limits certain amounts of requests per minute. In `multi_curl()` this causes problem. A built in rate limiter would be extremely useful in such cases. Guzzle has something called [guzzle-rate-limiter-middleware](https://github.com/spatie/guzzle-rate-limiter-middleware)

Probably will be like:

```php
MultiCurl::perSecond(3); // Max. 3 requests per second

MultiCurl::perMinute(5); // Max. 5 requests per minute
```

**Comment by Dibbyo456** [comment]
Hi, @zachborboa Any update on this?

**Comment by zachborboa** [comment]
Hi @Dibbyo456, while I do recognize the usefulness of a feature like this, I haven't started an implementation. At a high level, I want to make this feature use a token bucket and be callable as such:
```php
$curl->setRateLimit('60/m');
```

**Comment by Dibbyo456** [comment]
That would be more useful. ❤

**Comment by zachborboa** [comment]
Implemented in https://github.com/php-curl-class/php-curl-class/pull/639.

**Comment by Dibbyo456** [comment]
Awesome. Thank you very much. ❤

**Comment by zachborboa** [comment]
@Dibbyo456 you're very welcome

**Comment by Dibbyo456** [comment]
Oh one more thing, you need to authenticate your Github with Packagist, so the package gets updated automatically. Right now it isn't the case.

**Comment by zachborboa** [comment]
> Oh one more thing, you need to authenticate your Github with Packagist, so the package gets updated automatically. Right now it isn't the case.

@Dibbyo456 should be fixed. Thanks for the reminder
