### ISSUE TITLE
SSL connect error

### ISSUE THREAD

**Issue by alexeydg** [php-curl-class/php-curl-class#621]
In laradock (docker) i have error:

"SSL connect error: error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol"
simple php curl work without error

**Comment by zachborboa** [comment]
Hi, Please try using the verbose option.

```php
$curl = new Curl();
$curl->verbose();
```

The supported protocols inside the container may need to be updated. Something like this may work:
```bash
sudo apt-get install ca-certificates
```

**Comment by alexeydg** [comment]
ca-certificates was installed. php 7.3:
`$this->curl = new Curl();
        $this->curl->verbose();`
{
    "message": "Use of undefined constant STDERR - assumed 'STDERR' (this will throw an Error in a future version of PHP)",
    "exception": "ErrorException",
    "file": "/var/www/project.loc/vendor/php-curl-class/php-curl-class/src/Curl/Curl.php",
    "line": 1282,
    "trace": [
        {
            "file": "/var/www/project.loc/vendor/php-curl-class/php-curl-class/src/Curl/Curl.php",
            "line": 1282,
            "function": "handleError",
            "class": "Illuminate\\Foundation\\Bootstrap\\HandleExceptions",
            "type": "->"
        },

**Comment by alexeydg** [comment]
i add:
```
if(!defined('STDIN'))  define('STDIN',  fopen('php://stdin',  'rb'));
    if(!defined('STDOUT')) define('STDOUT', fopen('php://stdout', 'wb'));
    if(!defined('STDERR')) define('STDERR', fopen('php://stderr', 'wb'));

```
anyway error: SSL connect error: error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol

**Comment by zachborboa** [comment]
what domain are you connecting to when you get this ssl connection error? If possible, do you a sample code to reproduce?
