### ISSUE TITLE
base_url on MultiCurl does not work

### ISSUE THREAD

**Issue by Dibbyo456** [php-curl-class/php-curl-class#628]
`base_url` on `MultiCurl` does not work.

**Code**:
```php
$multi_curl = new MultiCurl('https://httpbin.org');

$multi_curl->error(function ($instance) {
    print_r($instance); die;
});

$multi_curl->addGet('/status/200');

$multi_curl->start();
```

`print_r` output:

```
[curl] => Resource id #16
[id] => 0
[error] => 1
[errorCode] => 3
[errorMessage] => URL using bad/illegal format or missing URL
[curlError] => 1
[curlErrorCode] => 3
[curlErrorMessage] => URL using bad/illegal format or missing URL
[httpError] =>
[httpStatusCode] => 0
[httpErrorMessage] =>
[url] => /status/200
[requestHeaders] => Curl\CaseInsensitiveArray Object
....
```

The `[url] => /status/200` is wrong. It should be `[url] => https://httpbin.org/status/200`

**Comment by Dibbyo456** [comment]
Changing this line https://github.com/php-curl-class/php-curl-class/blob/85c9a1a5e9017d868718adb9ca9cd797c9d2555a/src/Curl/MultiCurl.php#L146

to

```php
$curl = new Curl($this->baseUrl);
```

Seems to fix the issue. But I still don't understand this lines:
https://github.com/php-curl-class/php-curl-class/blob/85c9a1a5e9017d868718adb9ca9cd797c9d2555a/src/Curl/MultiCurl.php#L142-L145

`addGet()` also accepting `$url` as array?

**Comment by Dibbyo456** [comment]
Can you explain this lines? https://github.com/php-curl-class/php-curl-class/blob/85c9a1a5e9017d868718adb9ca9cd797c9d2555a/src/Curl/MultiCurl.php#L142-L145

Is this some sort of fail-safe if parameters has swapped?

**Comment by zachborboa** [comment]
> Can you explain this lines?
> 
> https://github.com/php-curl-class/php-curl-class/blob/85c9a1a5e9017d868718adb9ca9cd797c9d2555a/src/Curl/MultiCurl.php#L142-L145
> 
> Is this some sort of fail-safe if parameters has swapped?

These lines allow calling `addGet` two ways:
```php
$multi_curl = new MultiCurl();
$multi_curl->addGet('https://www.example.com/', array(
    'q' => 'hello world',
));
```

```php
$multi_curl = new MultiCurl();
$multi_curl->setUrl('https://www.example.com/');
$multi_curl->addGet(array(
    'q' => 'hello world',
));
```

**Comment by Dibbyo456** [comment]
Ah. That's pretty cool. Don't know how I missed it from `/examples`. Thank you.

**Comment by Naresh206** [comment]
Hi Team,

Can you please anyone work zoho inventory invoice, How to send the our
invoice data to zoho invoice,

Thanks,
Naresh A.

**Comment by zachborboa** [comment]
> `base_url` on `MultiCurl` does not work.
> 
> **Code**:
> 
> ```
> $multi_curl = new MultiCurl('https://httpbin.org');
> 
> $multi_curl->error(function ($instance) {
>     print_r($instance); die;
> });
> 
> $multi_curl->addGet('/status/200');
> 
> $multi_curl->start();
> ```

When setting the base url in new `MultiCurl` instances, subsequent `addGet()` `addPost()`, etc. calls are for specifying different data (not different url paths). Calling `addGet` with only an array as the parameter will use the array data for constructing the query string. When calling the other request methods like `addPost()` with only an array as the parameter, the data is sent in the request body.

```php
$multi_curl = new MultiCurl('https://httpbin.org');
$multi_curl->complete(function ($instance) {
    var_dump($instance->effectiveUrl);
});
$multi_curl->addGet(array(
    'a' => '1',
    'b' => '2',
    'c' => '3',
));
$multi_curl->addPost(array(
    'd' => '4',
    'e' => '5',
    'f' => '6',
));
$multi_curl->start();
```

```
string(32) "https://httpbin.org/?a=1&b=2&c=3"
string(20) "https://httpbin.org/"
```

I haven't yet figured out if it's possible to support specifying new request _paths_ in methods like `addGet` and `addPost` without conflicting with existing functionality.

**Comment by Dibbyo456** [comment]
Can you try out the pull #629 and let me the issue with it? Because for me the patch works every way.

```php
$multi_curl = new MultiCurl('https://httpbin.org');
$multi_curl->complete(function ($instance) {
    var_dump($instance->effectiveUrl);
});
$multi_curl->addGet(array(
    'a' => '1',
    'b' => '2',
    'c' => '3',
));
$multi_curl->addPost(array(
    'd' => '4',
    'e' => '5',
    'f' => '6',
));
```
```php
string(20) "https://httpbin.org/"
string(32) "https://httpbin.org/?a=1&b=2&c=3"
```
and

```php
$multi_curl = new MultiCurl('https://httpbin.org');
$multi_curl->complete(function ($instance) {
    var_dump($instance->effectiveUrl);
});
$multi_curl->addGet('/foo', array(
    'a' => '1',
    'b' => '2',
    'c' => '3',
));
$multi_curl->addPost('/foobar', array(
    'd' => '4',
    'e' => '5',
    'f' => '6',
));
```
```php
string(35) "https://httpbin.org/foo?a=1&b=2&c=3"
string(26) "https://httpbin.org/foobar"
```

As you can see both codes has correct `effectiveUrl`; don't really see the issue here.

**Comment by zachborboa** [comment]
Merged. Thanks!
