### ISSUE TITLE
Unable to pull latest commit using composer

### ISSUE THREAD

**Issue by Dibbyo456** [php-curl-class/php-curl-class#630]
**What is the expected behavior?**

Pull the latest commit `2c6d228`

**What is the actual behavior?**

Composer pulling stable release instead of latest commit even when `@dev` is present.

**What steps will reproduce the problem?**

Code:
```bash
C:\Users\HARRY\myapp>composer require php-curl-class/php-curl-class @dev
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing php-curl-class/php-curl-class (dev-master 73ec46e): Cloning 73ec46ed20 from cache
Writing lock file
Generating autoload files
```

Here composer is pulling `dev-master 73ec46e` which isn't the latest commit. Also cleared composer cache but no luck. Also tried:
```
composer require --dev php-curl-class/php-curl-class:dev-master
```
but no luck either, still pulling `dev-master 73ec46e`

**Comment by zachborboa** [comment]
Hi, Try adding the desired commit hash in the command:
```bash
$ composer require php-curl-class/php-curl-class:dev-master#2c6d228f5871a7a390d6723177fea4fa6ef6e104
```

**Comment by Dibbyo456** [comment]
That worked. 👍

**Comment by Dibbyo456** [comment]
I found the root cause of the issue. The package isn't automatically updating on Packigst when a new commit/release has been been made.

Packagist showing:

```
This package is not auto-updated.
Last update: 2020-04-26 15:33:40 UTC
```

There was an update button, so I forced it to update from Github.
You should enable auto update on Packigist, otherwise new release won't show up.
