### ISSUE TITLE
Question: Does the script support http2 requests?

### ISSUE THREAD

**Issue by inglesuniversal** [php-curl-class/php-curl-class#633]
something like this...

`

require_once 'HTTP/Request2.php';

$request = new Http_Request2('https://westus.api.cognitive.microsoft.com/vision/v#.#/ocr');
$url = $request->getUrl();

$headers = array(
    // Request headers
    'Content-Type' => 'application/json',
    'Ocp-Apim-Subscription-Key' => 'xxxxxxxxxxxxxxxx',
);

$request->setHeader($headers);

$parameters = array(
    // Request parameters
    'language' => 'unk',
    'detectOrientation' => 'true',
);

$url->setQueryVariables($parameters);

$request->setMethod(HTTP_Request2::METHOD_POST);

`

but in a more modern approach

**Comment by Dibbyo456** [comment]
This library uses cURL thus cURL get to decide what protocol it should use. The php be **must** build with curl with http2 support. To check wether http2 support or not do this:

Type: `php -i | grep HTTP2` or you can use `phpinfo()`

If it say YES, then PHP has built with cURL which support HTTP/2 protocol. If it says NO, then you have to build PHP from source with latest version of cURL library.

If it say YES, then cURL will automatically use HTTP/2 **when possible**.
To force cURL to explicitly use HTTP/2 you can also use (not recommended):

```php
$curl->setOpt(CURL_HTTP_VERSION_2, true);
```

**Comment by zachborboa** [comment]
Hi, are you talking about this library named HTTP_Request2? https://pear.php.net/manual/en/package.http.http-request2.php

PHP Curl Class does not natively support requests using HTTP_Request2.
