### ISSUE TITLE
why would my response be empty?

### ISSUE THREAD

**Issue by pixelpaulaus** [php-curl-class/php-curl-class#634]
What is the expected behavior?
return a response

What is the actual behavior?
the response is always empty, but rawresponse is not

What steps will reproduce the problem?
i am using it in the most stripped down basic usecase. just like in your examples.
But the response is always empty, even tho the rawresponse is not.
the response is a correctly formatted json. no errors given.

Code:
```php
$curl->response
```

**Comment by Dibbyo456** [comment]
> response is always empty, even tho the rawresponse is not.
> the response is a correctly formatted json. no errors given.

json response are always decoded by default. You can see the result using `print_r($curl->response)`

You can use `$curl->setJsonDecoder(false);` to disable the behavior. Eg:
```php
$curl = new Curl();
$curl->setJsonDecoder(false);
$curl->get('https://www.example.com/');
```
Now `$curl->response` and `$curl->getRawResponse()` should be same.

**Comment by pixelpaulaus** [comment]
But the response is json. That’s the problem.
It doesn’t seem to parse, even tho it is correct json.

**Comment by Dibbyo456** [comment]
Does the `getRawResponse()` parse when you call `json_decode()` manually to it?

**Comment by pixelpaulaus** [comment]
it does indeed...

`{"code":"INVALID_TOKEN","message":"INVALID_TOKEN: Invalid Access or Auth Token"}`

`print_r(json_decode($curl->getRawResponse()));`

```
(
    [code] => INVALID_TOKEN
    [message] => INVALID_TOKEN: Invalid Access or Auth Token
)
```

**Comment by Dibbyo456** [comment]
That's strange. If you `var_dump($curl->response)` then what does it print?

**Comment by pixelpaulaus** [comment]
```
<pre class='xdebug-var-dump' dir='ltr'>
<small>/home/dev/web-apps/whmcs/modules/servers/ssl/common.php:155:</small><font color='#3465a4'>null</font>
</pre>
```

**Comment by pixelpaulaus** [comment]
seems to be an issue getting the default decoder.
If i manualy set it to this it works...

```
$curl->setJsonDecoder(function($response) {
				    return json_decode($response, false);
				});
```

**Comment by zachborboa** [comment]
Hi, can you provide the output of `var_dump($curl);` where the response is empty? (Please remove any private data).

**Comment by zachborboa** [comment]
It may also help to use `$curl->verbose();` for debugging.

**Comment by zachborboa** [comment]
2023 update: There's now `$curl->diagnose();`.

More suggestions on https://github.com/php-curl-class/php-curl-class/blob/master/TROUBLESHOOTING.md
