### ISSUE TITLE
How to get raw request curl ?

### ISSUE THREAD

**Issue by dimaslanjaka** [php-curl-class/php-curl-class#636]
What is the expected behavior?
i want get raw request of curl. to inspect.
What is the actual behavior?
inspecting request curl.
What steps will reproduce the problem?
i dont know, ive used getrequestheaders, but saying private access
Code:
```php
$header_request = $curl->getRequestHeaders();
```

**Comment by zachborboa** [comment]
Hi, Try `var_dump($curl->requestHeaders)`.

**Comment by dimaslanjaka** [comment]
thanks i can use

foreach($curl->requestHeaders as $key => $val){
var_dump($key, $val);
}
