### ISSUE TITLE
Question: Can this script work to proxy Shoutcast http request locally?

### ISSUE THREAD

**Issue by inglesuniversal** [php-curl-class/php-curl-class#637]
ShoutCast radio streams are in http ONLY

Can your script proxy those request to make them play on Chrome like a cors script through https connection?

Eg.

https://mydomain.com/php-curl-class/proxy.php?url=http://shoutcast:8000/stream.mp3

Sort of like cors-anywhere script but using a simplify approach with your awesome script.

**Comment by zachborboa** [comment]
Hi, something like this should work:
```php
use Curl\Curl;

header('Accept-Ranges: none');
header('Content-Type: audio/mpeg');

$curl = new Curl();
$curl->setTimeout(null); // Disable default timeout.
$curl->setOpt(CURLOPT_WRITEFUNCTION, function($unused_curl, $body) {
    echo $body;
    return strlen($body);
});
$curl->get('http://www.example.com/path/to/stream.mp3');
```

**Comment by zachborboa** [comment]
Associated html snippet
```html
<audio src="http://mysite.example.com/mp3_stream_proxy.php" controls autoplay />
```

**Comment by inglesuniversal** [comment]
Unbelievable!!! I worked like butter on a fresh croissant!!!!

you ROCK!!!

Stay SAFE -> The world needs developers like you :)
