### ISSUE TITLE
Change proxy on all the subsequent instances inside MultiCurl

### ISSUE THREAD

**Issue by Dibbyo456** [php-curl-class/php-curl-class#640]
```php
<?php

 $multi_curl->setRetry(function ($instance) {
    if ($instance->httpStatusCode == 429) {
        $instance->setProxy('1.1.1.1');
        return true;
    }
    return false;
 });
```

Now lets imagine `$multi_curl` was first initiated with `setProxy('8.8.8.8')`, when the request fails it retries with `setProxy('1.1.1.1')`. everything works expected.

Now let's say I've initiated 5000 `addGet()` method and started the call using `start()`. The problem is all instances first try with proxy it was initiated, then once the call fails then `setRetry()` method kicks in and retry with next proxy. Meaning every instances now making 2 calls even though I know first call will fail.

What I'm trying to do, change proxy first time (if it fails) and make all the subsequent instances use that proxy even when it was first initiated with a different proxy. This will reduce calls. I hope the explanation was easy to understand.

**Update**: On second thought I think `beforeSend($callback)` can be used in this case. However instances that are already initiated (for having `setConcurrency()`) will still use the old proxy first, then retry with new one. Right?

**Comment by zachborboa** [comment]
Hi, you could do something like this to update the list of proxies used:
```php
$multi_curl = new MultiCurl();
$multi_curl->setProxies($proxies);

$multi_curl->setRetry(function ($instance) use ($proxies, $max_retries, $multi_curl) {
    // Remove proxy used for this instance from list of proxies.
    unset($proxies[$instance->getOpt(CURLOPT_PROXY)]);

    // Update list of proxies used in future requests.
    $multi_curl->setProxies($proxies);

    if ($instance->retries < $max_retries) {
        $new_random_proxy = ArrayUtil::arrayRandom($proxies);
        $instance->setProxy($new_random_proxy);
        return true;
    } else {
        return false;
    }
});
```

**Comment by Dibbyo456** [comment]
Thanks, it worked! Although I had tweak a little bit. 👍
