### ISSUE TITLE
SetTimeout ignored

### ISSUE THREAD

**Issue by blood73** [php-curl-class/php-curl-class#641]
I receive many errors: Timeout was reached: Connection timed out after 30001 milliseconds

But in code I set:
```php
$this->curl->setConnectTimeout(120);
$this->curl->setDefaultTimeout(120);
$this->curl->setTimeout(120);
```

Looks like used const DEFAULT_TIMEOUT = 30;

So, this setting is ignored. Why? How to set connection timeout correctly?

**Comment by Dibbyo456** [comment]
> So, this setting is ignored. Why?

The setting works fine for me.

```php
<?php

$curl = new Curl\Curl();
$curl->setTimeout(3);
$curl->get('https://speed.hetzner.de/100MB.bin');

var_dump($curl->errorCode);
var_dump($curl->errorMessage);

// int(28)
// string(109) "Timeout was reached: Operation timed out after 3007 milliseconds with 8126144 out of 104857600 bytes received"
```

**Comment by zachborboa** [comment]
> $this->curl->setDefaultTimeout(120);
`setDefaultTimeout()` is not meant to be called with any parameters.

`setConnectTimeout()` configures `CURLOPT_CONNECTTIMEOUT` which is for the maximum time to  allow the connection phase to the server to take.

`setTimeout()` configures `CURLOPT_TIMEOUT` which is for the maximum time that the transfer operation can take.

**Comment by zachborboa** [comment]
I think `$this->curl->setDefaultTimeout(120);` is incorrect since `Curl::setDefaultTimeout()` doesn't accept any parameters. Use `Curl::setTimeout()` to set your desired timeout. Please comment if you're still having trouble. Thanks
