### ISSUE TITLE
need php-curl save_as downloader

### ISSUE THREAD

**Issue by inglesuniversal** [php-curl-class/php-curl-class#642]
Hi:

I have a bunch of files on a remote bucket (doc, xls, ppt, pdf, mp4, mp3, wav, flac, pages, zip, png, gif, jpeg, etc) 

just about every imaginable extension...

When the users clicks on LINK... most files are shown or played on browser.

I want the file to be forced to be download instead of being displayed to the user.

Is there a way to do it with your wonderful script? Keeping the original filename and extension once downloaded to the cellphone or computer?

Best regards and STAY SAFE!

**Comment by Dibbyo456** [comment]
Can you provide example link?

**Comment by inglesuniversal** [comment]
thanks for your prompt reply...

this is the PHP code I have so far...

`<?php

$file = $_REQUEST['file'];
header('Content-type: octet/stream');
header('Content-disposition: attachment; filename='.$file.';');
header('Content-Length: '.filesize($file));
readfile($file);
exit;

?>`

This code is expecting to have the files within the same folder. That's where I have the problem, because If I try to add a remote URL, I get the url as part of the download name with 0 bytes file size (empty). ---> https___remote.bucket.com_filename.mp4

Hope this info is helpful.

**Comment by zachborboa** [comment]
```php
// https://www.example.com/?file=myfile.bin
$filename = basename($_GET['file']);
if (is_file($file)) {
    header('Content-type: octet/stream');
    header('Content-disposition: attachment; filename="' . $filename . '"');
    header('Content-Length: ' . filesize($filename));
    readfile($filename);
}
```

**Comment by inglesuniversal** [comment]
thanks

**Comment by inglesuniversal** [comment]
Here is a better explanation of what I want to accomplish:

Sample image stored on Google Bucket

`<a href="https://firebasestorage.googleapis.com/v0/b/mycloudvip-storage.appspot.com/o/GMbRXZARq1AqDGD0xTZ4%2F3aRuYkN2zmRDYcHozSGk.jpeg?alt=media&token=61acd73c-2298-4fae-abd2-c16e0f65ea64" download="jueguito.jpeg" target="_blank">GAME IMAGE</a>
`

The above code just opens the link on a new tab, but I don't want the user to see the original source link.

Based on your example and this URL from stackoverflow  

https://stackoverflow.com/questions/48669232/download-remote-file-with-php-to-server-and-finally-output-to-browser

Is there a way to get a remote file with CURL and download it directly to the users browser, without previously storing the file inside that LAMP server which holds the PHP CURL Class?

Thanks for all your amazing HELP

**Comment by zachborboa** [comment]
> Is there a way to get a remote file with CURL and download it directly to the users browser, without previously storing the file inside that LAMP server which holds the PHP CURL Class?

The user downloading the file will have some sense of where the file is being downloaded from. If you want to hide the original source link when the user views the link or hovers over the link in the browser, use a link that redirects to the desired final location. Another option is just to host the file where you want the link to appear and link to it.
