### ISSUE TITLE
How do you send an HTTP/2 POST request?

### ISSUE THREAD

**Issue by HackerWand** [php-curl-class/php-curl-class#645]
In version 8.6, looking at $curl->requestHeaders found that the request protocol version number was HTTP/1.1

**Comment by zachborboa** [comment]
Hi, I think this should do it:

```php
$curl->setOpt(CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_2_0);
```

Requires PHP 5.5.24+

**Comment by HackerWand** [comment]
@zachborboa 

I tried this approach with PHP 7.1.1, but the resulting request header is still HTTP/1.1

**Comment by zachborboa** [comment]
@HackerWand it could be that the server doesn't support HTTP2.

I didn't have to set CURLOPT_HTTP_VERSION to get HTTP2 support. Here's what I tried:
```php
$curl = new Curl();
$curl->get('https://httpbin.org/get');
var_dump($curl->requestHeaders['request-line']);
var_dump($curl->responseHeaders['status-line']);
```

```
string(15) "GET /get HTTP/2"
string(11) "HTTP/2 200 "
```

**Comment by HackerWand** [comment]
@zachborboa 
Maybe it's my PHP version? The following code execution results are still HTTP/1.1
```php
require __DIR__ . '/php/lib/vendor/autoload.php';
use \Curl\Curl;

$curl = new Curl();
$curl->get('https://httpbin.org/get');
var_dump($curl->requestHeaders['request-line']);
var_dump($curl->responseHeaders['status-line']);
```
![image](https://user-images.githubusercontent.com/12233185/88195516-b730fb00-cc72-11ea-8c26-510127bb58cc.png)
![image](https://user-images.githubusercontent.com/12233185/88195572-c617ad80-cc72-11ea-934c-4a76c9011e43.png)

**Comment by peter279k** [comment]
According to this  [comment](https://github.com/php-curl-class/php-curl-class/issues/645#issuecomment-662520955), I think it has to ensure following things:

- You've to ensure that specific requested remote server supports `HTTP/2`.
- If the remote server is on local machine, I think the `HTTP/2` support is not configured properly.
