### ISSUE TITLE
Modify next request based on the response of the previous request

### ISSUE THREAD

**Issue by gustavo-a** [php-curl-class/php-curl-class#646]
I am using the MultiCurl class to make some requests to an external server, and I need to modify some data on the database for each response I get. This modified data will be used on the next request.

I tried someting like this:
```php
$curl = new MultiCurl();

$curl->success( function ($instance){
  do_something($instance->response);
});

foreach( $mydata as $item ){

  $dataToSend['name'] = $item->name;

  if( 0 !== $item->parent ){ //this 'parent' is a reference to the previous item on $mydata array
    $dataToSend['whatever'] = get_parent_data($item->parent);
  }

  $curl->addPost('http://externalserver.com', $dataToSend);
}

$curl->start();

```

But it didn't work. My guess is that the success callback is only called when the MultiCurl class finishes all requests. I need it to be called after each request has succeded.

Is this possible? If so, how can I achieve this? If not, is there some alternative?

Thanks in advance.

**Comment by peter279k** [comment]
These multiple cURL features depend on PHP `curl_multi_*` functions.

And it doesn't include create next request until the previous request has the response.

If you want to achieve this goal, I think you can consider using normal `Curl` request to accomplish this issue.

**Comment by gustavo-a** [comment]
Thanks! I've been beating my brains out trying to figure out how to do that with `MultiCurl`.
Got it working using normal `Curl`.
