### ISSUE TITLE
function setOptions and setHeaders not working on PUT method.

### ISSUE THREAD

**Issue by onyet** [php-curl-class/php-curl-class#651]
What is the expected behavior?
I want the Grpc-Metadata-Authorization header to fit into the Curl class

What is the actual behavior?
The Grpc-Metadata-Authorization header is not set when making a put request

What steps will reproduce the problem?
use function setOptions or setHeaders.

Code:
```php

$api = new Curl();
$api->setHeaders(array(
            "Content-Type: application/json",
            "Accept: application/json",
            "Grpc-Metadata-Authorization: Bearer <TOKEN_HERE>"
        ));
$api->put('url','data');

```
OR
```php

$api = new Curl();$
api->setOpts(array(
        CURLOPT_RETURNTRANSFER=> 1,
        CURLOPT_HTTPHEADER    => array(
            "Content-Type: application/json",
            "Accept: application/json",
            "Grpc-Metadata-Authorization: Bearer <TOKEN_HERE>"
        )
    ));
$api->put('url','data');

```

it works without problems if using setOpt or setHeader

**Comment by zachborboa** [comment]
Hi, please use an associative array with the `setHeaders` function:

```php
$api = new Curl();
$api->setHeaders(array(
    'Content-Type' => 'application/json',
    'Accept' => 'application/json',
    'Grpc-Metadata-Authorization' => 'Bearer <TOKEN_HERE>',
));
$api->put('url', 'data');
```

(Support for using an indexed array with the `setHeaders` function was added in
https://github.com/php-curl-class/php-curl-class/commit/37c605f9e40044f18f80bc99332de78881e1b69f)
