### ISSUE TITLE
Feature request: load HTML content from a remote URL

### ISSUE THREAD

**Issue by inglesuniversal** [php-curl-class/php-curl-class#652]
Just as the proxy example provided before (BIG THANKS) to play http://non-ssl-audio.mp3

I would like to know if there is a way to load to the BODY an external webpage which cannot typically be loaded into an IFRAME

Thanks

**Comment by Dibbyo456** [comment]
`.mp3` is not html.

**Comment by inglesuniversal** [comment]
Yes, you are totally right. My previous issue had to do with playing a ShoutCast livestream which typically are non-ssl URL's and the example I got back did the trick by creating some kind of proxy and allowing me to have my site's url plus the non-ssl url all in one single link, thus, being able to play it without any browser's errors --> https://mysite.com/php-curl-class.php?url=http://111.222.333:1234/stream.mp3

So, now my request is based on bringing an external website and being able to embed it inside an iFrame, is that possible with your script?

Thanks

**Comment by zachborboa** [comment]
Hi (and apologies for the late response). Serving content of an external website on your site may work for simple pages (e.g. text). However, more complex pages (with javascript, media, etc.) are unlikely to work without quite a bit of additional effort.

You may want to try asking on https://stackoverflow.com/
