### ISSUE TITLE
Migrate continuous integration

### ISSUE THREAD

**Issue by zachborboa** [php-curl-class/php-curl-class#657]
What is the expected behavior?
Continuous integration should be running regularly.

What is the actual behavior?
The continuous integration cron was last run nearly 2 months ago (Nov 26, 2020).
https://travis-ci.com/github/php-curl-class/php-curl-class/builds

What steps will reproduce the problem?
New commits, pull requests, etc. aren't triggering tests.

Possible options:
- GitHub Actions
- CircleCI

**Comment by peter279k** [comment]
I think the GitHub Action is better than CirecleCI because the it's supported by official GitHub.

And it's not necessary to add/configure third-party CI service.
