### ISSUE TITLE
PHP 5.3 incompatibility tags 8.9.1 and 8.9.2

### ISSUE THREAD

**Issue by Idrinth** [php-curl-class/php-curl-class#666]
What is the expected behavior?

8.9.1 and 8.9.2 work with php 5.3

What is the actual behavior?

8.9.1 and 8.9.2 use `[]` instead of `array()` in Curl.php:349 and create a parse error with that.

**Comment by zachborboa** [comment]
Fixed in https://github.com/php-curl-class/php-curl-class/commit/7865d3d76acddfb2882810f2b9c104f51464b263. Thanks
