### ISSUE TITLE
Supplied resource is not a valid cURL handle resource

### ISSUE THREAD

**Issue by IMN-MichaelL** [php-curl-class/php-curl-class#670]
This problem was resolved a very long time ago in the following issue: https://github.com/php-curl-class/php-curl-class/issues/18 but was apparently lost in future updates. I am using 9.1.0.

https://github.com/php-curl-class/php-curl-class/blob/2e63c0d00a65ada99106def2ddba9d4b1ffa99d9/src/Curl/Curl.php#L213

**Comment by zachborboa** [comment]
Thanks!
