### ISSUE TITLE
How to GET a whole HTML code after execution?

### ISSUE THREAD

**Issue by BSzmiszke** [php-curl-class/php-curl-class#677]
What is the expected behavior?
I want to get a whole HTML content after the request being made.

What is the actual behavior?
No request data being returned at all.

What steps will reproduce the problem?

Code:
```php
$curl->get($url);
        $data = $curl->response;
        $curl->close();
        var_dump($data);

//results in string(0) "" where for example file_get_contents prints all HTML code.
```

**Comment by zachborboa** [comment]
Hi. Try debugging with the following:
```php
var_dump($curl);
```

If you update the library, there is a `Curl::diagnose()` method that has been recently added to assist in troubleshooting:
```php
$curl->diagnose();
```
