### ISSUE TITLE
MultiCurl POST should not add data automatically as URL params because this leads to 414 Request-URI Too Long

### ISSUE THREAD

**Issue by tgerakitis** [php-curl-class/php-curl-class#686]
What is the expected behavior?
Optimally, URL params and Body Params can be set individually

What is the actual behavior?
I want to send a body with more than 2000 characters which leads to a `414 Request-URI Too Long`

Issue was introduced in [8.9.4](https://github.com/php-curl-class/php-curl-class/compare/8.9.3...8.9.4#diff-fddc86c3cd09c6f7cf5e5169f91574803ffa90a1a944b2ebd69eb073eea11f06L262)

In this line, the `$data` gets set as URL parameters.
https://github.com/php-curl-class/php-curl-class/blob/712f3555bcf46a84df77aa45c15c2a7fc786a719/src/Curl/MultiCurl.php#L279

**Comment by zachborboa** [comment]
Thanks!
