### ISSUE TITLE
Example to add

### ISSUE THREAD

**Issue by redorbit1** [php-curl-class/php-curl-class#702]
Hello,

First, thanks for your work on this library.
I spent sometime trying to figure out how to get responses from multi_curl to use for later processing. Figured it out and thought other couple benefit from this example:

```
use Curl\MultiCurl;

// urls array
$urls = ["https://www.example1.com",
        "https://www.example1.com",
        "https://www.example1.com"];

// array to hold responses
$responses = [];

$multi_curl = new MultiCurl();
$multi_curl->setProxies(PRIVATE_PROXIES["ips"]);
$multi_curl->setProxyAuth(PRIVATE_PROXIES["creds"]);
$multi_curl->setProxyTunnel();
foreach ($urls as $url) {
    $multi_curl->addGet($url);
}
$multi_curl->complete(function ($instance) use (&$responses) {
    $responses[] = $instance->response;
});
$multi_curl->start();

$responses; // this is an array of response from multi_curl to use
```

**Comment by zachborboa** [comment]
Thanks!

**Comment by Philipp91** [comment]
Is there any guarantee for the order of the `$responses`?

On a related note, `addDownload()` takes a callback. Why doesn't `addGet()` also take one?

**Comment by zachborboa** [comment]
> Is there any guarantee for the order of the $responses?

No. There's `$instance->id` available to help identify.

> On a related note, addDownload() takes a callback. Why doesn't addGet() also take one?

`MultiCurl::addDownload` is different from all the other request types (`MultiCurl::addGet`, `MultiCurl::addPost`, etc.).
