### ISSUE TITLE
Deprecated: Error in whole file

### ISSUE THREAD

**Issue by digitaltim-de** [php-curl-class/php-curl-class#705]
Since some days i become this deprecation error and can`t order this to some issue. I am not sure, why, i become this error.

I am using Symfony 6.0 and PHP 8.1.

```
Deprecated: Return type of Curl\CaseInsensitiveArray::offsetExists($offset) should either be compatible with 
ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily 
suppress the notice in vendor/php-curl-class/php-curl-class/src/Curl/CaseInsensitiveArray.php on line 92
```

**Comment by zachborboa** [comment]
Hi. I believed this has been fixed. Update PHP Curl Class.

Fixed in https://github.com/php-curl-class/php-curl-class/commit/dce71a0c2f0279b4372449067ff6941b122b5980
