### ISSUE TITLE
MultiCurl->beforeSend() with retry

### ISSUE THREAD

**Issue by teandr** [php-curl-class/php-curl-class#707]
Hi.

Code:
```php
        // Curl
        $curl = new Curl();

        $curl->beforeSend(function (Curl $instance) {
            echo 'Message from beforeSend callback' . PHP_EOL;
        });

        $curl->setRetry(function (Curl $instance) {
            echo $instance->getHttpStatusCode() . ' | ' . $instance->url . PHP_EOL;
            return $instance->retries < 1;
        });

        $curl->get('https://httpbin.org/status/503');
        
        //MultiCurl
        $multi_curl = new MultiCurl();

        $multi_curl->beforeSend(function (Curl $instance) {
            echo 'Message from beforeSend callback' . PHP_EOL;
        });

        $multi_curl->setRetry(function (Curl $instance) {
            echo $instance->getHttpStatusCode() . ' | ' . $instance->url . PHP_EOL;
            return $instance->retries < 1;
        });

        $multi_curl->addGet('https://httpbin.org/status/503');
        $multi_curl->addGet('https://httpbin.org/status/503');

        $multi_curl->start();
```
Output:

Curl
-----
Message from beforeSend callback -> first attempt
503 | https://httpbin.org/status/503

Message from beforeSend callback -> second attempt
503 | https://httpbin.org/status/503

MultiCurl:
----------
Message from beforeSend callback -> first attempt
Message from beforeSend callback -> first attempt

503 | https://httpbin.org/status/503
503 | https://httpbin.org/status/503

-> missed messages from second attempt

503 | https://httpbin.org/status/503
503 | https://httpbin.org/status/503

Thank you

**Comment by teandr** [comment]
Hello. Thanks for the answer. I would like to see the same behavior in MultiCurl. It seems logical to me.

**Comment by zachborboa** [comment]
> I would like to see the same behavior in MultiCurl. It seems logical to me.

Agreed. However, this change will need to be included in a major version bump.

**Comment by Dibbyo456** [comment]
Any workaround until patched?

**Comment by Dibbyo456** [comment]
Hi, @zachborboa can we get a patch for this?
