### ISSUE TITLE
How we can pass Bearer Token to request?

### ISSUE THREAD

**Issue by nileshsmartwebtech** [php-curl-class/php-curl-class#711]
What is the expected behavior?
It should able to send Authorization Bearer Token. 
What is the actual behavior?
We did not found any method ro option to set Authorization Bearer Token.
What steps will reproduce the problem?

Code:
```

```

**Comment by twocore** [comment]
Mostly the Authorization Token is sent as HTTP header, for example in the work4all API (ERP/CRM, Germany). You can use the `setHeader()` method to set them:

`$curl->setHeader('Authorization', 'bearer <token>');`

**Comment by zachborboa** [comment]
> `$curl->setHeader('Authorization', 'bearer <token>');`

correct.
