### ISSUE TITLE
MultiCurl::stop() don't work as expected

### ISSUE THREAD

**Issue by Allyans3** [php-curl-class/php-curl-class#714]
MultiCurl::stop() don't work without $multi_curl->setConcurrency(1).

I want to make, for example, 30 requests with proxy, timeout and connection_timeout at the same time and when 1 of 30 requests will be successful, stop others immediately.

Code from your test file, but without setConcurrency() method:
```php
const TEST_URL = "https://httpbin.org/ip";

$multi_curl = new MultiCurl();
$request_count = 0;

$multi_curl->success(function ($instance) use (&$request_count, $multi_curl) {
    $request_count += 1;
    $multi_curl->stop();
});

$multi_curl->addGet(TEST_URL);
$multi_curl->addGet(TEST_URL);
$multi_curl->addGet(TEST_URL);

$multi_curl->start();

dd($request_count); // 3, not 1
```

**Comment by zachborboa** [comment]
Fixed. Thanks!
