### ISSUE TITLE
Posting data with an integer key

### ISSUE THREAD

**Issue by ajdunn2** [php-curl-class/php-curl-class#725]
Since 9.6.1, I cannot post data with a key that happens to be a number.
Tested with PHP 7.4 and 8.0

What is the expected behavior?
- Able to POST using an array containing an integer key

What is the actual behavior?
`TypeError: urlencode() expects parameter 1 to be string, integer given`

What steps will reproduce the problem?

Code:
```php

$curl = new Curl();
$curl->post('https://www.example.com/', [
    'string' => 'thisisfine',
    '12345678' => 'thisbreaks',
]);

```

This appears to be related to `$k` https://github.com/php-curl-class/php-curl-class/blob/642e232dc2c518e1345e204bff19d6d2ebf64bce/src/Curl/Curl.php#L210

The following change appears to fix the issue.

```php
                return urlencode(strval($k)) . '=' . urlencode(strval($v));
```

**Comment by zachborboa** [comment]
Thanks!

**Comment by ajdunn2** [comment]
Thank you!!
