### ISSUE TITLE
buildPostData() throws an error in PHP 8 if $data is an object

### ISSUE THREAD

**Issue by tgerakitis** [php-curl-class/php-curl-class#727]
This line needs an array cast https://github.com/php-curl-class/php-curl-class/blob/57745cabd6077c2f4ac7fed837e246d83e18ec74/src/Curl/Curl.php#L211

Since PHP 8 `array_keys()` and `array_values()` throw an error if an object is provided: https://onlinephp.io/c/5e435

Code:
```php
...
            }, array_keys((array)$data), array_values((array)$data)));
...
```
In the past, this would only issue a warning.

**Comment by zachborboa** [comment]
Thanks!
