### ISSUE TITLE
multi_curl ，’setCookieString‘ cannot be used

### ISSUE THREAD

**Issue by zuilaoxian** [php-curl-class/php-curl-class#735]
php:7.3.4nts
php-curl-class: dev

$multi_curl->setCookieString($cookiestr); cannot be used

![微信截图_20221105172727](https://user-images.githubusercontent.com/61530237/200113094-8d002e19-7950-4b4d-aa15-5202cff5790a.png)

$multi_curl->setCookie($key, $value);   normal
![image](https://user-images.githubusercontent.com/61530237/200113133-43305c31-8c5a-4a46-a792-b6b4931154b3.png)

**Comment by zachborboa** [comment]
Fixed in https://github.com/php-curl-class/php-curl-class/pull/738.

Thanks!
