### ISSUE TITLE
Content-Encoding: gzip issue

### ISSUE THREAD

**Issue by JAY6390** [php-curl-class/php-curl-class#740]
What is the expected behavior?
For the content to be gunzipped before being parsed

What is the actual behavior?
gzipped content remains garbled

What steps will reproduce the problem?
This was done on the fedex API and throws a garbled mess when there is an error instead of decoding the gzipped json data. To fix this I've added this to my actual code but it's not really a great solution

```
if($curl->responseHeaders['content-encoding'] == 'gzip') {
	$curl->rawResponse = gzdecode($curl->rawResponse);
}
```

**Comment by zachborboa** [comment]
Fixed in https://github.com/php-curl-class/php-curl-class/pull/744. Thanks!
