### ISSUE TITLE
Warning  gzdecode(): data error after update to 9.12.01

### ISSUE THREAD

**Issue by juhacz** [php-curl-class/php-curl-class#747]
After update to 9.12.01 my script stop working, I get "Warning  gzdecode(): data error".

What is the expected behavior?
Get HTML page

What is the actual behavior?
Warning  gzdecode(): data error

What steps will reproduce the problem?
Update from 9.10.0 to 9.12.01m when I return to 9.10.0, all working fine.

I share Tracy logs for debugging:
http://70.34.252.222/rwqbfngwoi53423tgs/1.html
http://70.34.252.222/rwqbfngwoi53423tgs/2.html

Thank You

**Comment by zachborboa** [comment]
Thanks!

**Comment by juhacz** [comment]
There's still something wrong.
http://70.34.252.222/xxxxxxxx/exception--2022-12-12--10-55--b52046db54.html

**Comment by zachborboa** [comment]
@juhacz fixed. Thanks again!
