### ISSUE TITLE
Deprecated: Creation of dynamic property Curl\Curl::$rfc6265 is deprecated

### ISSUE THREAD

**Issue by yucho123987** [php-curl-class/php-curl-class#755]
What is the expected behavior?
Do not show the message.
What is the actual behavior?
It said "Deprecated: Creation of dynamic property Curl\Curl::$rfc6265 is deprecated in /home/yucho/CYAutoCheckIn/vendor/php-curl-class/php-curl-class/src/Curl/Curl.php on line 1908".
What steps will reproduce the problem?
Use ```setCookie``` method in PHP 8.2.
Code:
```php
$testCURL=new Curl();
$testCURL->setUserAgent($user_agent);
foreach (getCookies($cookie) as $cookie) {
  $testCURL->setCookie($cookie['name'],$cookie['value']);
}
//......
```

**Comment by mbolli** [comment]
This was just merged into master: https://github.com/php-curl-class/php-curl-class/pull/754

**Comment by zachborboa** [comment]
Yes, should be fixed in https://github.com/php-curl-class/php-curl-class/pull/754
