### ISSUE TITLE
CurlStringFile: Object of class CURLStringFile could not be converted to string

### ISSUE THREAD

**Issue by blaaat** [php-curl-class/php-curl-class#760]
What is the expected behavior?

No errors when uploading a CurlStringFile

What is the actual behavior?

Errors are triggerred unless a normal file is added to the upload as wel

What steps will reproduce the problem?

Code:
```php

$curl->post('/endpoint', [
'a' => new CurlStringFile('data','name','mime');
]);
```

**Comment by zachborboa** [comment]
Fixed. Thanks!
