### ISSUE TITLE
Return types

### ISSUE THREAD

**Issue by Wulfheart** [php-curl-class/php-curl-class#770]
I would like to add PHPDocs to add PHPDocs to all methods to add more return types. Would you be willing to merge this? If so, do you think that this would require additional tests?

**Comment by zachborboa** [comment]
Hi! I'd be interested in seeing a small sample of what changes you're thinking. I don't know if it would require additional tests

**Comment by zachborboa** [comment]
note: maybe use TypeDeclaration
https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#typedeclaration

**Comment by zachborboa** [comment]
coding standards configuration added in https://github.com/php-curl-class/php-curl-class/blob/master/tests/.php-cs-fixer.php.

#794 #795 #796
