### ISSUE TITLE
issue with response content being double decoded

### ISSUE THREAD

**Issue by deepika-maj** [php-curl-class/php-curl-class#804]
The library is showing a warning message like `... Warning: gzdecode(): data error ...` on my logs
when `$curl->setOpt(CURLOPT_ENCODING , '');` is set and the content from origin is returned as `gzip`.

Upon further inspection, I found that Curl automatically decodes the content and the following lines is double decoding already decoded contents which is the reason for such warning.

I hope someone fixes this issue.

https://github.com/php-curl-class/php-curl-class/blob/d5542274acd2331f2562ce8c787315001685de60/src/Curl/Curl.php#L1928-L1937

**Comment by zachborboa** [comment]
Hi. I'm trying to reproduce the warning message. Can you provide an example request that causes the warning?

Also, what version of PHP Curl Class are you using? I believe the current version should suppress the warning message.

Thank you

**Comment by zachborboa** [comment]
thank you for the code sample.

I was able to locate the error and it's coming up as a silenced error:
<img width="1215" alt="image" src="https://github.com/php-curl-class/php-curl-class/assets/1083146/f1989919-cdf0-47cd-ab11-406555847d80">

**Comment by deepika-maj** [comment]
Yes, it is the silenced error but why do we need that code block?
The curl by default decodes gzip content unless `CURLOPT_HTTP_CONTENT_DECODING` option is set to `0`.

The only reason I see it can add value is if we either check `CURLOPT_HTTP_CONTENT_DECODING` is set to `0` or if we can detect the `$response` is not yet decoded before processing with `gzdecode`.

**Comment by zachborboa** [comment]
Fixed in https://github.com/php-curl-class/php-curl-class/pull/808. Thanks!
