### ISSUE TITLE
Error code: 18 error message: Transferred a partial file (CURLE_PARTIAL_FILE): HTTP/2 stream 1 was not closed cleanly

### ISSUE THREAD

**Issue by KrYpToDeN** [php-curl-class/php-curl-class#838]
Hello, tell me, please, what can i do to resove this problem:

`.. URL .. was unsuccessful. error code: 18 error message: Transferred a partial file (CURLE_PARTIAL_FILE): HTTP/2 stream 1 was not closed cleanly before end of the underlying stream call to .. URL ..`

Yesterday all was OK. Today something happend.

i use big GET requests.

**Comment by zachborboa** [comment]
Hi. I'm not sure the `CURLE_PARTIAL_FILE` error is an issue with the library. From the docs, it says this error comes up when the received file is less than expected:

```
CURLE_PARTIAL_FILE (18)

A file transfer was shorter or larger than expected. This happens when the server first reports an expected transfer size, and then delivers data that does not match the previously given size.
```
from https://curl.se/libcurl/c/libcurl-errors.html#CURLEPARTIALFILE
